Yume: yume::ty::Function Class Reference
yume::ty::Function Class Reference
A function pointer type.
#include <type.hpp>
Public Member Functions
Function (string name, vector< Type > args, optional< Type > ret, vector< Type > closure, bool fn_ptr, bool c_varargs=false)
auto args () const -> const auto &
auto args () -> auto &
auto closure () const -> const auto &
auto closure () -> auto &
auto ret () const -> const auto &
auto is_fn_ptr () const
auto is_c_varargs () const
auto name () const -> string override
auto fn_memo () const -> auto *
auto closure_memo () const -> auto *
auto memo () const -> auto *
void fn_memo (Compiler &, llvm::FunctionType *memo) const
void closure_memo (Compiler &, llvm::StructType *memo) const
void memo (Compiler &, llvm::Type *memo) const
Public Member Functions inherited from yume::ty::BaseType
BaseType (const BaseType &) noexcept=delete
BaseType (BaseType &&) noexcept=delete
auto operator= (const BaseType &) noexcept -> BaseType &=delete
auto operator= (BaseType &&) noexcept -> BaseType &=delete
virtual ~BaseType ()=default
auto kind () const -> Kind
auto base_name () const -> string
virtual auto name () const -> string=0
Additional Inherited Members
Protected Member Functions inherited from yume::ty::BaseType
BaseType (Kind kind, string name)
Detailed Description
A function pointer type.
Definition at line 108 of file type.hpp.
Constructor & Destructor Documentation
Function()
yume::ty::Function::Function (string name, vector< Type > args, optional< Type > ret, vector< Type > closure, bool fn_ptr, bool c_varargs = false) inline
Definition at line 125 of file type.hpp.
Member Function Documentation
args() [1/2]
auto yume::ty::Function::args () -> auto& inline
Definition at line 130 of file type.hpp.
args() [2/2]
auto yume::ty::Function::args () const -> const auto& inline
Definition at line 129 of file type.hpp.
closure() [1/2]
auto yume::ty::Function::closure () -> auto& inline
Definition at line 132 of file type.hpp.
closure() [2/2]
auto yume::ty::Function::closure () const -> const auto& inline
Definition at line 131 of file type.hpp.
closure_memo() [1/2]
auto yume::ty::Function::closure_memo () const -> auto* inline
Definition at line 139 of file type.hpp.
Referenced by yume::Compiler::declare().
closure_memo() [2/2]
void yume::ty::Function::closure_memo (Compiler & , llvm::StructType * memo) const inline
Definition at line 143 of file type.hpp.
References memo().
fn_memo() [1/2]
auto yume::ty::Function::fn_memo () const -> auto* inline
Definition at line 138 of file type.hpp.
Referenced by yume::Compiler::declare().
fn_memo() [2/2]
void yume::ty::Function::fn_memo (Compiler & , llvm::FunctionType * memo) const inline
Definition at line 142 of file type.hpp.
References memo().
is_c_varargs()
auto yume::ty::Function::is_c_varargs () const inline
Definition at line 135 of file type.hpp.
is_fn_ptr()
auto yume::ty::Function::is_fn_ptr () const inline
Definition at line 134 of file type.hpp.
memo() [1/2]
auto yume::ty::Function::memo () const -> auto* inline
Definition at line 140 of file type.hpp.
Referenced by closure_memo(), and fn_memo().
memo() [2/2]
void yume::ty::Function::memo (Compiler & , llvm::Type * memo) const inline
Definition at line 144 of file type.hpp.
References memo().
Referenced by memo().
name()
auto yume::ty::Function::name () const -> string override virtual
Implements yume::ty::BaseType.
Definition at line 343 of file type.cpp.
References yume::ty::BaseType::base_name().
ret()
auto yume::ty::Function::ret () const -> const auto& inline
Definition at line 133 of file type.hpp.
The documentation for this class was generated from the following files:
src/yume/ty/type.hpp
src/yume/ty/type.cpp