Yume: yume::ast::AST Class Reference
yume::ast::AST Class Reference abstract
All nodes in the AST tree of the program inherit from this class.
#include <ast.hpp>
Public Member Functions
AST (const AST &)=delete
AST (AST &&)=default
auto operator= (const AST &) -> AST &=delete
auto operator= (AST &&) -> AST &=delete
virtual ~AST ()=default
virtual void visit (Visitor &visitor) const =0
Recursively visit this ast node and all its constituents.
auto val_ty () const noexcept -> optional< ty::Type >
auto ensure_ty () const -> ty::Type
void val_ty (optional< ty::Type > type)
void attach_to (nonnull< AST * > other)
Make the type of this node depend on the type of other.
auto kind () const -> Kind
auto kind_name () const -> string
Human-readable string representation of the Kind of this node.
auto token_range () const -> const span< Token > &
auto location () const -> Loc
The union of the locations of the Tokens making up this node.
virtual auto describe () const -> string
A short, string representation for debugging.
virtual auto clone () const -> AST *=0
Deep copy, except for the type and attachments.
Protected Member Functions
void unify_val_ty ()
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
auto tok () const noexcept -> span< Token >
AST (Kind kind, span< Token > tok)
Detailed Description
All nodes in the AST tree of the program inherit from this class.
AST nodes cannot be copied or moved as all special member functions (aside from the destructor) are deleted. There will always be one instance for a specific node during the lifetype of the compiler. However note that AST nodes can be cloned with the clone() method, which will produce a deep copy. This is used when instantiating a template. The clone will have the exact same structure and locations but distinct types, depending on what the types the template is instantiated with.
Definition at line 216 of file ast.hpp.
Constructor & Destructor Documentation
AST() [1/3]
yume::ast::AST::AST (Kind kind, span< Token > tok) inline protected
Definition at line 233 of file ast.hpp.
AST() [2/3]
yume::ast::AST::AST (const AST &) delete
AST() [3/3]
yume::ast::AST::AST (AST &&) default
~AST()
virtual yume::ast::AST::~AST () virtual default
Member Function Documentation
attach_to()
void yume::ast::AST::attach_to (nonnull< AST * > other) inline
Make the type of this node depend on the type of other.
See also
Attachment
Definition at line 260 of file ast.hpp.
References unify_val_ty().
Referenced by yume::semantic::TypeWalker::expression(), and yume::semantic::TypeWalker::statement().
clone()
virtual auto yume::ast::AST::clone () const -> AST * pure virtual
Deep copy, except for the type and attachments.
Implemented in yume::ast::AssignExpr, yume::ast::BoolExpr, yume::ast::CallExpr, yume::ast::CharExpr, yume::ast::Compound, yume::ast::ConstDecl, yume::ast::ConstExpr, yume::ast::CtorDecl, yume::ast::CtorExpr, yume::ast::Decl, yume::ast::DtorExpr, yume::ast::Expr, yume::ast::FieldAccessExpr, yume::ast::FnDecl, yume::ast::FunctionType, yume::ast::IfClause, yume::ast::IfStmt, yume::ast::ImplicitCastExpr, yume::ast::LambdaExpr, yume::ast::NumberExpr, yume::ast::Program, yume::ast::ProxyType, yume::ast::QualType, yume::ast::ReturnStmt, yume::ast::SelfType, yume::ast::SimpleType, yume::ast::SliceExpr, yume::ast::Stmt, yume::ast::StringExpr, yume::ast::StructDecl, yume::ast::TemplatedType, yume::ast::Type, yume::ast::TypeName, yume::ast::VarDecl, yume::ast::VarExpr, and yume::ast::WhileStmt.
describe()
auto yume::ast::AST::describe () const -> string virtual
A short, string representation for debugging.
Reimplemented in yume::ast::Decl, yume::ast::SimpleType, yume::ast::QualType, yume::ast::TemplatedType, yume::ast::SelfType, yume::ast::ProxyType, yume::ast::FunctionType, yume::ast::TypeName, yume::ast::NumberExpr, yume::ast::CharExpr, yume::ast::BoolExpr, yume::ast::StringExpr, yume::ast::VarExpr, yume::ast::ConstExpr, yume::ast::CallExpr, yume::ast::CtorExpr, yume::ast::DtorExpr, and yume::ast::SliceExpr.
Definition at line 11 of file describe.cpp.
References kind_name().
ensure_ty()
auto yume::ast::AST::ensure_ty () const -> ty::Type inline
Definition at line 246 of file ast.hpp.
References yume::yume_assert().
Referenced by yume::Compiler::expression(), yume::is_trivially_destructible(), and yume::Compiler::statement().
kind()
auto yume::ast::AST::kind () const -> Kind inline
Definition at line 266 of file ast.hpp.
Referenced by yume::CRTPWalker< Derived >::body_expression(), yume::CRTPWalker< Derived >::body_statement(), and kind_name().
kind_name()
auto yume::ast::AST::kind_name () const -> string inline
Human-readable string representation of the Kind of this node.
Definition at line 268 of file ast.hpp.
References kind(), and yume::ast::kind_name().
Referenced by yume::semantic::TypeWalker::body_expression(), yume::Compiler::body_statement(), yume::semantic::TypeWalker::body_statement(), and describe().
location()
auto yume::ast::AST::location () const -> Loc
The union of the locations of the Tokens making up this node.
Definition at line 27 of file ast.cpp.
operator=() [1/2]
auto yume::ast::AST::operator= (AST &&) -> AST &=delete delete
operator=() [2/2]
auto yume::ast::AST::operator= (const AST &) -> AST &=delete delete
tok()
auto yume::ast::AST::tok () const -> span<Token> inline protected noexcept
Definition at line 231 of file ast.hpp.
Referenced by yume::ast::AssignExpr::clone(), yume::ast::BoolExpr::clone(), yume::ast::CallExpr::clone(), yume::ast::CharExpr::clone(), yume::ast::Compound::clone(), yume::ast::ConstDecl::clone(), yume::ast::ConstExpr::clone(), yume::ast::CtorDecl::clone(), yume::ast::CtorExpr::clone(), yume::ast::DtorExpr::clone(), yume::ast::FieldAccessExpr::clone(), yume::ast::FnDecl::clone(), yume::ast::FunctionType::clone(), yume::ast::IfClause::clone(), yume::ast::IfStmt::clone(), yume::ast::ImplicitCastExpr::clone(), yume::ast::LambdaExpr::clone(), yume::ast::NumberExpr::clone(), yume::ast::Program::clone(), yume::ast::ProxyType::clone(), yume::ast::QualType::clone(), yume::ast::ReturnStmt::clone(), yume::ast::SelfType::clone(), yume::ast::SimpleType::clone(), yume::ast::SliceExpr::clone(), yume::ast::StringExpr::clone(), yume::ast::StructDecl::clone(), yume::ast::TemplatedType::clone(), yume::ast::TypeName::clone(), yume::ast::VarDecl::clone(), yume::ast::VarExpr::clone(), and yume::ast::WhileStmt::clone().
token_range()
auto yume::ast::AST::token_range () const -> const span<Token>& inline
Definition at line 269 of file ast.hpp.
unify_val_ty()
void yume::ast::AST::unify_val_ty () protected
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
Definition at line 9 of file ast.cpp.
Referenced by attach_to().
val_ty() [1/2]
auto yume::ast::AST::val_ty () const -> optional<ty::Type> inline noexcept
Definition at line 245 of file ast.hpp.
Referenced by yume::semantic::TypeWalker::expression(), and yume::semantic::TypeWalker::statement().
val_ty() [2/2]
void yume::ast::AST::val_ty (optional< ty::Type > type) inline
Definition at line 251 of file ast.hpp.
visit()
virtual void yume::ast::AST::visit (Visitor & visitor) const pure virtual
Recursively visit this ast node and all its constituents.
See also
Visitor
Implemented in yume::ast::SimpleType, yume::ast::QualType, yume::ast::TemplatedType, yume::ast::SelfType, yume::ast::ProxyType, yume::ast::FunctionType, yume::ast::TypeName, yume::ast::NumberExpr, yume::ast::CharExpr, yume::ast::BoolExpr, yume::ast::StringExpr, yume::ast::VarExpr, yume::ast::ConstExpr, yume::ast::CallExpr, yume::ast::CtorExpr, yume::ast::DtorExpr, yume::ast::SliceExpr, yume::ast::AssignExpr, yume::ast::FieldAccessExpr, yume::ast::ImplicitCastExpr, yume::ast::Compound, yume::ast::LambdaExpr, yume::ast::FnDecl, yume::ast::CtorDecl, yume::ast::StructDecl, yume::ast::VarDecl, yume::ast::ConstDecl, yume::ast::WhileStmt, yume::ast::IfClause, yume::ast::IfStmt, yume::ast::ReturnStmt, and yume::ast::Program.
Referenced by yume::Fn::ast().
The documentation for this class was generated from the following files:
src/yume/ast/ast.hpp
src/yume/ast/ast.cpp
src/yume/ast/describe.cpp