Yume: yume::ast::WhileStmt Class Reference
yume::ast::WhileStmt Class Reference
A while loop (while).
#include <ast.hpp>
Public Member Functions
WhileStmt (span< Token > tok, unique_ptr< Expr > cond, unique_ptr< Compound > body)
void visit (Visitor &visitor) override
auto body () const -> const auto &
auto cond () const -> const auto &
auto clone () const -> WhileStmt *override
Deep copy, except for the type and attachments.
auto clone () const -> Stmt *override=0
Deep copy, except for the type and attachments.
Public Member Functions inherited from yume::ast::AST
AST (const AST &)=delete
AST (AST &&)=default
auto operator= (const AST &) -> AST &=delete
auto operator= (AST &&) -> AST &=delete
virtual ~AST ()=default
virtual void visit (Visitor &visitor)=0
auto val_ty () const noexcept -> const ty::Type *
void val_ty (const ty::Type *type) const
void attach_to (const AST *other) const
Make the type of this node depend on the type of other.
auto kind () const -> Kind
auto kind_name () const -> string
Human-readable string representation of the Kind of this node.
auto token_range () const -> const span< Token > &
auto location () const -> Loc
The union of the locations of the Tokens making up this node.
virtual auto describe () const -> string
A short, string representation for debugging.
virtual auto clone () const -> AST *=0
Deep copy, except for the type and attachments.
Additional Inherited Members
Protected Member Functions inherited from yume::ast::Stmt
AST (Kind kind, span< Token > tok)
AST (const AST &)=delete
AST (AST &&)=default
Protected Member Functions inherited from yume::ast::AST
void unify_val_ty () const
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
AST (Kind kind, span< Token > tok)
Protected Attributes inherited from yume::ast::AST
const Kind m_kind
Every subclass of AST has a distinct Kind.
const span< Token > m_tok
The range of tokenizer Tokens that this node was parsed from.
const ty::Type * m_val_ty {}
The value type of this node. Determined in the semantic phase; always nullptr after parsing.
unique_ptr< Attachment > m_attach {std::make_unique<Attachment>()}
Detailed Description
A while loop (while).
Definition at line 623 of file ast.hpp.
Constructor & Destructor Documentation
WhileStmt()
yume::ast::WhileStmt::WhileStmt (span< Token > tok, unique_ptr< Expr > cond, unique_ptr< Compound > body) inline
Definition at line 628 of file ast.hpp.
Referenced by clone().
Member Function Documentation
body()
auto yume::ast::WhileStmt::body () const -> const auto& inline
Definition at line 632 of file ast.hpp.
Referenced by yume::Compiler::statement().
clone()
auto yume::ast::WhileStmt::clone () const -> WhileStmt *override override virtual
Deep copy, except for the type and attachments.
Implements yume::ast::Stmt.
Definition at line 753 of file ast.cpp.
References yume::ast::dup(), yume::ast::AST::m_tok, and WhileStmt().
cond()
auto yume::ast::WhileStmt::cond () const -> const auto& inline
Definition at line 633 of file ast.hpp.
Referenced by yume::Compiler::statement().
visit()
void yume::ast::WhileStmt::visit (Visitor & visitor) override virtual
Implements yume::ast::AST.
Definition at line 783 of file ast.cpp.
References yume::Visitor::visit().
The documentation for this class was generated from the following files:
src/ast.hpp
src/ast.cpp