Yume: yume::ast::CtorDecl Class Reference
yume::ast::CtorDecl Class Reference
A declaration of a custom constructor (def :new).
#include <ast.hpp>
Public Member Functions
CtorDecl (span< Token > tok, vector< TypeName > args, Compound body)
void visit (Visitor &visitor) const override
Recursively visit this ast node and all its constituents.
auto describe () const -> string override
A short, string representation for debugging.
auto name () const -> string override
auto args () const -> const auto &
auto args () -> auto &
auto body () const -> const auto &
auto body () -> auto &
auto clone () const -> CtorDecl *override
Deep copy, except for the type and attachments.
auto clone () const -> Decl *override=0
Deep copy, except for the type and attachments.
virtual auto name () const -> string=0
auto clone () const -> Stmt *override=0
Deep copy, except for the type and attachments.
Public Member Functions inherited from yume::ast::AST
AST (const AST &)=delete
AST (AST &&)=default
auto operator= (const AST &) -> AST &=delete
auto operator= (AST &&) -> AST &=delete
virtual ~AST ()=default
virtual void visit (Visitor &visitor) const =0
Recursively visit this ast node and all its constituents.
auto val_ty () const noexcept -> optional< ty::Type >
auto ensure_ty () const -> ty::Type
void val_ty (optional< ty::Type > type)
void attach_to (nonnull< AST * > other)
Make the type of this node depend on the type of other.
auto kind () const -> Kind
auto kind_name () const -> string
Human-readable string representation of the Kind of this node.
auto token_range () const -> const span< Token > &
auto location () const -> Loc
The union of the locations of the Tokens making up this node.
virtual auto describe () const -> string
A short, string representation for debugging.
virtual auto clone () const -> AST *=0
Deep copy, except for the type and attachments.
Additional Inherited Members
Protected Member Functions inherited from yume::ast::Stmt
AST (Kind kind, span< Token > tok)
AST (const AST &)=delete
AST (AST &&)=default
Protected Member Functions inherited from yume::ast::AST
void unify_val_ty ()
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
auto tok () const noexcept -> span< Token >
AST (Kind kind, span< Token > tok)
Detailed Description
A declaration of a custom constructor (def :new).
The arguments of a constructor may be regular TypeNames, just as in regular function declarations, but they also may be a FieldAccessExpr without a base (such as ::x), representing a shorthand where the field is set immediately, and the type is deduced to be that of the field. Essentially the following two declarations are identical:
struct Foo(data I32)
  def :new(::data)
  end
  def :new(data I32)
    ::data = data
  end
end
Definition at line 751 of file ast.hpp.
Constructor & Destructor Documentation
CtorDecl()
yume::ast::CtorDecl::CtorDecl (span< Token > tok, vector< TypeName > args, Compound body) inline
Definition at line 757 of file ast.hpp.
Referenced by clone().
Member Function Documentation
args() [1/2]
auto yume::ast::CtorDecl::args () -> auto& inline
Definition at line 764 of file ast.hpp.
args() [2/2]
auto yume::ast::CtorDecl::args () const -> const auto& inline
Definition at line 763 of file ast.hpp.
Referenced by yume::semantic::TypeWalker::statement().
body() [1/2]
auto yume::ast::CtorDecl::body () -> auto& inline
Definition at line 766 of file ast.hpp.
body() [2/2]
auto yume::ast::CtorDecl::body () const -> const auto& inline
Definition at line 765 of file ast.hpp.
Referenced by yume::semantic::TypeWalker::statement().
clone()
auto yume::ast::CtorDecl::clone () const -> CtorDecl *override override virtual
Deep copy, except for the type and attachments.
Implements yume::ast::Decl.
Definition at line 76 of file clone.cpp.
References CtorDecl(), and yume::ast::AST::tok().
describe()
auto yume::ast::CtorDecl::describe () const -> string override virtual
A short, string representation for debugging.
Reimplemented from yume::ast::AST.
Definition at line 45 of file describe.cpp.
name()
auto yume::ast::CtorDecl::name () const -> string inline override virtual
Implements yume::ast::Decl.
Definition at line 762 of file ast.hpp.
visit()
void yume::ast::CtorDecl::visit (Visitor & visitor) const override virtual
Recursively visit this ast node and all its constituents.
See also
Visitor
Implements yume::ast::AST.
Definition at line 39 of file visit.cpp.
References yume::Visitor::visit().
The documentation for this class was generated from the following files:
src/yume/ast/ast.hpp
src/yume/ast/clone.cpp
src/yume/ast/describe.cpp
src/yume/ast/visit.cpp