Yume: yume::ty::BaseType Class Reference
yume::ty::BaseType Class Reference abstract
Represents a type in the type system. NOTE: that this isn't the class to use for type introspection, for that, Type should be used instead as it is fully qualified.
#include <type_base.hpp>
Public Member Functions
BaseType (const BaseType &) noexcept=delete
BaseType (BaseType &&) noexcept=delete
auto operator= (const BaseType &) noexcept -> BaseType &=delete
auto operator= (BaseType &&) noexcept -> BaseType &=delete
virtual ~BaseType ()=default
auto kind () const -> Kind
auto base_name () const -> string
virtual auto name () const -> string=0
Protected Member Functions
BaseType (Kind kind, string name)
Detailed Description
Represents a type in the type system. NOTE: that this isn't the class to use for type introspection, for that, Type should be used instead as it is fully qualified.
All kinds of types inherit from this class. Similar to AST nodes, Types cannot be copied or moved as all special member functions (aside from the destructor) are deleted.
There will always be one instance of a Type object for a specific type. This means that comparing if two types are the same type is simply a pointer equality check.
The single instance of most types is located in TypeHolder, however "qualified" types are instead stored in instances of Type. A "qualified" type is, for example, mut. These qualifiers do not stack. Getting the "mut" reference to a mutable reference should be itself.
Also, pointer-like types are also not held in TypeHolder, and are instead stored in the m_known_ptr_like array of their pointee type.
Definition at line 42 of file type_base.hpp.
Constructor & Destructor Documentation
BaseType() [1/3]
yume::ty::BaseType::BaseType (const BaseType &) delete noexcept
BaseType() [2/3]
yume::ty::BaseType::BaseType (BaseType &&) delete noexcept
~BaseType()
virtual yume::ty::BaseType::~BaseType () virtual default
BaseType() [3/3]
yume::ty::BaseType::BaseType (Kind kind, string name) inline protected
Definition at line 60 of file type_base.hpp.
Member Function Documentation
base_name()
auto yume::ty::BaseType::base_name () const -> string inline
Definition at line 56 of file type_base.hpp.
Referenced by yume::ty::Int::name(), yume::ty::Struct::name(), yume::ty::Function::name(), yume::ty::Generic::name(), and yume::ty::OpaqueSelf::name().
kind()
auto yume::ty::BaseType::kind () const -> Kind inline
Definition at line 55 of file type_base.hpp.
Referenced by yume::ty::Type::compatibility().
name()
virtual auto yume::ty::BaseType::name () const -> string pure virtual
Implemented in yume::ty::Int, yume::ty::Nil, yume::ty::Ptr, yume::ty::Struct, yume::ty::Function, yume::ty::Generic, and yume::ty::OpaqueSelf.
operator=() [1/2]
auto yume::ty::BaseType::operator= (BaseType &&) -> BaseType &=delete delete noexcept
operator=() [2/2]
auto yume::ty::BaseType::operator= (const BaseType &) -> BaseType &=delete delete noexcept
The documentation for this class was generated from the following file:
src/yume/ty/type_base.hpp