Yume: yume::ast::NumberExpr Class Reference
yume::ast::NumberExpr Class Reference final
Number literals.
#include <ast.hpp>
Public Member Functions
NumberExpr (span< Token > tok, int64_t val)
void visit (Visitor &visitor) const override
Recursively visit this ast node and all its constituents.
auto describe () const -> string override
A short, string representation for debugging.
auto val () const -> int64_t
auto clone () const -> NumberExpr *override
Deep copy, except for the type and attachments.
auto clone () const -> Expr *override=0
Deep copy, except for the type and attachments.
auto clone () const -> Stmt *override=0
Deep copy, except for the type and attachments.
Public Member Functions inherited from yume::ast::AST
AST (const AST &)=delete
AST (AST &&)=default
auto operator= (const AST &) -> AST &=delete
auto operator= (AST &&) -> AST &=delete
virtual ~AST ()=default
virtual void visit (Visitor &visitor) const =0
Recursively visit this ast node and all its constituents.
auto val_ty () const noexcept -> optional< ty::Type >
auto ensure_ty () const -> ty::Type
void val_ty (optional< ty::Type > type)
void attach_to (nonnull< AST * > other)
Make the type of this node depend on the type of other.
auto kind () const -> Kind
auto kind_name () const -> string
Human-readable string representation of the Kind of this node.
auto token_range () const -> const span< Token > &
auto location () const -> Loc
The union of the locations of the Tokens making up this node.
virtual auto describe () const -> string
A short, string representation for debugging.
virtual auto clone () const -> AST *=0
Deep copy, except for the type and attachments.
Additional Inherited Members
Protected Member Functions inherited from yume::ast::Stmt
AST (Kind kind, span< Token > tok)
AST (const AST &)=delete
AST (AST &&)=default
Protected Member Functions inherited from yume::ast::AST
void unify_val_ty ()
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
auto tok () const noexcept -> span< Token >
AST (Kind kind, span< Token > tok)
Detailed Description
Number literals.
Definition at line 441 of file ast.hpp.
Constructor & Destructor Documentation
NumberExpr()
yume::ast::NumberExpr::NumberExpr (span< Token > tok, int64_t val) inline explicit
Definition at line 445 of file ast.hpp.
Referenced by clone().
Member Function Documentation
clone()
auto yume::ast::NumberExpr::clone () const -> NumberExpr *override override virtual
Deep copy, except for the type and attachments.
Implements yume::ast::Expr.
Definition at line 61 of file clone.cpp.
References NumberExpr(), and yume::ast::AST::tok().
describe()
auto yume::ast::NumberExpr::describe () const -> string override virtual
A short, string representation for debugging.
Reimplemented from yume::ast::AST.
Definition at line 47 of file describe.cpp.
Referenced by visit().
val()
auto yume::ast::NumberExpr::val () const -> int64_t inline
Definition at line 449 of file ast.hpp.
Referenced by yume::semantic::TypeWalker::expression().
visit()
void yume::ast::NumberExpr::visit (Visitor & visitor) const override virtual
Recursively visit this ast node and all its constituents.
See also
Visitor
Implements yume::ast::AST.
Definition at line 14 of file visit.cpp.
References describe(), and yume::Visitor::visit().
The documentation for this class was generated from the following files:
src/yume/ast/ast.hpp
src/yume/ast/clone.cpp
src/yume/ast/describe.cpp
src/yume/ast/visit.cpp