Yume: yume::diagnostic::DotVisitor Class Reference
yume::diagnostic::DotVisitor Class Reference
#include <dot_visitor.hpp>
Public Member Functions
DotVisitor (llvm::raw_ostream &stream_)
~DotVisitor () override
DotVisitor (const DotVisitor &)=delete
DotVisitor (DotVisitor &&)=delete
auto operator= (const DotVisitor &) -> DotVisitor &=delete
auto operator= (DotVisitor &&) -> DotVisitor &=delete
auto visit (ast::AST &expr, const char *label) -> DotVisitor &override
auto visit (std::nullptr_t null, const char *label) -> DotVisitor &override
auto visit (const string &str, const char *label) -> DotVisitor &override
Public Member Functions inherited from yume::Visitor
Visitor ()=default
virtual ~Visitor ()=default
Visitor (Visitor &)=delete
Visitor (Visitor &&)=default
auto operator= (Visitor &) -> Visitor &=delete
auto operator= (Visitor &&) -> Visitor &=default
virtual auto visit (ast::AST &, const char *) -> Visitor &=0
virtual auto visit (std::nullptr_t, const char *) -> Visitor &=0
virtual auto visit (const string &, const char *) -> Visitor &=0
virtual auto visit (ast::AST &expr) -> Visitor &
virtual auto visit (std::nullptr_t) -> Visitor &
virtual auto visit (const string &str) -> Visitor &
template<typename T >
auto visit (vector< T > &vector, const char *label=nullptr) -> Visitor &
template<typename T >
auto visit (unique_ptr< T > &ptr, const char *label=nullptr) -> Visitor &
template<typename T >
auto visit (optional< T > &opt, const char *label=nullptr) -> Visitor &
template<typename T >
auto visit (std::pair< T, const char * > &pair) -> Visitor &
void visit ()
Detailed Description
Definition at line 18 of file dot_visitor.hpp.
Constructor & Destructor Documentation
DotVisitor() [1/3]
yume::diagnostic::DotVisitor::DotVisitor (llvm::raw_ostream & stream_) inline explicit
Definition at line 54 of file dot_visitor.hpp.
~DotVisitor()
yume::diagnostic::DotVisitor::~DotVisitor () inline override
Definition at line 57 of file dot_visitor.hpp.
DotVisitor() [2/3]
yume::diagnostic::DotVisitor::DotVisitor (const DotVisitor &) delete
DotVisitor() [3/3]
yume::diagnostic::DotVisitor::DotVisitor (DotVisitor &&) delete
Member Function Documentation
operator=() [1/2]
auto yume::diagnostic::DotVisitor::operator= (const DotVisitor &) -> DotVisitor &=delete delete
operator=() [2/2]
auto yume::diagnostic::DotVisitor::operator= (DotVisitor &&) -> DotVisitor &=delete delete
visit() [1/3]
auto yume::diagnostic::DotVisitor::visit (ast::AST & expr, const char * label) -> DotVisitor& override virtual
Implements yume::Visitor.
Definition at line 78 of file dot_visitor.cpp.
References yume::diagnostic::xml_escape().
Referenced by main().
visit() [2/3]
auto yume::diagnostic::DotVisitor::visit (const string & str, const char * label) -> DotVisitor& override virtual
Implements yume::Visitor.
Definition at line 101 of file dot_visitor.cpp.
References yume::diagnostic::xml_escape().
visit() [3/3]
auto yume::diagnostic::DotVisitor::visit (std::nullptr_t null, const char * label) -> DotVisitor& override virtual
Implements yume::Visitor.
Definition at line 110 of file dot_visitor.cpp.
The documentation for this class was generated from the following files:
src/diagnostic/dot_visitor.hpp
src/diagnostic/dot_visitor.cpp