Yume: yume::Visitor Class Reference
yume::Visitor Class Reference abstract
#include <visitor.hpp>
Public Member Functions
Visitor ()=default
virtual ~Visitor ()=default
Visitor (Visitor &)=delete
Visitor (Visitor &&)=default
auto operator= (Visitor &) -> Visitor &=delete
auto operator= (Visitor &&) -> Visitor &=default
virtual auto visit (const ast::AST &, const char *) -> Visitor &=0
virtual auto visit (std::nullptr_t, const char *) -> Visitor &=0
virtual auto visit (const string &, const char *) -> Visitor &=0
virtual auto visit (const ast::AST &expr) -> Visitor &final
virtual auto visit (std::nullptr_t) -> Visitor &final
virtual auto visit (const string &str) -> Visitor &final
template<typename T >
auto visit (const ast::OptionalAnyBase< T > &any_base, const char *label=nullptr) -> Visitor &
template<typename T >
auto visit (const ast::AnyBase< T > &any_base, const char *label=nullptr) -> Visitor &
template<std::ranges::range Range>
requires (!std::convertible_to<Range, const char*>)
auto visit (const Range &iter, const char *label=nullptr) -> Visitor &
template<typename T >
auto visit (const optional< T > &opt, const char *label=nullptr) -> Visitor &
template<typename T , typename U >
auto visit (const std::variant< T, U > &var, const char *label=nullptr) -> Visitor &
template<typename T >
auto visit (std::pair< T, const char * > &pair) -> Visitor &
void visit ()
Detailed Description
Definition at line 14 of file visitor.hpp.
Constructor & Destructor Documentation
Visitor() [1/3]
yume::Visitor::Visitor () default
~Visitor()
virtual yume::Visitor::~Visitor () virtual default
Visitor() [2/3]
yume::Visitor::Visitor (Visitor &) delete
Visitor() [3/3]
yume::Visitor::Visitor (Visitor &&) default
Member Function Documentation
operator=() [1/2]
auto yume::Visitor::operator= (Visitor &&) -> Visitor &=default default
operator=() [2/2]
auto yume::Visitor::operator= (Visitor &) -> Visitor &=delete delete
visit() [1/13]
void yume::Visitor::visit () inline
Definition at line 72 of file visitor.hpp.
Referenced by visit().
visit() [2/13]
template<typename T > auto yume::Visitor::visit (const ast::AnyBase< T > & any_base, const char * label = nullptr) -> Visitor& inline
Definition at line 41 of file visitor.hpp.
References visit(), and yume::yume_assert().
visit() [3/13]
virtual auto yume::Visitor::visit (const ast::AST & , const char *) -> Visitor & pure virtual
Implemented in yume::diagnostic::DotVisitor, yume::diagnostic::HashVisitor, and yume::diagnostic::PrintVisitor.
Referenced by visit(), yume::ast::SimpleType::visit(), yume::ast::QualType::visit(), yume::ast::TemplatedType::visit(), yume::ast::ProxyType::visit(), yume::ast::FunctionType::visit(), yume::ast::TypeName::visit(), yume::ast::NumberExpr::visit(), yume::ast::CharExpr::visit(), yume::ast::BoolExpr::visit(), yume::ast::StringExpr::visit(), yume::ast::VarExpr::visit(), yume::ast::ConstExpr::visit(), yume::ast::CallExpr::visit(), yume::ast::CtorExpr::visit(), yume::ast::DtorExpr::visit(), yume::ast::SliceExpr::visit(), yume::ast::DirectCallExpr::visit(), yume::ast::AssignExpr::visit(), yume::ast::FieldAccessExpr::visit(), yume::ast::ImplicitCastExpr::visit(), yume::ast::Compound::visit(), yume::ast::LambdaExpr::visit(), yume::ast::FnDecl::visit(), yume::ast::CtorDecl::visit(), yume::ast::StructDecl::visit(), yume::ast::VarDecl::visit(), yume::ast::ConstDecl::visit(), yume::ast::WhileStmt::visit(), yume::ast::IfClause::visit(), yume::ast::IfStmt::visit(), yume::ast::ReturnStmt::visit(), and yume::ast::Program::visit().
visit() [4/13]
virtual auto yume::Visitor::visit (const ast::AST & expr) -> Visitor& inline final virtual
Definition at line 29 of file visitor.hpp.
References visit().
Referenced by visit().
visit() [5/13]
template<typename T > auto yume::Visitor::visit (const ast::OptionalAnyBase< T > & any_base, const char * label = nullptr) -> Visitor& inline
Definition at line 35 of file visitor.hpp.
References visit().
visit() [6/13]
template<typename T > auto yume::Visitor::visit (const optional< T > & opt, const char * label = nullptr) -> Visitor& inline
Definition at line 56 of file visitor.hpp.
References visit().
visit() [7/13]
template<std::ranges::range Range> requires (!std::convertible_to<Range, const char*>) auto yume::Visitor::visit (const Range & iter, const char * label = nullptr) -> Visitor& inline
Definition at line 48 of file visitor.hpp.
References visit().
visit() [8/13]
template<typename T , typename U > auto yume::Visitor::visit (const std::variant< T, U > & var, const char * label = nullptr) -> Visitor& inline
Definition at line 62 of file visitor.hpp.
References visit().
visit() [9/13]
virtual auto yume::Visitor::visit (const string & , const char *) -> Visitor & pure virtual
Implemented in yume::diagnostic::DotVisitor, yume::diagnostic::HashVisitor, and yume::diagnostic::PrintVisitor.
visit() [10/13]
virtual auto yume::Visitor::visit (const string & str) -> Visitor& inline final virtual
Definition at line 33 of file visitor.hpp.
References visit().
Referenced by visit().
visit() [11/13]
virtual auto yume::Visitor::visit (std::nullptr_t) -> Visitor& inline final virtual
Definition at line 31 of file visitor.hpp.
References visit().
Referenced by visit().
visit() [12/13]
virtual auto yume::Visitor::visit (std::nullptr_t , const char *) -> Visitor & pure virtual
Implemented in yume::diagnostic::DotVisitor, yume::diagnostic::HashVisitor, and yume::diagnostic::PrintVisitor.
visit() [13/13]
template<typename T > auto yume::Visitor::visit (std::pair< T, const char * > & pair) -> Visitor& inline
Definition at line 68 of file visitor.hpp.
References visit().
The documentation for this class was generated from the following file:
src/yume/diagnostic/visitor/visitor.hpp