Yume: yume::ty::Ptr Class Reference
yume::ty::Ptr Class Reference
A "qualified" type, with a stackable qualifier, i.e. ptr.
#include <type.hpp>
Public Member Functions
Ptr (string name, Type base, Qualifier qual)
auto pointee () const -> Type
auto qualifier () const -> Qualifier
auto has_qualifier (Qualifier qual) const -> bool
auto name () const -> string override
Public Member Functions inherited from yume::ty::BaseType
BaseType (const BaseType &) noexcept=delete
BaseType (BaseType &&) noexcept=delete
auto operator= (const BaseType &) noexcept -> BaseType &=delete
auto operator= (BaseType &&) noexcept -> BaseType &=delete
virtual ~BaseType ()=default
auto kind () const -> Kind
auto base_name () const -> string
virtual auto name () const -> string=0
Additional Inherited Members
Protected Member Functions inherited from yume::ty::BaseType
BaseType (Kind kind, string name)
Detailed Description
A "qualified" type, with a stackable qualifier, i.e. ptr.
Definition at line 45 of file type.hpp.
Constructor & Destructor Documentation
Ptr()
yume::ty::Ptr::Ptr (string name, Type base, Qualifier qual) inline
Definition at line 53 of file type.hpp.
Member Function Documentation
has_qualifier()
auto yume::ty::Ptr::has_qualifier (Qualifier qual) const -> bool inline
Definition at line 56 of file type.hpp.
name()
auto yume::ty::Ptr::name () const -> string override virtual
Implements yume::ty::BaseType.
Definition at line 262 of file type.cpp.
References yume::ty::Type::name(), and yume::ty::qual_suffix().
pointee()
auto yume::ty::Ptr::pointee () const -> Type inline
Definition at line 54 of file type.hpp.
qualifier()
auto yume::ty::Ptr::qualifier () const -> Qualifier inline
Definition at line 55 of file type.hpp.
Referenced by yume::ty::visit_subs().
The documentation for this class was generated from the following files:
src/yume/ty/type.hpp
src/yume/ty/type.cpp