Yume: yume::ScopeContainer< T > Class Template Reference
yume::ScopeContainer< T > Class Template Reference
#include <scope_container.hpp>
Public Member Functions
auto all_scopes () const noexcept -> const auto &
auto last_scope () const noexcept -> const auto &
auto last_scope () noexcept -> auto &
auto push_scope_guarded () noexcept -> ScopeContainerGuard< T >
void push_scope () noexcept
void pop_scope () noexcept
auto add (std::string_view key, T object) noexcept
auto add_to_front (std::string_view key, T object) noexcept
auto find (std::string_view key) const noexcept -> nullable< const T * >
auto find (std::string_view key) noexcept -> nullable< T * >
void clear () noexcept
auto size () noexcept -> size_t
Detailed Description
template<typename T>
class yume::ScopeContainer< T >
Definition at line 13 of file scope_container.hpp.
Member Function Documentation
add()
template<typename T > auto yume::ScopeContainer< T >::add (std::string_view key, T object) inline noexcept
Definition at line 24 of file scope_container.hpp.
Referenced by yume::semantic::TypeWalker::statement().
add_to_front()
template<typename T > auto yume::ScopeContainer< T >::add_to_front (std::string_view key, T object) inline noexcept
Definition at line 25 of file scope_container.hpp.
Referenced by yume::semantic::TypeWalker::expression().
all_scopes()
template<typename T > auto yume::ScopeContainer< T >::all_scopes () const -> const auto& inline noexcept
Definition at line 17 of file scope_container.hpp.
clear()
template<typename T > void yume::ScopeContainer< T >::clear () inline noexcept
Definition at line 38 of file scope_container.hpp.
Referenced by yume::semantic::TypeWalker::expression(), and yume::semantic::TypeWalker::statement().
find() [1/2]
template<typename T > auto yume::ScopeContainer< T >::find (std::string_view key) const -> nullable<const T*> inline noexcept
Definition at line 26 of file scope_container.hpp.
Referenced by yume::semantic::TypeWalker::expression(), and yume::semantic::TypeWalker::statement().
find() [2/2]
template<typename T > auto yume::ScopeContainer< T >::find (std::string_view key) -> nullable<T*> inline noexcept
Definition at line 32 of file scope_container.hpp.
last_scope() [1/2]
template<typename T > auto yume::ScopeContainer< T >::last_scope () const -> const auto& inline noexcept
Definition at line 18 of file scope_container.hpp.
last_scope() [2/2]
template<typename T > auto yume::ScopeContainer< T >::last_scope () -> auto& inline noexcept
Definition at line 19 of file scope_container.hpp.
pop_scope()
template<typename T > void yume::ScopeContainer< T >::pop_scope () inline noexcept
Definition at line 22 of file scope_container.hpp.
Referenced by yume::ScopeContainerGuard< T >::~ScopeContainerGuard().
push_scope()
template<typename T > void yume::ScopeContainer< T >::push_scope () inline noexcept
Definition at line 21 of file scope_container.hpp.
push_scope_guarded()
template<typename T > auto yume::ScopeContainer< T >::push_scope_guarded noexcept
Definition at line 59 of file scope_container.hpp.
Referenced by yume::semantic::TypeWalker::expression(), and yume::semantic::TypeWalker::statement().
size()
template<typename T > auto yume::ScopeContainer< T >::size () -> size_t inline noexcept
Definition at line 39 of file scope_container.hpp.
Referenced by yume::semantic::TypeWalker::statement(), and yume::ScopeContainerGuard< T >::~ScopeContainerGuard().
The documentation for this class was generated from the following file:
src/yume/compiler/scope_container.hpp