Yume: yume::ScopeContainerGuard< T > Class Template Reference
yume::ScopeContainerGuard< T > Class Template Reference
#include <scope_container.hpp>
Public Member Functions
ScopeContainerGuard (ScopeContainer< T > &container, size_t prev_size)
~ScopeContainerGuard ()
ScopeContainerGuard (const ScopeContainerGuard< T > &)=delete
ScopeContainerGuard (ScopeContainerGuard< T > &&)=delete
auto operator= (const ScopeContainerGuard< T > &)=delete
auto operator= (ScopeContainerGuard< T > &&)=delete
Detailed Description
template<typename T>
class yume::ScopeContainerGuard< T >
Definition at line 43 of file scope_container.hpp.
Constructor & Destructor Documentation
ScopeContainerGuard() [1/3]
template<typename T > yume::ScopeContainerGuard< T >::ScopeContainerGuard (ScopeContainer< T > & container, size_t prev_size) inline
Definition at line 48 of file scope_container.hpp.
~ScopeContainerGuard()
template<typename T > yume::ScopeContainerGuard< T >::~ScopeContainerGuard () inline
Definition at line 50 of file scope_container.hpp.
References yume::ScopeContainer< T >::pop_scope(), yume::ScopeContainer< T >::size(), and yume::yume_assert().
ScopeContainerGuard() [2/3]
template<typename T > yume::ScopeContainerGuard< T >::ScopeContainerGuard (const ScopeContainerGuard< T > &) delete
ScopeContainerGuard() [3/3]
template<typename T > yume::ScopeContainerGuard< T >::ScopeContainerGuard (ScopeContainerGuard< T > &&) delete
Member Function Documentation
operator=() [1/2]
template<typename T > auto yume::ScopeContainerGuard< T >::operator= (const ScopeContainerGuard< T > &) delete
operator=() [2/2]
template<typename T > auto yume::ScopeContainerGuard< T >::operator= (ScopeContainerGuard< T > &&) delete
The documentation for this class was generated from the following file:
src/yume/compiler/scope_container.hpp