Yume: yume::ast::TypeName Class Reference
yume::ast::TypeName Class Reference
A pair of a Type and an identifier, i.e. a parameter name.
#include <ast.hpp>
Public Member Functions
TypeName (span< Token > tok, unique_ptr< Type > type, string name)
void visit (Visitor &visitor) const override
auto describe () const -> string override
A short, string representation for debugging.
auto type () const -> auto &
auto name () const -> string
template<size_t I>
auto get () &-> auto &
template<size_t I>
auto get () const &-> auto const &
template<size_t I>
auto get () &&-> auto &&
auto clone () const -> TypeName *override
Deep copy, except for the type and attachments.
Public Member Functions inherited from yume::ast::AST
AST (const AST &)=delete
AST (AST &&)=default
auto operator= (const AST &) -> AST &=delete
auto operator= (AST &&) -> AST &=delete
virtual ~AST ()=default
virtual void visit (Visitor &visitor) const =0
auto val_ty () const noexcept -> const ty::Type *
auto get_val_ty () const noexcept -> const ty::Type *
void val_ty (const ty::Type *type) const
void attach_to (const AST *other) const
Make the type of this node depend on the type of other.
auto kind () const -> Kind
auto kind_name () const -> string
Human-readable string representation of the Kind of this node.
auto token_range () const -> const span< Token > &
auto location () const -> Loc
The union of the locations of the Tokens making up this node.
virtual auto describe () const -> string
A short, string representation for debugging.
virtual auto clone () const -> AST *=0
Deep copy, except for the type and attachments.
Additional Inherited Members
Protected Member Functions inherited from yume::ast::AST
void unify_val_ty () const
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
auto tok () const noexcept -> span< Token >
AST (Kind kind, span< Token > tok)
Detailed Description
A pair of a Type and an identifier, i.e. a parameter name.
Definition at line 326 of file ast.hpp.
Constructor & Destructor Documentation
TypeName()
yume::ast::TypeName::TypeName (span< Token > tok, unique_ptr< Type > type, string name) inline
Definition at line 331 of file ast.hpp.
Referenced by clone().
Member Function Documentation
clone()
auto yume::ast::TypeName::clone () const -> TypeName *override override virtual
Deep copy, except for the type and attachments.
Implements yume::ast::AST.
Definition at line 69 of file clone.cpp.
References yume::ast::AST::tok(), and TypeName().
describe()
auto yume::ast::TypeName::describe () const -> string override virtual
A short, string representation for debugging.
Reimplemented from yume::ast::AST.
Definition at line 35 of file describe.cpp.
get() [1/3]
template<size_t I> auto yume::ast::TypeName::get () && -> auto&& inline
Definition at line 355 of file ast.hpp.
get() [2/3]
template<size_t I> auto yume::ast::TypeName::get () & -> auto& inline
Definition at line 339 of file ast.hpp.
get() [3/3]
template<size_t I> auto yume::ast::TypeName::get () const & -> auto const& inline
Definition at line 347 of file ast.hpp.
name()
auto yume::ast::TypeName::name () const -> string inline
Definition at line 337 of file ast.hpp.
type()
auto yume::ast::TypeName::type () const -> auto& inline
Definition at line 336 of file ast.hpp.
Referenced by yume::semantic::TypeWalker::expression().
visit()
void yume::ast::TypeName::visit (Visitor & visitor) const override virtual
Implements yume::ast::AST.
Definition at line 38 of file visit.cpp.
References yume::Visitor::visit().
The documentation for this class was generated from the following files:
src/yume/ast/ast.hpp
src/yume/ast/clone.cpp
src/yume/ast/describe.cpp
src/yume/ast/visit.cpp