Yume: yume::ast::AssignExpr Class Reference
yume::ast::AssignExpr Class Reference
An assignment (=).
#include <ast.hpp>
Public Member Functions
AssignExpr (span< Token > tok, unique_ptr< Expr > target, unique_ptr< Expr > value)
void visit (Visitor &visitor) override
auto target () const -> auto &
auto value () const -> auto &
auto clone () const -> AssignExpr *override
Deep copy, except for the type and attachments.
auto clone () const -> Expr *override=0
Deep copy, except for the type and attachments.
auto clone () const -> Stmt *override=0
Deep copy, except for the type and attachments.
Public Member Functions inherited from yume::ast::AST
AST (const AST &)=delete
AST (AST &&)=default
auto operator= (const AST &) -> AST &=delete
auto operator= (AST &&) -> AST &=delete
virtual ~AST ()=default
virtual void visit (Visitor &visitor)=0
auto val_ty () const noexcept -> const ty::Type *
void val_ty (const ty::Type *type) const
void attach_to (const AST *other) const
Make the type of this node depend on the type of other.
auto kind () const -> Kind
auto kind_name () const -> string
Human-readable string representation of the Kind of this node.
auto token_range () const -> const span< Token > &
auto location () const -> Loc
The union of the locations of the Tokens making up this node.
virtual auto describe () const -> string
A short, string representation for debugging.
virtual auto clone () const -> AST *=0
Deep copy, except for the type and attachments.
Additional Inherited Members
Protected Member Functions inherited from yume::ast::Stmt
AST (Kind kind, span< Token > tok)
AST (const AST &)=delete
AST (AST &&)=default
Protected Member Functions inherited from yume::ast::AST
void unify_val_ty () const
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
auto tok () const noexcept -> span< Token >
AST (Kind kind, span< Token > tok)
Detailed Description
An assignment (=).
Assignment has a specific target (the left-hand side), and the value (the right-hand-side). The target may be multiple things, such as a variable VarExpr or field FieldAccessExpr. Note that some things such as indexed assignment []= become a CallExpr instead.
Definition at line 488 of file ast.hpp.
Constructor & Destructor Documentation
AssignExpr()
yume::ast::AssignExpr::AssignExpr (span< Token > tok, unique_ptr< Expr > target, unique_ptr< Expr > value) inline
Definition at line 493 of file ast.hpp.
Referenced by clone().
Member Function Documentation
clone()
auto yume::ast::AssignExpr::clone () const -> AssignExpr *override override virtual
Deep copy, except for the type and attachments.
Implements yume::ast::Expr.
Definition at line 68 of file clone.cpp.
References AssignExpr(), and yume::ast::AST::tok().
target()
auto yume::ast::AssignExpr::target () const -> auto& inline
Definition at line 497 of file ast.hpp.
Referenced by yume::TypeWalker::expression().
value()
auto yume::ast::AssignExpr::value () const -> auto& inline
Definition at line 498 of file ast.hpp.
Referenced by yume::TypeWalker::expression().
visit()
void yume::ast::AssignExpr::visit (Visitor & visitor) override virtual
Implements yume::ast::AST.
Definition at line 44 of file visit.cpp.
References yume::Visitor::visit().
The documentation for this class was generated from the following files:
src/ast/ast.hpp
src/ast/clone.cpp
src/ast/visit.cpp