Yume: yume::ast::QualType Class Reference
yume::ast::QualType Class Reference
A type with a Qualifier like mut or [] following.
#include <ast.hpp>
Public Member Functions
QualType (span< Token > tok, AnyType base, Qualifier qualifier)
void visit (Visitor &visitor) const override
Recursively visit this ast node and all its constituents.
auto describe () const -> string override
A short, string representation for debugging.
constexpr auto qualifier () const -> Qualifier
auto base () const -> const auto &
auto base () -> auto &
auto clone () const -> QualType *override
Deep copy, except for the type and attachments.
auto clone () const -> Type *override=0
Deep copy, except for the type and attachments.
Public Member Functions inherited from yume::ast::AST
AST (const AST &)=delete
AST (AST &&)=default
auto operator= (const AST &) -> AST &=delete
auto operator= (AST &&) -> AST &=delete
virtual ~AST ()=default
virtual void visit (Visitor &visitor) const =0
Recursively visit this ast node and all its constituents.
auto val_ty () const noexcept -> const ty::Type *
auto get_val_ty () const noexcept -> const ty::Type *
void val_ty (const ty::Type *type) const
void attach_to (const AST *other) const
Make the type of this node depend on the type of other.
auto kind () const -> Kind
auto kind_name () const -> string
Human-readable string representation of the Kind of this node.
auto token_range () const -> const span< Token > &
auto location () const -> Loc
The union of the locations of the Tokens making up this node.
virtual auto describe () const -> string
A short, string representation for debugging.
virtual auto clone () const -> AST *=0
Deep copy, except for the type and attachments.
Additional Inherited Members
Protected Member Functions inherited from yume::ast::Type
AST (Kind kind, span< Token > tok)
AST (const AST &)=delete
AST (AST &&)=default
Protected Member Functions inherited from yume::ast::AST
void unify_val_ty () const
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
auto tok () const noexcept -> span< Token >
AST (Kind kind, span< Token > tok)
Detailed Description
A type with a Qualifier like mut or [] following.
Definition at line 308 of file ast.hpp.
Constructor & Destructor Documentation
QualType()
yume::ast::QualType::QualType (span< Token > tok, AnyType base, Qualifier qualifier) inline
Definition at line 313 of file ast.hpp.
Referenced by clone().
Member Function Documentation
base() [1/2]
auto yume::ast::QualType::base () -> auto& inline
Definition at line 320 of file ast.hpp.
base() [2/2]
auto yume::ast::QualType::base () const -> const auto& inline
Definition at line 319 of file ast.hpp.
clone()
auto yume::ast::QualType::clone () const -> QualType *override override virtual
Deep copy, except for the type and attachments.
Implements yume::ast::Type.
Definition at line 78 of file clone.cpp.
References QualType(), and yume::ast::AST::tok().
describe()
auto yume::ast::QualType::describe () const -> string override virtual
A short, string representation for debugging.
Reimplemented from yume::ast::AST.
Definition at line 12 of file describe.cpp.
References yume::Mut, yume::Ptr, and yume::Slice.
Referenced by visit().
qualifier()
constexpr auto yume::ast::QualType::qualifier () const -> Qualifier inline constexpr
Definition at line 318 of file ast.hpp.
visit()
void yume::ast::QualType::visit (Visitor & visitor) const override virtual
Recursively visit this ast node and all its constituents.
See also
Visitor
Implements yume::ast::AST.
Definition at line 36 of file visit.cpp.
References describe(), and yume::Visitor::visit().
The documentation for this class was generated from the following files:
src/yume/ast/ast.hpp
src/yume/ast/clone.cpp
src/yume/ast/describe.cpp
src/yume/ast/visit.cpp