Yume: yume::ast::FieldAccessExpr Class Reference
yume::ast::FieldAccessExpr Class Reference
Direct access of a field of a struct (::).
#include <ast.hpp>
Public Member Functions
FieldAccessExpr (span< Token > tok, unique_ptr< Expr > base, string field)
void visit (Visitor &visitor) const override
auto base () const -> const auto &
auto base () -> auto &
auto field () const -> string
void offset (int offset) const
auto offset () const -> int
auto clone () const -> FieldAccessExpr *override
Deep copy, except for the type and attachments.
auto clone () const -> Expr *override=0
Deep copy, except for the type and attachments.
auto clone () const -> Stmt *override=0
Deep copy, except for the type and attachments.
Public Member Functions inherited from yume::ast::AST
AST (const AST &)=delete
AST (AST &&)=default
auto operator= (const AST &) -> AST &=delete
auto operator= (AST &&) -> AST &=delete
virtual ~AST ()=default
virtual void visit (Visitor &visitor) const =0
auto val_ty () const noexcept -> const ty::Type *
auto get_val_ty () const noexcept -> const ty::Type *
void val_ty (const ty::Type *type) const
void attach_to (const AST *other) const
Make the type of this node depend on the type of other.
auto kind () const -> Kind
auto kind_name () const -> string
Human-readable string representation of the Kind of this node.
auto token_range () const -> const span< Token > &
auto location () const -> Loc
The union of the locations of the Tokens making up this node.
virtual auto describe () const -> string
A short, string representation for debugging.
virtual auto clone () const -> AST *=0
Deep copy, except for the type and attachments.
Additional Inherited Members
Protected Member Functions inherited from yume::ast::Stmt
AST (Kind kind, span< Token > tok)
AST (const AST &)=delete
AST (AST &&)=default
Protected Member Functions inherited from yume::ast::AST
void unify_val_ty () const
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
auto tok () const noexcept -> span< Token >
AST (Kind kind, span< Token > tok)
Detailed Description
Direct access of a field of a struct (::).
Definition at line 502 of file ast.hpp.
Constructor & Destructor Documentation
FieldAccessExpr()
yume::ast::FieldAccessExpr::FieldAccessExpr (span< Token > tok, unique_ptr< Expr > base, string field) inline
Definition at line 508 of file ast.hpp.
Referenced by clone().
Member Function Documentation
base() [1/2]
auto yume::ast::FieldAccessExpr::base () -> auto& inline
Definition at line 513 of file ast.hpp.
base() [2/2]
auto yume::ast::FieldAccessExpr::base () const -> const auto& inline
Definition at line 512 of file ast.hpp.
Referenced by yume::semantic::TypeWalker::expression().
clone()
auto yume::ast::FieldAccessExpr::clone () const -> FieldAccessExpr *override override virtual
Deep copy, except for the type and attachments.
Implements yume::ast::Expr.
Definition at line 77 of file clone.cpp.
References FieldAccessExpr(), and yume::ast::AST::tok().
field()
auto yume::ast::FieldAccessExpr::field () const -> string inline
Definition at line 514 of file ast.hpp.
Referenced by yume::semantic::TypeWalker::expression().
offset() [1/2]
auto yume::ast::FieldAccessExpr::offset () const -> int inline
Definition at line 516 of file ast.hpp.
offset() [2/2]
void yume::ast::FieldAccessExpr::offset (int offset) const inline
Definition at line 515 of file ast.hpp.
References offset().
Referenced by yume::semantic::TypeWalker::expression(), and offset().
visit()
void yume::ast::FieldAccessExpr::visit (Visitor & visitor) const override virtual
Implements yume::ast::AST.
Definition at line 46 of file visit.cpp.
References yume::Visitor::visit().
The documentation for this class was generated from the following files:
src/yume/ast/ast.hpp
src/yume/ast/clone.cpp
src/yume/ast/visit.cpp