Yume: yume::ast::FnDecl Class Reference
yume::ast::FnDecl Class Reference
A declaration of a function (def).
#include <ast.hpp>
Public Types
using extern_decl_t = { string name
using body_t = variant< Compound, string, extern_decl_t >
Public Member Functions
FnDecl (span< Token > tok, string name, vector< TypeName > args, vector< string > type_args, OptionalType ret, body_t body, std::set< string > annotations)
void visit (Visitor &visitor) const override
Recursively visit this ast node and all its constituents.
auto describe () const -> string override
A short, string representation for debugging.
auto name () const -> string override
auto args () const -> const auto &
auto args () -> auto &
auto type_args () const
auto ret () const -> const auto &
auto ret () -> auto &
auto body () const -> const auto &
auto body () -> auto &
auto varargs () const -> bool
auto primitive () const -> bool
auto extern_decl () const -> bool
auto extern_linkage () const -> bool
void make_extern_linkage (bool value=true)
auto clone () const -> FnDecl *override
Deep copy, except for the type and attachments.
auto clone () const -> Decl *override=0
Deep copy, except for the type and attachments.
virtual auto name () const -> string=0
auto clone () const -> Stmt *override=0
Deep copy, except for the type and attachments.
Public Member Functions inherited from yume::ast::AST
AST (const AST &)=delete
AST (AST &&)=default
auto operator= (const AST &) -> AST &=delete
auto operator= (AST &&) -> AST &=delete
virtual ~AST ()=default
virtual void visit (Visitor &visitor) const =0
Recursively visit this ast node and all its constituents.
auto val_ty () const noexcept -> optional< ty::Type >
auto ensure_ty () const -> ty::Type
void val_ty (optional< ty::Type > type)
void attach_to (nonnull< AST * > other)
Make the type of this node depend on the type of other.
auto kind () const -> Kind
auto kind_name () const -> string
Human-readable string representation of the Kind of this node.
auto token_range () const -> const span< Token > &
auto location () const -> Loc
The union of the locations of the Tokens making up this node.
virtual auto describe () const -> string
A short, string representation for debugging.
virtual auto clone () const -> AST *=0
Deep copy, except for the type and attachments.
Public Attributes
bool varargs
Static Public Attributes
static constexpr auto ANN_EXTERN = "extern"
Additional Inherited Members
Protected Member Functions inherited from yume::ast::Stmt
AST (Kind kind, span< Token > tok)
AST (const AST &)=delete
AST (AST &&)=default
Protected Member Functions inherited from yume::ast::AST
void unify_val_ty ()
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
auto tok () const noexcept -> span< Token >
AST (Kind kind, span< Token > tok)
Detailed Description
A declaration of a function (def).
Definition at line 682 of file ast.hpp.
Member Typedef Documentation
body_t
using yume::ast::FnDecl::body_t = variant<Compound, string, extern_decl_t>
Definition at line 689 of file ast.hpp.
extern_decl_t
using yume::ast::FnDecl::extern_decl_t = { string name
Definition at line 684 of file ast.hpp.
Constructor & Destructor Documentation
FnDecl()
yume::ast::FnDecl::FnDecl (span< Token > tok, string name, vector< TypeName > args, vector< string > type_args, OptionalType ret, body_t body, std::set< string > annotations) inline
Definition at line 705 of file ast.hpp.
Referenced by clone().
Member Function Documentation
args() [1/2]
auto yume::ast::FnDecl::args () -> auto& inline
Definition at line 714 of file ast.hpp.
args() [2/2]
auto yume::ast::FnDecl::args () const -> const auto& inline
Definition at line 713 of file ast.hpp.
Referenced by yume::semantic::TypeWalker::statement().
body() [1/2]
auto yume::ast::FnDecl::body () -> auto& inline
Definition at line 719 of file ast.hpp.
body() [2/2]
auto yume::ast::FnDecl::body () const -> const auto& inline
Definition at line 718 of file ast.hpp.
Referenced by yume::Fn::compound_body(), yume::Fn::fn_body(), and yume::semantic::TypeWalker::statement().
clone()
auto yume::ast::FnDecl::clone () const -> FnDecl *override override virtual
Deep copy, except for the type and attachments.
Implements yume::ast::Decl.
Definition at line 69 of file clone.cpp.
References FnDecl(), and yume::ast::AST::tok().
describe()
auto yume::ast::FnDecl::describe () const -> string override virtual
A short, string representation for debugging.
Reimplemented from yume::ast::AST.
Definition at line 44 of file describe.cpp.
extern_decl()
auto yume::ast::FnDecl::extern_decl () const -> bool inline
Definition at line 722 of file ast.hpp.
extern_linkage()
auto yume::ast::FnDecl::extern_linkage () const -> bool inline
Definition at line 723 of file ast.hpp.
make_extern_linkage()
void yume::ast::FnDecl::make_extern_linkage (bool value = true) inline
Definition at line 724 of file ast.hpp.
name()
auto yume::ast::FnDecl::name () const -> string inline override virtual
Implements yume::ast::Decl.
Definition at line 712 of file ast.hpp.
primitive()
auto yume::ast::FnDecl::primitive () const -> bool inline
Definition at line 721 of file ast.hpp.
ret() [1/2]
auto yume::ast::FnDecl::ret () -> auto& inline
Definition at line 717 of file ast.hpp.
ret() [2/2]
auto yume::ast::FnDecl::ret () const -> const auto& inline
Definition at line 716 of file ast.hpp.
Referenced by yume::semantic::TypeWalker::statement().
type_args()
auto yume::ast::FnDecl::type_args () const inline
Definition at line 715 of file ast.hpp.
varargs()
auto yume::ast::FnDecl::varargs () const -> bool inline
Definition at line 720 of file ast.hpp.
visit()
void yume::ast::FnDecl::visit (Visitor & visitor) const override virtual
Recursively visit this ast node and all its constituents.
See also
Visitor
Implements yume::ast::AST.
Definition at line 22 of file visit.cpp.
References yume::Visitor::visit().
Member Data Documentation
ANN_EXTERN
constexpr auto yume::ast::FnDecl::ANN_EXTERN = "extern" static constexpr
Definition at line 691 of file ast.hpp.
varargs
bool yume::ast::FnDecl::varargs
Definition at line 686 of file ast.hpp.
The documentation for this class was generated from the following files:
src/yume/ast/ast.hpp
src/yume/ast/clone.cpp
src/yume/ast/describe.cpp
src/yume/ast/visit.cpp