Yume: yume::Compiler Class Reference
yume::Compiler Class Reference
The Compiler the the primary top-level type during compilation. A single instance is created during the compilation process.
#include <compiler.hpp>
Public Member Functions
auto module () const -> const auto &
auto context () const -> const auto &
auto builder () const -> const auto &
Compiler (const optional< string > &target_triple, vector< SourceFile > source_files)
void run ()
Begin compilation!
auto declare (Fn &) -> llvm::Function *
Declare a function/constructor in bytecode, or get an existing declaration.
auto create_struct (Struct &) -> bool
void define (Fn &)
Compile the body of a function or constructor.
void define (Const &)
void body_statement (ast::Stmt &)
auto decl_statement (ast::Stmt &, optional< ty::Type > parent=std::nullopt, ast::Program *member=nullptr) -> DeclLike
auto body_expression (ast::Expr &expr) -> Val
auto direct_call_operator (ast::CallExpr &expr) -> Val
void write_object (const char *filename, bool binary)
auto llvm_type (ty::Type type, bool erase_opaque=false) -> llvm::Type *
Convert a type into its corresponding LLVM type.
auto ptr_bitsize () -> unsigned int
auto default_init (ty::Type type) -> Val
Default-constructs an object of specified type type .
void destruct (Val val, ty::Type type)
Destructs an object val of specified type type .
auto source_files () -> const auto &
template<>
void statement (ast::Compound &stat)
template<>
void statement (ast::WhileStmt &stat)
template<>
void statement (ast::IfStmt &stat)
template<>
void statement (ast::ReturnStmt &stat)
template<>
void statement (ast::VarDecl &stat)
template<>
auto expression (ast::NumberExpr &expr) -> Val
template<>
auto expression (ast::CharExpr &expr) -> Val
template<>
auto expression (ast::BoolExpr &expr) -> Val
template<>
auto expression (ast::StringExpr &expr) -> Val
template<>
auto expression (ast::VarExpr &expr) -> Val
template<>
auto expression (ast::ConstExpr &expr) -> Val
template<>
auto expression (ast::CallExpr &expr) -> Val
template<>
auto expression (ast::BinaryLogicExpr &expr) -> Val
template<>
auto expression (ast::AssignExpr &expr) -> Val
template<>
auto expression (ast::LambdaExpr &expr) -> Val
template<>
auto expression (ast::CtorExpr &expr) -> Val
template<>
auto expression (ast::SliceExpr &expr) -> Val
template<>
auto expression (ast::FieldAccessExpr &expr) -> Val
template<>
auto expression (ast::ImplicitCastExpr &expr) -> Val
template<>
auto expression (ast::TypeExpr &expr) -> Val
Public Member Functions inherited from yume::CRTPWalker< Compiler >
auto body_statement (ast::Stmt &stat, auto &&... args)
auto body_expression (ast::Expr &expr, auto &&... args)
Detailed Description
The Compiler the the primary top-level type during compilation. A single instance is created during the compilation process.
Definition at line 44 of file compiler.hpp.
Constructor & Destructor Documentation
Compiler()
yume::Compiler::Compiler (const optional< string > & target_triple, vector< SourceFile > source_files)
Definition at line 88 of file compiler.cpp.
References yume::TypeHolder::declare_size_type(), and yume::make_cdtor_fn().
Member Function Documentation
body_expression()
auto yume::Compiler::body_expression (ast::Expr & expr) -> Val
Definition at line 1578 of file compiler.cpp.
References yume::CRTPWalker< Derived >::body_expression().
Referenced by define(), and statement().
body_statement()
void yume::Compiler::body_statement (ast::Stmt & stat)
Definition at line 1572 of file compiler.cpp.
References yume::CRTPWalker< Derived >::body_statement(), and yume::ast::AST::kind_name().
Referenced by statement().
builder()
auto yume::Compiler::builder () const -> const auto& inline
Definition at line 81 of file compiler.hpp.
Referenced by yume::destruct_indirect().
context()
auto yume::Compiler::context () const -> const auto& inline
Definition at line 80 of file compiler.hpp.
create_struct()
auto yume::Compiler::create_struct (Struct & st) -> bool
Definition at line 273 of file compiler.cpp.
References yume::any_of, yume::Struct::self_ty, yume::Struct::st_ast, yume::Struct::subs, and yume::yume_assert().
decl_statement()
auto yume::Compiler::decl_statement (ast::Stmt & stmt, optional< ty::Type > parent = std::nullopt, ast::Program * member = nullptr) -> DeclLike
Definition at line 301 of file compiler.cpp.
References yume::Struct::name(), yume::Struct::self_ty, and yume::Struct::type_args.
Referenced by yume::semantic::TypeWalker::resolve_queue(), and run().
declare()
auto yume::Compiler::declare (Fn & fn) -> llvm::Function*
Declare a function/constructor in bytecode, or get an existing declaration.
Definition at line 514 of file compiler.cpp.
References yume::Fn::arg_names(), yume::Fn::ast(), yume::ty::Function::closure_memo(), yume::Fn::extern_decl(), yume::Fn::extern_linkage(), yume::ty::Function::fn_memo(), yume::Fn::fn_ty, yume::Fn::has_annotation(), yume::Fn::llvm, yume::Fn::local(), yume::mangle::mangle_name(), yume::Fn::member, yume::Fn::name(), yume::Fn::primitive(), and yume::yume_assert().
Referenced by yume::semantic::TypeWalker::resolve_queue(), and run().
default_init()
auto yume::Compiler::default_init (ty::Type type) -> Val
Default-constructs an object of specified type type .
Definition at line 488 of file compiler.cpp.
References yume::Ptr.
define() [1/2]
void yume::Compiler::define (Const & cn)
Definition at line 627 of file compiler.cpp.
References yume::Const::ast(), body_expression(), destruct(), yume::Const::llvm, and llvm_type().
define() [2/2]
void yume::Compiler::define (Fn & fn)
Compile the body of a function or constructor.
Definition at line 653 of file compiler.cpp.
References yume::Fn::abstract(), yume::Fn::ast(), yume::Fn::compound_body(), end, yume::Fn::fn_body(), yume::Fn::llvm, yume::Val::llvm, llvm_type(), yume::Fn::self_ty, yume::InScope::value, yume::vtable_entry_for(), and yume::yume_assert().
Referenced by run().
destruct()
void yume::Compiler::destruct (Val val, ty::Type type)
Destructs an object val of specified type type .
Definition at line 450 of file compiler.cpp.
References yume::ty::Type::base_cast(), destruct(), yume::ty::Type::is_mut(), yume::ty::Type::is_slice(), llvm_type(), yume::ty::Type::mut_base(), and ptr_bitsize().
Referenced by define(), destruct(), and yume::destruct_indirect().
direct_call_operator()
auto yume::Compiler::direct_call_operator (ast::CallExpr & expr) -> Val
Definition at line 1211 of file compiler.cpp.
References yume::yume_assert().
expression() [1/15]
template<> auto yume::Compiler::expression (ast::AssignExpr & expr) -> Val
Definition at line 1104 of file compiler.cpp.
References yume::destruct_indirect(), and yume::yume_assert().
expression() [2/15]
template<> auto yume::Compiler::expression (ast::BinaryLogicExpr & expr) -> Val
Definition at line 1080 of file compiler.cpp.
expression() [3/15]
template<> auto yume::Compiler::expression (ast::BoolExpr & expr) -> Val
Definition at line 877 of file compiler.cpp.
expression() [4/15]
template<> auto yume::Compiler::expression (ast::CallExpr & expr) -> Val
Definition at line 1046 of file compiler.cpp.
References yume::vals_to_llvm().
expression() [5/15]
template<> auto yume::Compiler::expression (ast::CharExpr & expr) -> Val
Definition at line 875 of file compiler.cpp.
expression() [6/15]
template<> auto yume::Compiler::expression (ast::ConstExpr & expr) -> Val
Definition at line 946 of file compiler.cpp.
expression() [7/15]
template<> auto yume::Compiler::expression (ast::CtorExpr & expr) -> Val
Definition at line 1238 of file compiler.cpp.
References yume::ty::Int::is_signed(), and yume::yume_assert().
expression() [8/15]
template<> auto yume::Compiler::expression (ast::FieldAccessExpr & expr) -> Val
Definition at line 1394 of file compiler.cpp.
References yume::yume_assert().
expression() [9/15]
template<> auto yume::Compiler::expression (ast::ImplicitCastExpr & expr) -> Val
Definition at line 1418 of file compiler.cpp.
References yume::any_of, yume::ty::Struct::decl(), yume::Fn::fn_ty, yume::ty::Struct::is_interface(), yume::ty::Int::is_signed(), yume::Val::llvm, yume::ty::Struct::name(), yume::InScope::owning, yume::Val::scope, yume::vtable_entry_for(), and yume::yume_assert().
expression() [10/15]
template<> auto yume::Compiler::expression (ast::LambdaExpr & expr) -> Val
Definition at line 1150 of file compiler.cpp.
References yume::ast::AST::ensure_ty(), yume::Val::llvm, yume::Fn::member, and yume::yume_assert().
expression() [11/15]
template<> auto yume::Compiler::expression (ast::NumberExpr & expr) -> Val
Definition at line 868 of file compiler.cpp.
expression() [12/15]
template<> auto yume::Compiler::expression (ast::SliceExpr & expr) -> Val
Definition at line 1363 of file compiler.cpp.
References yume::yume_assert().
expression() [13/15]
template<> auto yume::Compiler::expression (ast::StringExpr & expr) -> Val
Definition at line 905 of file compiler.cpp.
expression() [14/15]
template<> auto yume::Compiler::expression (ast::TypeExpr & expr) -> Val
Definition at line 1552 of file compiler.cpp.
References yume::yume_assert().
expression() [15/15]
template<> auto yume::Compiler::expression (ast::VarExpr & expr) -> Val
Definition at line 935 of file compiler.cpp.
References yume::Val::llvm, and yume::yume_assert().
llvm_type()
auto yume::Compiler::llvm_type (ty::Type type, bool erase_opaque = false) -> llvm::Type*
Convert a type into its corresponding LLVM type.
Definition at line 407 of file compiler.cpp.
References yume::build_function_type(), yume::build_struct_type(), yume::Ptr, and yume::yume_assert().
Referenced by define(), destruct(), yume::destruct_indirect(), run(), and statement().
module()
auto yume::Compiler::module () const -> const auto& inline
Definition at line 79 of file compiler.hpp.
ptr_bitsize()
auto yume::Compiler::ptr_bitsize () -> unsigned int
Definition at line 1322 of file compiler.cpp.
Referenced by yume::TypeHolder::declare_size_type(), and destruct().
run()
void yume::Compiler::run ()
Begin compilation!
Definition at line 177 of file compiler.cpp.
References yume::Struct::ast(), yume::create_vtable_for(), decl_statement(), declare(), define(), yume::Fn::extern_decl(), yume::Fn::extern_linkage(), llvm_type(), yume::Fn::make_extern_linkage(), yume::Fn::name(), and yume::yume_assert().
Referenced by compile().
source_files()
auto yume::Compiler::source_files () -> const auto& inline
Definition at line 113 of file compiler.hpp.
statement() [1/5]
template<> void yume::Compiler::statement (ast::Compound & stat)
Definition at line 563 of file compiler.cpp.
References body_statement().
statement() [2/5]
template<> void yume::Compiler::statement (ast::IfStmt & stat)
Definition at line 750 of file compiler.cpp.
References body_expression(), yume::ast::IfStmt::clauses, yume::ast::IfStmt::else_clause, and yume::Fn::llvm.
statement() [3/5]
template<> void yume::Compiler::statement (ast::ReturnStmt & stat)
Definition at line 795 of file compiler.cpp.
References body_expression(), yume::ast::ReturnStmt::expr, yume::ast::ReturnStmt::extends_lifetime, yume::ast::OptionalAnyBase< T >::has_value(), yume::Fn::llvm, yume::InScope::owning, and yume::ast::OptionalAnyBase< T >::raw_ptr().
statement() [4/5]
template<> void yume::Compiler::statement (ast::VarDecl & stat)
Definition at line 846 of file compiler.cpp.
References body_expression(), yume::ast::AST::ensure_ty(), yume::ast::VarDecl::init, llvm_type(), and yume::ast::VarDecl::name.
statement() [5/5]
template<> void yume::Compiler::statement (ast::WhileStmt & stat)
Definition at line 736 of file compiler.cpp.
References yume::ast::WhileStmt::body, body_expression(), body_statement(), yume::ast::WhileStmt::cond, and yume::Fn::llvm.
write_object()
void yume::Compiler::write_object (const char * filename, bool binary)
Definition at line 1557 of file compiler.cpp.
References yume::open_file().
The documentation for this class was generated from the following files:
src/yume/compiler/compiler.hpp
src/yume/compiler/compiler.cpp