Yume: src/main.cpp File Reference
main.cpp File Reference
#include "ast/ast.hpp"
#include "compiler/compiler.hpp"
#include "compiler/vals.hpp"
#include "diagnostic/dot_visitor.hpp"
#include "diagnostic/errors.hpp"
#include "token.hpp"
#include "util.hpp"
#include <algorithm>
#include <cstdlib>
#include <exception>
#include <fstream>
#include <iterator>
#include <llvm/ADT/StringRef.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/ErrorOr.h>
#include <llvm/Support/MemoryBuffer.h>
#include <llvm/Support/PrettyStackTrace.h>
#include <llvm/Support/Signals.h>
#include <llvm/Support/raw_ostream.h>
#include <memory>
#include <span>
#include <string>
#include <string_view>
#include <utility>
#include <vector>
Macros
#define YUME_LIB_DIR "./lib/"
Functions
auto main (int argc, const char *argv[]) -> int
Macro Definition Documentation
YUME_LIB_DIR
#define YUME_LIB_DIR "./lib/"
Definition at line 29 of file main.cpp.
Function Documentation
main()
auto main (int argc, const char * argv[]) -> int
Definition at line 32 of file main.cpp.
References yume::open_file(), yume::Compiler::run(), yume::stacktrace(), yume::stem(), yume::diagnostic::DotVisitor::visit(), and YUME_LIB_DIR.