Yume: yume::mangle Namespace Reference
yume::mangle Namespace Reference
Functions
static auto length_encode (const string &name) -> string
auto mangle_name (Fn &fn) -> string
auto mangle_name (ty::Type ast_type, DeclLike parent) -> string
Function Documentation
length_encode()
static auto yume::mangle::length_encode (const string & name) -> string static
Definition at line 5 of file mangle.cpp.
mangle_name() [1/2]
auto yume::mangle::mangle_name (Fn & fn) -> string
Definition at line 9 of file mangle.cpp.
References mangle_name().
Referenced by yume::Compiler::declare(), and mangle_name().
mangle_name() [2/2]
auto yume::mangle::mangle_name (ty::Type ast_type, DeclLike parent) -> string
Definition at line 29 of file mangle.cpp.
References mangle_name(), yume::Ptr, and yume::yume_assert().