Yume: yume Namespace Reference
yume Namespace Reference
Namespaces
namespace ast
namespace diagnostic
namespace mangle
namespace semantic
namespace ty
Classes
struct any_of_fn
struct ASTStackTrace
class Atom
Atoms represent strings in a string pool.
struct Characteristic
A criterion for classifying a stream of characters as a specific type of token Token::Type.
class Compiler
The Compiler the the primary top-level type during compilation. A single instance is created during the compilation process.
struct Const
A constant declaration in the compiler.
struct CRTPWalker
A helper template to walk the Abstract Syntax Tree (AST), utilizing the Curiously Recurring Template Pattern (CRTP).
struct DeclLike
A common base between declarations in the compiler: Fn, Struct and Const. Its value may also be absent (std::monostate).
struct Def
struct Fn
A function declaration in the compiler.
struct FnArg
struct InScope
A local variable in function scope. Used to track destructing when the scope ends.
struct Loc
Represents a location in source code, as a range starting at a line and column and ending at some other line and column of some file.
struct ParserStackTrace
class ScopeContainer
class ScopeContainerGuard
struct source_location
struct SourceFile
A source file with its associated Syntax Tree.
struct StringLiteral
struct Struct
A struct declaration in the compiler.
struct Substitution
struct Token
A categorized token in source code, created by the tokenizer. These tokens are consumed by the lexer.
class Tokenizer
Contains the state while the tokenizer is running, such as the position within the file currently being read.
struct TokenState
struct TypeHolder
struct Val
A value of a complied expression.
struct visitable_variant
class Visitor
struct VTableEntry
Concepts
concept OnlyStmt
concept visitable
Typedefs
using Def_t = visitable_variant< ast::FnDecl *, ast::CtorDecl *, ast::LambdaExpr * >
using DeclLike_t = visitable_variant< std::monostate, Fn *, Struct *, Const * >
using char_raw_fn = bool(char)
using char_pos_fn = bool(char, size_t)
using char_fn = std::function< bool(TokenState &)>
using substitution_t = std::map< string, ty::Type >
template<typename T >
using nullable = T
template<typename T >
using nonnull = T
Enumerations
enum struct Qualifier { Ptr , Mut }
enum struct PtrLikeQualifier { Ptr = static_cast<int>(Qualifier::Ptr) , Q_END }
Functions
auto make_atom (std::string_view value) noexcept -> Atom
Create an Atom with the given string content.
auto operator""_a (const char *value, std::size_t len) noexcept -> Atom
static auto make_cdtor_fn (llvm::IRBuilder<> &builder, llvm::Module &module, bool is_ctor) -> llvm::Function *
static auto vtable_entry_for (const Fn &fn) -> VTableEntry
static void create_vtable_for (Struct &st)
static auto build_function_type (Compiler &compiler, const ty::Function &type) -> llvm::Type *
static auto build_struct_type (Compiler &compiler, const ty::Struct &type) -> llvm::Type *
static void destruct_indirect (Compiler &compiler, const InScope &v)
static auto constexpr const_hash (const char *input) -> unsigned
A constexpr-friendly simple string hash, for simple switches with string cases.
static auto vals_to_llvm (const vector< Val > &in) -> vector< llvm::Value * >
void backtrace (void *)
auto what (const std::exception_ptr &eptr=std::current_exception()) -> std::string_view
auto current_exception_name () -> const char *
void print_exception ()
auto at (const source_location location=source_location::current()) -> std::string
auto tokenize_preserve_skipped (std::istream &in, const string &source_file) -> vector< Token >
Consume the contents of the input stream and create corresponding tokens, preserving every token, including whitespace. This is usually undesired.
auto tokenize (std::istream &in, const string &source_file) -> vector< Token >
Consume the contents of the input stream and create corresponding tokens, ignoring insignificant whitespace.
auto operator<< (llvm::raw_ostream &os, const Token &token) -> llvm::raw_ostream &
template<typename T >
constexpr void yume_assert (T &&assertion, const std::string_view log_msg={}, const source_location location=source_location::current()) noexcept
auto open_file (nonnull< const char * > filename) -> unique_ptr< llvm::raw_pwrite_stream >
Opens a writeable stream to a file with the given filename relative to the current working directory.
auto stem (std::string_view sv) -> std::string_view
The stem of a path-like string, which is the component after the last slash.
Variables
static constexpr const auto always_false = [](auto&&...) { return false; }
template<StringLiteral msg, typename RetT = void>
static constexpr const auto always_throw = [](auto&&...) -> RetT { throw std::runtime_error(msg.value); }
template<auto pm, typename R = void>
static constexpr const auto fwd = [](auto&&... args) -> R { return std::invoke(pm, args...); }
template<auto pm>
static constexpr const auto fwd< pm, void > = [](auto&&... args) -> decltype(auto) { return std::invoke(pm, args...); }
static constexpr any_of_fn any_of
constexpr bool ENABLE_ASSERT = true
static constexpr std::string_view VERSION = "???"
static constexpr std::string_view GIT_SHORTHASH = "???"
Typedef Documentation
char_fn
using yume::char_fn = typedef std::function<bool(TokenState&)>
Definition at line 63 of file token.cpp.
char_pos_fn
using yume::char_pos_fn = typedef bool(char, size_t)
Definition at line 38 of file token.cpp.
char_raw_fn
using yume::char_raw_fn = typedef bool(char)
Definition at line 37 of file token.cpp.
DeclLike_t
using yume::DeclLike_t = typedef visitable_variant<std::monostate, Fn*, Struct*, Const*>
Definition at line 196 of file vals.hpp.
Def_t
using yume::Def_t = typedef visitable_variant<ast::FnDecl*, ast::CtorDecl*, ast::LambdaExpr*>
Definition at line 42 of file vals.hpp.
nonnull
template<typename T > using yume::nonnull = typedef T
Definition at line 70 of file util.hpp.
nullable
template<typename T > using yume::nullable = typedef T
Definition at line 69 of file util.hpp.
substitution_t
using yume::substitution_t = typedef std::map<string, ty::Type>
Definition at line 18 of file substitution.hpp.
Enumeration Type Documentation
PtrLikeQualifier
enum struct yume::PtrLikeQualifier strong
Enumerator
Ptr
ptr
Q_END
Definition at line 9 of file qualifier.hpp.
Qualifier
enum struct yume::Qualifier strong
Enumerator
Ptr
ptr
Mut
mut
Definition at line 4 of file qualifier.hpp.
Function Documentation
at()
auto yume::at (const source_location location = source_location::current()) -> std::string inline
Definition at line 34 of file source_location.hpp.
Referenced by yume::ast::parser::Parser::assert_payload_next(), yume::ast::parser::Parser::consume(), yume::ast::parser::Parser::consume_word(), yume::ast::parser::Parser::expect(), yume::ast::parser::Parser::ignore_separator(), yume::ast::parser::Parser::next(), yume::ast::parser::Parser::try_consume(), yume::ast::parser::Parser::try_peek(), and yume::ast::parser::Parser::try_peek_uword().
backtrace()
void yume::backtrace (void *)
Definition at line 284 of file errors.cpp.
Referenced by main().
build_function_type()
static auto yume::build_function_type (Compiler & compiler, const ty::Function & type) -> llvm::Type* static
Definition at line 331 of file compiler.cpp.
Referenced by yume::Compiler::llvm_type().
build_struct_type()
static auto yume::build_struct_type (Compiler & compiler, const ty::Struct & type) -> llvm::Type* static
Definition at line 373 of file compiler.cpp.
Referenced by yume::Compiler::llvm_type().
const_hash()
static auto constexpr yume::const_hash (const char * input) -> unsigned static constexpr
A constexpr-friendly simple string hash, for simple switches with string cases.
Definition at line 922 of file compiler.cpp.
References const_hash().
Referenced by const_hash().
create_vtable_for()
static void yume::create_vtable_for (Struct & st) inline static
Definition at line 151 of file compiler.cpp.
References yume::Struct::ast(), yume::Struct::body(), vtable_entry_for(), yume::Struct::vtable_members, and yume_assert().
Referenced by yume::Compiler::run().
current_exception_name()
auto yume::current_exception_name () -> const char* inline
Definition at line 35 of file errors.hpp.
Referenced by print_exception().
destruct_indirect()
static void yume::destruct_indirect (Compiler & compiler, const InScope & v) static
Definition at line 539 of file compiler.cpp.
References yume::InScope::ast, yume::Compiler::builder(), yume::Compiler::destruct(), yume::ast::AST::ensure_ty(), yume::Val::llvm, yume::Compiler::llvm_type(), yume::InScope::owning, yume::InScope::value, and yume_assert().
Referenced by yume::Compiler::expression().
make_atom()
auto yume::make_atom (std::string_view value) -> Atom inline noexcept
Create an Atom with the given string content.
See also
atom_literal::operator""_a
Definition at line 34 of file atom.hpp.
References yume::Atom::make_atom().
Referenced by operator""_a(), and yume::ast::parser::Parser::try_parse_type().
make_cdtor_fn()
static auto yume::make_cdtor_fn (llvm::IRBuilder<> & builder, llvm::Module & module, bool is_ctor) -> llvm::Function* static
Definition at line 60 of file compiler.cpp.
Referenced by yume::Compiler::Compiler().
open_file()
auto yume::open_file (nonnull< const char * > filename) -> unique_ptr<llvm::raw_pwrite_stream> inline
Opens a writeable stream to a file with the given filename relative to the current working directory.
Definition at line 90 of file util.hpp.
Referenced by compile(), and yume::Compiler::write_object().
operator""_a()
auto yume::operator""_a (const char * value, std::size_t len) -> Atom inline noexcept
Definition at line 36 of file atom.hpp.
References make_atom().
operator<<()
auto yume::operator<< (llvm::raw_ostream & os, const Token & token) -> llvm::raw_ostream&
Definition at line 307 of file token.cpp.
print_exception()
void yume::print_exception () inline
Definition at line 41 of file errors.hpp.
References current_exception_name(), and what().
Referenced by main().
stem()
auto yume::stem (std::string_view sv) -> std::string_view inline
The stem of a path-like string, which is the component after the last slash.
"foo/bar/file.txt" -> "file.txt"
Definition at line 106 of file util.hpp.
Referenced by compile(), and yume::Loc::to_string().
tokenize()
auto yume::tokenize (std::istream & in, const string & source_file) -> vector< Token >
Consume the contents of the input stream and create corresponding tokens, ignoring insignificant whitespace.
Definition at line 298 of file token.cpp.
References tokenize_preserve_skipped().
tokenize_preserve_skipped()
auto yume::tokenize_preserve_skipped (std::istream & in, const string & source_file) -> vector< Token >
Consume the contents of the input stream and create corresponding tokens, preserving every token, including whitespace. This is usually undesired.
See also
tokenize
Definition at line 292 of file token.cpp.
Referenced by tokenize().
vals_to_llvm()
static auto yume::vals_to_llvm (const vector< Val > & in) -> vector<llvm::Value*> inline static
Definition at line 949 of file compiler.cpp.
Referenced by yume::Compiler::expression().
vtable_entry_for()
static auto yume::vtable_entry_for (const Fn & fn) -> VTableEntry inline static
Definition at line 147 of file compiler.cpp.
References yume::Fn::arg_types(), yume::Fn::name(), yume::VTableEntry::name, and yume::Fn::ret().
Referenced by create_vtable_for(), yume::Compiler::define(), and yume::Compiler::expression().
what()
auto yume::what (const std::exception_ptr & eptr = std::current_exception()) -> std::string_view inline
Definition at line 17 of file errors.hpp.
Referenced by print_exception().
yume_assert()
template<typename T > constexpr void yume::yume_assert (T && assertion, const std::string_view log_msg = {}, const source_location location = source_location::current()) inline constexpr noexcept
Definition at line 80 of file util.hpp.
Referenced by yume::ast::AnyBase< T >::AnyBase(), yume::ty::Type::apply_generic_substitution(), yume::Compiler::create_struct(), create_vtable_for(), yume::Compiler::declare(), yume::Compiler::define(), destruct_indirect(), yume::ty::Type::determine_generic_subs(), yume::Compiler::direct_call_operator(), yume::ast::AST::ensure_ty(), yume::semantic::TypeWalker::expression(), yume::Compiler::expression(), yume::Compiler::llvm_type(), yume::semantic::TypeWalker::make_dup(), yume::mangle::mangle_name(), yume::Loc::operator+(), yume::Compiler::run(), yume::semantic::TypeWalker::statement(), yume::ty::visit_subs(), and yume::ScopeContainerGuard< T >::~ScopeContainerGuard().
Variable Documentation
always_false
constexpr const auto yume::always_false = [](auto&&...) { return false; } static constexpr
Definition at line 9 of file vals.cpp.
Referenced by yume::Fn::abstract(), yume::Fn::extern_decl(), yume::Fn::extern_linkage(), yume::Fn::local(), yume::Fn::primitive(), and yume::Fn::varargs().
always_throw
template<StringLiteral msg, typename RetT = void> constexpr const auto yume::always_throw = [](auto&&...) -> RetT { throw std::runtime_error(msg.value); } static constexpr
Definition at line 12 of file vals.cpp.
Referenced by yume::Fn::fn_body(), and yume::Fn::make_extern_linkage().
any_of
constexpr any_of_fn yume::any_of static constexpr
Definition at line 34 of file token.cpp.
Referenced by yume::Compiler::create_struct(), yume::Compiler::expression(), yume::ty::Type::is_generic(), and yume::semantic::TypeWalker::statement().
ENABLE_ASSERT
constexpr bool yume::ENABLE_ASSERT = true constexpr
Definition at line 76 of file util.hpp.
fwd
template<auto pm, typename R = void> constexpr const auto yume::fwd = [](auto&&... args) -> R { return std::invoke(pm, args...); } static constexpr
Definition at line 15 of file vals.cpp.
fwd< pm, void >
template<auto pm> constexpr const auto yume::fwd< pm, void > = [](auto&&... args) -> decltype(auto) { return std::invoke(pm, args...); } static constexpr
Definition at line 17 of file vals.cpp.
GIT_SHORTHASH
constexpr std::string_view yume::GIT_SHORTHASH = "???" static constexpr
Definition at line 33 of file yumec.cpp.
Referenced by emit_version().
VERSION
constexpr std::string_view yume::VERSION = "???" static constexpr
Definition at line 32 of file yumec.cpp.
Referenced by emit_version().