Yume: yume::ty Namespace Reference
yume::ty Namespace Reference
Namespaces
namespace detail
Classes
class BaseType
Represents a type in the type system. NOTE: that this isn't the class to use for type introspection, for that, Type should be used instead as it is fully qualified.
struct Compat
The compatibility between two types, for overload selection.
struct Conv
class Function
A function pointer type.
class Generic
An unsubstituted generic type variable, usually something like T.
class Int
A built-in integral type, such as I32 or Bool.
class Nil
The null type, Nil.
class OpaqueSelf
The "self" type of abstract or overriding functions. An extra layer of indirection is introduced for type erasure.
class Ptr
A "qualified" type, with a stackable qualifier, i.e. ptr.
class Struct
An user-defined struct type with associated fields.
struct Sub
class Type
A "qualified" type, with a non-stackable qualifier, i.e. mut.
Enumerations
enum Kind {
K_Unknown , K_Int , K_Nil , K_Ptr ,
K_Struct , K_Function , K_Generic , K_OpaqueSelf
}
Functions
static auto qual_suffix (Qualifier qual) -> string
static auto visit_subs (Type a, Type b, optional< Sub > sub) -> optional< Sub >
static auto intersect_generics (Substitution &subs, const Generic *gen, ty::Type gen_sub) -> optional< ty::Type >
Add the substitution gen_sub for the generic type variable gen in template instantiation instantiation. If a substitution already exists for the same type variable, the two substitutions are intersected.
Enumeration Type Documentation
Kind
enum yume::ty::Kind
Enumerator
K_Unknown
UnknownType, default, zero value. Hopefully never encountered!
K_Int
Int
K_Nil
Nil
K_Ptr
Ptr
K_Struct
Struct
K_Function
Function
K_Generic
Generic
K_OpaqueSelf
OpaqueSelf
Definition at line 15 of file type_base.hpp.
Function Documentation
intersect_generics()
static auto yume::ty::intersect_generics (Substitution & subs, const Generic * gen, ty::Type gen_sub) -> optional<ty::Type> static
Add the substitution gen_sub for the generic type variable gen in template instantiation instantiation. If a substitution already exists for the same type variable, the two substitutions are intersected.
Returns
nullopt if substitution failed
Definition at line 79 of file type.cpp.
Referenced by yume::ty::Type::determine_generic_subs().
qual_suffix()
static auto yume::ty::qual_suffix (Qualifier qual) -> string static
Definition at line 18 of file type.cpp.
References yume::Mut, yume::Ptr, and yume::Ref.
Referenced by yume::ty::Type::name(), and yume::ty::Ptr::name().
visit_subs()
static auto yume::ty::visit_subs (Type a, Type b, optional< Sub > sub) -> optional<Sub> static
Definition at line 43 of file type.cpp.
References yume::ty::Ptr::qualifier(), visit_subs(), and yume::yume_assert().
Referenced by yume::ty::Type::determine_generic_subs(), and visit_subs().