Yume: yume::ast Namespace Reference
yume::ast Namespace Reference
Classes
class AssignExpr
An assignment (=).
class AST
All nodes in the AST tree of the program inherit from this class.
struct Attachment
Represents the relationship between multiple AST nodes.
class BoolExpr
Bool literals (true or false).
class CallExpr
A function call or operator.
class CharExpr
Char literals.
class Compound
A statement consisting of multiple other statements, i.e. the body of a function.
class CtorExpr
A construction of a struct or cast of a primitive.
class Expr
Expressions have an associated value and type.
class FieldAccessExpr
Direct access of a field of a struct (::).
class FnDecl
A declaration of a function (def).
class IfClause
Clauses of an if statement IfStmt.
class IfStmt
An if statement (if), with one or more IfClauses, and optionally an else clause.
class NumberExpr
Number literals.
class Program
The top level structure of a file of source code.
class QualType
A type with a Qualifier like mut or [] following.
class ReturnStmt
Return from a function body.
class SelfType
The self type.
class SimpleType
Just the name of a type, always capitalized.
class SliceExpr
A slice literal, i.e. an array.
class Stmt
Statements make up most things in source code.
class StringExpr
String literals.
class StructDecl
A declaration of a struct (struct).
struct TokenIterator
An iterator-like holding Tokens, used when parsing.
class Type
A type annotation. This (ast::Type) is distinct from the actual type of a value (ty::Type).
class TypeName
A pair of a Type and an identifier, i.e. a parameter name.
class VarDecl
A declaration of a local variable (let).
class VarExpr
A variable, i.e. just an identifier.
class WhileStmt
A while loop (while).
Typedefs
using VectorTokenIterator = vector< Token >::iterator
Enumerations
enum Kind {
K_Unknown , K_IfClause , K_TypeName , K_Stmt ,
K_Compound , K_FnDecl , K_StructDecl , K_VarDecl ,
K_While , K_If , K_Return , K_Program ,
K_Expr , K_Number , K_Char , K_Bool ,
K_String , K_Var , K_Call , K_Ctor ,
K_Slice , K_Assign , K_FieldAccess , K_END_Expr ,
K_END_Stmt , K_Type , K_SimpleType , K_QualType ,
K_SelfType , K_END_Type
}
Functions
static auto ts (auto &&begin, int end)
static auto ts (auto &&begin, TokenIterator &end)
static auto ts (auto &&begin, auto &&end)
template<typename T , typename... Args>
static auto make_ast (auto &&begin, auto &&end, Args &&... args)
auto operators ()
auto unary_operators ()
auto to_string (Token token) -> string
auto ignore_separator (TokenIterator &tokens, const source_location location=source_location::current()) -> bool
Ignore any Separator tokens if any are present.
void expect (TokenIterator &tokens, Token::Type token_type, const source_location location=source_location::current())
If the next token doesn't have the type, token_type, throw a runtime exception.
void require_separator (TokenIterator &tokens, const source_location location=source_location::current())
Consume all subsequent Separator tokens. Throws if none were found.
void consume (TokenIterator &tokens, Token::Type token_type, Atom payload, const source_location location=source_location::current())
Consume a token of type token_type with the given payload. Throws if it wasn't encountered.
auto try_consume (TokenIterator &tokens, Token::Type tokenType, Atom payload, const source_location location=source_location::current()) -> bool
Attempt to consume a token of type token_type with the given payload. Does nothing if it wasn't encountered.
auto try_peek (TokenIterator &tokens, int ahead, Token::Type token_type, Atom payload, const source_location location=source_location::current()) -> bool
Check if the token ahead by ahead is of type token_type with the given payload.
auto try_peek (TokenIterator &tokens, int ahead, Token::Type token_type, const source_location location=source_location::current()) -> bool
Check if the token ahead by ahead is of type token_type.
void consume_with_commas_until (TokenIterator &tokens, Token::Type token_type, Atom payload, auto action, const source_location location=source_location::current())
Consume tokens until a token of type token_type with the given payload is encountered. action (a no-arg function) is called every time. Between each call, a comma is expected.
auto next (TokenIterator &tokens, const source_location location=source_location::current()) -> Token
Return the next token and increment the iterator.
auto consume_word (TokenIterator &tokens, const source_location location=source_location::current()) -> string
Return the payload of the next token. Throws if the next token isn't a Word.
auto is_uword (const string &word) -> bool
Check if the string begins with a capital letter. Used for types, as all types must be capitalized.
auto try_peek_uword (TokenIterator &tokens, int ahead, const source_location location=source_location::current()) -> bool
Check if the ahead by ahead is a capitalized word.
static auto parse_stmt (TokenIterator &tokens) -> unique_ptr< Stmt >
static auto parse_expr (TokenIterator &tokens) -> unique_ptr< Expr >
static auto parse_type (TokenIterator &tokens, bool implicit_self=false) -> unique_ptr< Type >
static auto parse_type_name (TokenIterator &tokens) -> unique_ptr< TypeName >
static auto try_parse_type (TokenIterator &tokens) -> optional< unique_ptr< Type > >
static auto parse_fn_name (TokenIterator &tokens) -> string
static auto parse_struct_decl (TokenIterator &tokens) -> unique_ptr< StructDecl >
static auto parse_fn_decl (TokenIterator &tokens) -> unique_ptr< FnDecl >
static auto parse_var_decl (TokenIterator &tokens) -> unique_ptr< VarDecl >
static auto parse_while_stmt (TokenIterator &tokens) -> unique_ptr< WhileStmt >
static auto parse_return_stmt (TokenIterator &tokens) -> unique_ptr< ReturnStmt >
static auto parse_if_stmt (TokenIterator &tokens) -> unique_ptr< IfStmt >
static auto parse_number_expr (TokenIterator &tokens) -> unique_ptr< NumberExpr >
static auto parse_string_expr (TokenIterator &tokens) -> unique_ptr< StringExpr >
static auto parse_char_expr (TokenIterator &tokens) -> unique_ptr< CharExpr >
static auto parse_primary (TokenIterator &tokens) -> unique_ptr< Expr >
static auto parse_receiver (TokenIterator &tokens, unique_ptr< Expr > receiver, auto receiver_entry) -> unique_ptr< Expr >
static auto parse_receiver (TokenIterator &tokens) -> unique_ptr< Expr >
static auto parse_unary (TokenIterator &tokens) -> unique_ptr< Expr >
static auto parse_operator (TokenIterator &tokens, size_t n=0) -> unique_ptr< Expr >
auto constexpr kind_name (Kind type) -> const char *
Variables
static constexpr auto Symbol = Token::Type::Symbol
static constexpr auto Word = Token::Type::Word
static constexpr auto Separator = Token::Type::Separator
static constexpr auto Number = Token::Type::Number
static const Atom KWD_IF = "if"_a
static const Atom KWD_DEF = "def"_a
static const Atom KWD_END = "end"_a
static const Atom KWD_LET = "let"_a
static const Atom KWD_PTR = "ptr"_a
static const Atom KWD_MUT = "mut"_a
static const Atom KWD_ELSE = "else"_a
static const Atom KWD_SELF_ITEM = "self"_a
static const Atom KWD_SELF_TYPE = "Self"_a
static const Atom KWD_THEN = "then"_a
static const Atom KWD_TRUE = "true"_a
static const Atom KWD_FALSE = "false"_a
static const Atom KWD_WHILE = "while"_a
static const Atom KWD_STRUCT = "struct"_a
static const Atom KWD_RETURN = "return"_a
static const Atom KWD_VARARGS = "__varargs__"_a
static const Atom KWD_PRIMITIVE = "__primitive__"_a
static const Atom SYM_COMMA = ","_a
static const Atom SYM_DOT = "."_a
static const Atom SYM_EQ = "="_a
static const Atom SYM_LPAREN = "("_a
static const Atom SYM_RPAREN = ")"_a
static const Atom SYM_LBRACKET = "["_a
static const Atom SYM_RBRACKET = "]"_a
static const Atom SYM_LBRACE = "{"_a
static const Atom SYM_RBRACE = "}"_a
static const Atom SYM_EQ_EQ = "=="_a
static const Atom SYM_NEQ = "!="_a
static const Atom SYM_GT = ">"_a
static const Atom SYM_LT = "<"_a
static const Atom SYM_PLUS = "+"_a
static const Atom SYM_MINUS = "-"_a
static const Atom SYM_PERCENT = "%"_a
static const Atom SYM_SLASH_SLASH = "//"_a
static const Atom SYM_STAR = "*"_a
static const Atom SYM_BANG = "!"_a
static const Atom SYM_COLON = ":"_a
Typedef Documentation
VectorTokenIterator
using yume::ast::VectorTokenIterator = typedef vector<Token>::iterator
Definition at line 96 of file ast.hpp.
Enumeration Type Documentation
Kind
enum yume::ast::Kind
Enumerator
K_Unknown
Unknown, default, zero value. Hopefully never encountered!
K_IfClause
IfClause
K_TypeName
TypeName
K_Stmt
Stmt
K_Compound
Compound
K_FnDecl
FnDecl
K_StructDecl
StructDecl
K_VarDecl
VarDecl
K_While
WhileStmt
K_If
IfStmt
K_Return
ReturnStmt
K_Program
Program
K_Expr
Expr
K_Number
NumberExpr
K_Char
CharExpr
K_Bool
BoolExpr
K_String
StringExpr
K_Var
VarExpr
K_Call
CallExpr
K_Ctor
CtorExpr
K_Slice
SliceExpr
K_Assign
AssignExpr
K_FieldAccess
FieldAccessExpr
K_END_Expr
K_END_Stmt
K_Type
Type
K_SimpleType
SimpleType
K_QualType
QualType
K_SelfType
SelfType
K_END_Type
Definition at line 27 of file ast.hpp.
Function Documentation
consume()
void yume::ast::consume (TokenIterator & tokens, Token::Type token_type, Atom payload, const source_location location = source_location::current())
Consume a token of type token_type with the given payload. Throws if it wasn't encountered.
Definition at line 119 of file ast.cpp.
References yume::at(), expect(), ignore_separator(), and to_string().
Referenced by consume_with_commas_until(), parse_fn_decl(), parse_fn_name(), parse_if_stmt(), parse_primary(), parse_receiver(), parse_return_stmt(), parse_struct_decl(), parse_type(), parse_var_decl(), parse_while_stmt(), and try_parse_type().
consume_with_commas_until()
void yume::ast::consume_with_commas_until (TokenIterator & tokens, Token::Type token_type, Atom payload, auto action, const source_location location = source_location::current())
Consume tokens until a token of type token_type with the given payload is encountered. action (a no-arg function) is called every time. Between each call, a comma is expected.
Definition at line 178 of file ast.cpp.
References consume(), SYM_COMMA, Symbol, and try_consume().
Referenced by parse_fn_decl(), parse_primary(), parse_receiver(), and parse_struct_decl().
consume_word()
auto yume::ast::consume_word (TokenIterator & tokens, const source_location location = source_location::current()) -> string
Return the payload of the next token. Throws if the next token isn't a Word.
Definition at line 199 of file ast.cpp.
References yume::at(), ignore_separator(), next(), to_string(), and Word.
Referenced by parse_fn_decl(), parse_fn_name(), parse_primary(), parse_receiver(), parse_struct_decl(), parse_type(), parse_type_name(), parse_var_decl(), and try_parse_type().
expect()
void yume::ast::expect (TokenIterator & tokens, Token::Type token_type, const source_location location = source_location::current())
If the next token doesn't have the type, token_type, throw a runtime exception.
Definition at line 104 of file ast.cpp.
References yume::at(), to_string(), and yume::Token::type_name().
Referenced by consume(), parse_char_expr(), parse_number_expr(), parse_string_expr(), and require_separator().
ignore_separator()
auto yume::ast::ignore_separator (TokenIterator & tokens, const source_location location = source_location::current()) -> bool
Ignore any Separator tokens if any are present.
Returns
true if a separator was encountered (and consumed)
Definition at line 90 of file ast.cpp.
References yume::at(), yume::ast::TokenIterator::at_end(), and Separator.
Referenced by consume(), consume_word(), yume::ast::Program::parse(), parse_fn_decl(), parse_struct_decl(), parse_while_stmt(), and require_separator().
is_uword()
auto yume::ast::is_uword (const string & word) -> bool
Check if the string begins with a capital letter. Used for types, as all types must be capitalized.
Definition at line 208 of file ast.cpp.
Referenced by parse_struct_decl(), parse_type(), try_parse_type(), and try_peek_uword().
kind_name()
auto constexpr yume::ast::kind_name (Kind type) -> const char* inline constexpr
Definition at line 66 of file ast.hpp.
References K_Assign, K_Bool, K_Call, K_Char, K_Compound, K_Ctor, K_FieldAccess, K_FnDecl, K_If, K_IfClause, K_Number, K_Program, K_QualType, K_Return, K_SelfType, K_SimpleType, K_Slice, K_String, K_StructDecl, K_TypeName, K_Unknown, K_Var, K_VarDecl, and K_While.
Referenced by yume::ast::AST::kind_name().
make_ast()
template<typename T , typename... Args> static auto yume::ast::make_ast (auto && begin, auto && end, Args &&... args) static
Definition at line 16 of file ast.cpp.
References ts().
next()
auto yume::ast::next (TokenIterator & tokens, const source_location location = source_location::current()) -> Token
Return the next token and increment the iterator.
Definition at line 189 of file ast.cpp.
References yume::at().
Referenced by consume_word(), parse_char_expr(), parse_number_expr(), parse_string_expr(), and yume::Compiler::run().
operators()
auto yume::ast::operators ()
Definition at line 64 of file ast.cpp.
References SYM_EQ_EQ, SYM_GT, SYM_LT, SYM_MINUS, SYM_NEQ, SYM_PERCENT, SYM_PLUS, SYM_SLASH_SLASH, and SYM_STAR.
Referenced by parse_fn_name(), and parse_operator().
parse_char_expr()
static auto yume::ast::parse_char_expr (TokenIterator & tokens) -> unique_ptr<CharExpr> static
Definition at line 467 of file ast.cpp.
References yume::ast::TokenIterator::begin(), yume::Token::Char, expect(), and next().
Referenced by parse_primary().
parse_expr()
static auto yume::ast::parse_expr (TokenIterator & tokens) -> unique_ptr<Expr> static
Definition at line 709 of file ast.cpp.
References parse_operator().
Referenced by parse_fn_decl(), parse_if_stmt(), parse_primary(), parse_receiver(), parse_return_stmt(), parse_stmt(), parse_var_decl(), and parse_while_stmt().
parse_fn_decl()
static auto yume::ast::parse_fn_decl (TokenIterator & tokens) -> unique_ptr<FnDecl> static
Definition at line 306 of file ast.cpp.
References yume::ast::TokenIterator::begin(), consume(), consume_with_commas_until(), consume_word(), ignore_separator(), KWD_DEF, KWD_END, KWD_PRIMITIVE, KWD_VARARGS, parse_expr(), parse_fn_name(), parse_stmt(), parse_type_name(), require_separator(), SYM_EQ, SYM_GT, SYM_LPAREN, SYM_LT, SYM_RPAREN, Symbol, try_consume(), try_parse_type(), ts(), and Word.
Referenced by parse_stmt().
parse_fn_name()
static auto yume::ast::parse_fn_name (TokenIterator & tokens) -> string static
Definition at line 240 of file ast.cpp.
References consume(), consume_word(), operators(), SYM_BANG, SYM_EQ, SYM_LBRACKET, SYM_RBRACKET, Symbol, try_consume(), and Word.
Referenced by parse_fn_decl().
parse_if_stmt()
static auto yume::ast::parse_if_stmt (TokenIterator & tokens) -> unique_ptr<IfStmt> static
Definition at line 395 of file ast.cpp.
References yume::ast::TokenIterator::begin(), consume(), KWD_ELSE, KWD_END, KWD_IF, KWD_THEN, parse_expr(), parse_stmt(), require_separator(), try_consume(), ts(), and Word.
Referenced by parse_stmt().
parse_number_expr()
static auto yume::ast::parse_number_expr (TokenIterator & tokens) -> unique_ptr<NumberExpr> static
Definition at line 451 of file ast.cpp.
References yume::ast::TokenIterator::begin(), expect(), next(), and Number.
Referenced by parse_primary().
parse_operator()
static auto yume::ast::parse_operator (TokenIterator & tokens, size_t n = 0) -> unique_ptr<Expr> static
Definition at line 586 of file ast.cpp.
References yume::ast::TokenIterator::begin(), operators(), parse_operator(), parse_unary(), Symbol, and try_consume().
Referenced by parse_expr(), and parse_operator().
parse_primary()
static auto yume::ast::parse_primary (TokenIterator & tokens) -> unique_ptr<Expr> static
Definition at line 475 of file ast.cpp.
References yume::ast::TokenIterator::begin(), yume::Token::Char, consume(), consume_with_commas_until(), consume_word(), KWD_FALSE, KWD_TRUE, yume::Token::Literal, Number, parse_char_expr(), parse_expr(), parse_number_expr(), parse_string_expr(), parse_type(), SYM_LBRACKET, SYM_LPAREN, SYM_RBRACKET, SYM_RPAREN, Symbol, try_consume(), try_peek_uword(), and Word.
Referenced by parse_receiver().
parse_receiver() [1/2]
static auto yume::ast::parse_receiver (TokenIterator & tokens) -> unique_ptr<Expr> static
Definition at line 568 of file ast.cpp.
References yume::ast::TokenIterator::begin(), parse_primary(), and parse_receiver().
parse_receiver() [2/2]
static auto yume::ast::parse_receiver (TokenIterator & tokens, unique_ptr< Expr > receiver, auto receiver_entry) -> unique_ptr<Expr> static
Definition at line 520 of file ast.cpp.
References yume::ast::TokenIterator::begin(), consume(), consume_with_commas_until(), consume_word(), parse_expr(), parse_receiver(), SYM_COLON, SYM_DOT, SYM_EQ, SYM_LBRACKET, SYM_LPAREN, SYM_RBRACKET, SYM_RPAREN, Symbol, and try_consume().
Referenced by parse_receiver(), and parse_unary().
parse_return_stmt()
static auto yume::ast::parse_return_stmt (TokenIterator & tokens) -> unique_ptr<ReturnStmt> static
Definition at line 383 of file ast.cpp.
References yume::ast::TokenIterator::at_end(), yume::ast::TokenIterator::begin(), consume(), KWD_RETURN, parse_expr(), Separator, try_peek(), and Word.
Referenced by parse_stmt().
parse_stmt()
static auto yume::ast::parse_stmt (TokenIterator & tokens) -> unique_ptr<Stmt> static
Definition at line 612 of file ast.cpp.
References KWD_DEF, KWD_IF, KWD_LET, KWD_RETURN, KWD_STRUCT, KWD_WHILE, parse_expr(), parse_fn_decl(), parse_if_stmt(), parse_return_stmt(), parse_struct_decl(), parse_var_decl(), parse_while_stmt(), and require_separator().
Referenced by yume::ast::Program::parse(), parse_fn_decl(), parse_if_stmt(), parse_struct_decl(), and parse_while_stmt().
parse_string_expr()
static auto yume::ast::parse_string_expr (TokenIterator & tokens) -> unique_ptr<StringExpr> static
Definition at line 459 of file ast.cpp.
References yume::ast::TokenIterator::begin(), expect(), yume::Token::Literal, and next().
Referenced by parse_primary().
parse_struct_decl()
static auto yume::ast::parse_struct_decl (TokenIterator & tokens) -> unique_ptr<StructDecl> static
Definition at line 275 of file ast.cpp.
References yume::ast::TokenIterator::begin(), consume(), consume_with_commas_until(), consume_word(), ignore_separator(), is_uword(), KWD_END, KWD_STRUCT, parse_stmt(), parse_type_name(), require_separator(), SYM_GT, SYM_LPAREN, SYM_LT, SYM_RPAREN, Symbol, try_consume(), ts(), and Word.
Referenced by parse_stmt().
parse_type()
static auto yume::ast::parse_type (TokenIterator & tokens, bool implicit_self = false) -> unique_ptr<Type> static
Definition at line 634 of file ast.cpp.
References yume::ast::TokenIterator::begin(), consume(), consume_word(), is_uword(), KWD_MUT, KWD_PTR, KWD_SELF_TYPE, yume::Mut, yume::Ptr, yume::Slice, SYM_LBRACKET, SYM_RBRACKET, Symbol, try_consume(), try_peek(), and Word.
Referenced by parse_primary(), and parse_type_name().
parse_type_name()
static auto yume::ast::parse_type_name (TokenIterator & tokens) -> unique_ptr<TypeName> static
Definition at line 698 of file ast.cpp.
References yume::ast::TokenIterator::begin(), consume_word(), KWD_SELF_ITEM, parse_type(), try_consume(), and Word.
Referenced by parse_fn_decl(), and parse_struct_decl().
parse_unary()
static auto yume::ast::parse_unary (TokenIterator & tokens) -> unique_ptr<Expr> static
Definition at line 573 of file ast.cpp.
References yume::ast::TokenIterator::begin(), parse_receiver(), Symbol, try_consume(), and unary_operators().
Referenced by parse_operator().
parse_var_decl()
static auto yume::ast::parse_var_decl (TokenIterator & tokens) -> unique_ptr<VarDecl> static
Definition at line 349 of file ast.cpp.
References yume::ast::TokenIterator::begin(), consume(), consume_word(), KWD_LET, parse_expr(), SYM_EQ, Symbol, try_parse_type(), and Word.
Referenced by parse_stmt().
parse_while_stmt()
static auto yume::ast::parse_while_stmt (TokenIterator & tokens) -> unique_ptr<WhileStmt> static
Definition at line 363 of file ast.cpp.
References yume::ast::TokenIterator::begin(), consume(), ignore_separator(), KWD_END, KWD_WHILE, parse_expr(), parse_stmt(), try_consume(), ts(), and Word.
Referenced by parse_stmt().
require_separator()
void yume::ast::require_separator (TokenIterator & tokens, const source_location location = source_location::current())
Consume all subsequent Separator tokens. Throws if none were found.
Definition at line 113 of file ast.cpp.
References expect(), ignore_separator(), and Separator.
Referenced by parse_fn_decl(), parse_if_stmt(), parse_stmt(), and parse_struct_decl().
to_string()
auto yume::ast::to_string (Token token) -> string
Definition at line 82 of file ast.cpp.
Referenced by yume::at(), consume(), consume_word(), yume::ast::NumberExpr::describe(), yume::ast::CharExpr::describe(), expect(), and yume::TypeHolder::TypeHolder().
try_consume()
auto yume::ast::try_consume (TokenIterator & tokens, Token::Type tokenType, Atom payload, const source_location location = source_location::current()) -> bool
Attempt to consume a token of type token_type with the given payload. Does nothing if it wasn't encountered.
Definition at line 136 of file ast.cpp.
References yume::at().
Referenced by consume_with_commas_until(), parse_fn_decl(), parse_fn_name(), parse_if_stmt(), parse_operator(), parse_primary(), parse_receiver(), parse_struct_decl(), parse_type(), parse_type_name(), parse_unary(), parse_while_stmt(), and try_parse_type().
try_parse_type()
static auto yume::ast::try_parse_type (TokenIterator & tokens) -> optional<unique_ptr<Type>> static
Definition at line 664 of file ast.cpp.
References yume::ast::TokenIterator::begin(), consume(), consume_word(), is_uword(), KWD_MUT, KWD_PTR, KWD_SELF_TYPE, yume::make_atom(), yume::Mut, yume::Ptr, yume::Slice, SYM_LBRACKET, SYM_RBRACKET, Symbol, try_consume(), try_peek(), and Word.
Referenced by parse_fn_decl(), and parse_var_decl().
try_peek() [1/2]
auto yume::ast::try_peek (TokenIterator & tokens, int ahead, Token::Type token_type, Atom payload, const source_location location = source_location::current()) -> bool
Check if the token ahead by ahead is of type token_type with the given payload.
Definition at line 151 of file ast.cpp.
References yume::at(), and yume::Token::type_name().
Referenced by parse_return_stmt(), parse_type(), and try_parse_type().
try_peek() [2/2]
auto yume::ast::try_peek (TokenIterator & tokens, int ahead, Token::Type token_type, const source_location location = source_location::current()) -> bool
Check if the token ahead by ahead is of type token_type.
Definition at line 164 of file ast.cpp.
References yume::at(), and yume::Token::type_name().
try_peek_uword()
auto yume::ast::try_peek_uword (TokenIterator & tokens, int ahead, const source_location location = source_location::current()) -> bool
Check if the ahead by ahead is a capitalized word.
Definition at line 211 of file ast.cpp.
References yume::at(), is_uword(), and Word.
Referenced by parse_primary().
ts() [1/3]
static auto yume::ast::ts (auto && begin, auto && end) static
Definition at line 14 of file ast.cpp.
ts() [2/3]
static auto yume::ast::ts (auto && begin, int end) static
Definition at line 12 of file ast.cpp.
Referenced by make_ast(), parse_fn_decl(), parse_if_stmt(), parse_struct_decl(), and parse_while_stmt().
ts() [3/3]
static auto yume::ast::ts (auto && begin, TokenIterator & end) static
Definition at line 13 of file ast.cpp.
References yume::ast::TokenIterator::begin().
unary_operators()
auto yume::ast::unary_operators ()
Definition at line 73 of file ast.cpp.
References SYM_BANG, SYM_MINUS, and SYM_PLUS.
Referenced by parse_unary().
Variable Documentation
KWD_DEF
const Atom yume::ast::KWD_DEF = "def"_a static
Definition at line 26 of file ast.cpp.
Referenced by parse_fn_decl(), and parse_stmt().
KWD_ELSE
const Atom yume::ast::KWD_ELSE = "else"_a static
Definition at line 31 of file ast.cpp.
Referenced by parse_if_stmt().
KWD_END
const Atom yume::ast::KWD_END = "end"_a static
Definition at line 27 of file ast.cpp.
Referenced by parse_fn_decl(), parse_if_stmt(), parse_struct_decl(), and parse_while_stmt().
KWD_FALSE
const Atom yume::ast::KWD_FALSE = "false"_a static
Definition at line 36 of file ast.cpp.
Referenced by parse_primary().
KWD_IF
const Atom yume::ast::KWD_IF = "if"_a static
Definition at line 25 of file ast.cpp.
Referenced by parse_if_stmt(), and parse_stmt().
KWD_LET
const Atom yume::ast::KWD_LET = "let"_a static
Definition at line 28 of file ast.cpp.
Referenced by parse_stmt(), and parse_var_decl().
KWD_MUT
const Atom yume::ast::KWD_MUT = "mut"_a static
Definition at line 30 of file ast.cpp.
Referenced by parse_type(), and try_parse_type().
KWD_PRIMITIVE
const Atom yume::ast::KWD_PRIMITIVE = "__primitive__"_a static
Definition at line 41 of file ast.cpp.
Referenced by parse_fn_decl().
KWD_PTR
const Atom yume::ast::KWD_PTR = "ptr"_a static
Definition at line 29 of file ast.cpp.
Referenced by parse_type(), and try_parse_type().
KWD_RETURN
const Atom yume::ast::KWD_RETURN = "return"_a static
Definition at line 39 of file ast.cpp.
Referenced by parse_return_stmt(), and parse_stmt().
KWD_SELF_ITEM
const Atom yume::ast::KWD_SELF_ITEM = "self"_a static
Definition at line 32 of file ast.cpp.
Referenced by parse_type_name().
KWD_SELF_TYPE
const Atom yume::ast::KWD_SELF_TYPE = "Self"_a static
Definition at line 33 of file ast.cpp.
Referenced by parse_type(), and try_parse_type().
KWD_STRUCT
const Atom yume::ast::KWD_STRUCT = "struct"_a static
Definition at line 38 of file ast.cpp.
Referenced by parse_stmt(), and parse_struct_decl().
KWD_THEN
const Atom yume::ast::KWD_THEN = "then"_a static
Definition at line 34 of file ast.cpp.
Referenced by parse_if_stmt().
KWD_TRUE
const Atom yume::ast::KWD_TRUE = "true"_a static
Definition at line 35 of file ast.cpp.
Referenced by parse_primary().
KWD_VARARGS
const Atom yume::ast::KWD_VARARGS = "__varargs__"_a static
Definition at line 40 of file ast.cpp.
Referenced by parse_fn_decl().
KWD_WHILE
const Atom yume::ast::KWD_WHILE = "while"_a static
Definition at line 37 of file ast.cpp.
Referenced by parse_stmt(), and parse_while_stmt().
Number
constexpr auto yume::ast::Number = Token::Type::Number static constexpr
Definition at line 23 of file ast.cpp.
Referenced by parse_number_expr(), and parse_primary().
Separator
constexpr auto yume::ast::Separator = Token::Type::Separator static constexpr
Definition at line 22 of file ast.cpp.
Referenced by ignore_separator(), parse_return_stmt(), and require_separator().
SYM_BANG
const Atom yume::ast::SYM_BANG = "!"_a static
Definition at line 61 of file ast.cpp.
Referenced by parse_fn_name(), and unary_operators().
SYM_COLON
const Atom yume::ast::SYM_COLON = ":"_a static
Definition at line 62 of file ast.cpp.
Referenced by parse_receiver().
SYM_COMMA
const Atom yume::ast::SYM_COMMA = ","_a static
Definition at line 43 of file ast.cpp.
Referenced by consume_with_commas_until().
SYM_DOT
const Atom yume::ast::SYM_DOT = "."_a static
Definition at line 44 of file ast.cpp.
Referenced by parse_receiver().
SYM_EQ
const Atom yume::ast::SYM_EQ = "="_a static
Definition at line 45 of file ast.cpp.
Referenced by parse_fn_decl(), parse_fn_name(), parse_receiver(), and parse_var_decl().
SYM_EQ_EQ
const Atom yume::ast::SYM_EQ_EQ = "=="_a static
Definition at line 52 of file ast.cpp.
Referenced by operators().
SYM_GT
const Atom yume::ast::SYM_GT = ">"_a static
Definition at line 54 of file ast.cpp.
Referenced by operators(), parse_fn_decl(), and parse_struct_decl().
SYM_LBRACE
const Atom yume::ast::SYM_LBRACE = "{"_a static
Definition at line 50 of file ast.cpp.
SYM_LBRACKET
const Atom yume::ast::SYM_LBRACKET = "["_a static
Definition at line 48 of file ast.cpp.
Referenced by parse_fn_name(), parse_primary(), parse_receiver(), parse_type(), and try_parse_type().
SYM_LPAREN
const Atom yume::ast::SYM_LPAREN = "("_a static
Definition at line 46 of file ast.cpp.
Referenced by parse_fn_decl(), parse_primary(), parse_receiver(), and parse_struct_decl().
SYM_LT
const Atom yume::ast::SYM_LT = "<"_a static
Definition at line 55 of file ast.cpp.
Referenced by operators(), parse_fn_decl(), and parse_struct_decl().
SYM_MINUS
const Atom yume::ast::SYM_MINUS = "-"_a static
Definition at line 57 of file ast.cpp.
Referenced by operators(), and unary_operators().
SYM_NEQ
const Atom yume::ast::SYM_NEQ = "!="_a static
Definition at line 53 of file ast.cpp.
Referenced by operators().
SYM_PERCENT
const Atom yume::ast::SYM_PERCENT = "%"_a static
Definition at line 58 of file ast.cpp.
Referenced by operators().
SYM_PLUS
const Atom yume::ast::SYM_PLUS = "+"_a static
Definition at line 56 of file ast.cpp.
Referenced by operators(), and unary_operators().
SYM_RBRACE
const Atom yume::ast::SYM_RBRACE = "}"_a static
Definition at line 51 of file ast.cpp.
SYM_RBRACKET
const Atom yume::ast::SYM_RBRACKET = "]"_a static
Definition at line 49 of file ast.cpp.
Referenced by parse_fn_name(), parse_primary(), parse_receiver(), parse_type(), and try_parse_type().
SYM_RPAREN
const Atom yume::ast::SYM_RPAREN = ")"_a static
Definition at line 47 of file ast.cpp.
Referenced by parse_fn_decl(), parse_primary(), parse_receiver(), and parse_struct_decl().
SYM_SLASH_SLASH
const Atom yume::ast::SYM_SLASH_SLASH = "//"_a static
Definition at line 59 of file ast.cpp.
Referenced by operators().
SYM_STAR
const Atom yume::ast::SYM_STAR = "*"_a static
Definition at line 60 of file ast.cpp.
Referenced by operators().
Symbol
constexpr auto yume::ast::Symbol = Token::Type::Symbol static constexpr
Definition at line 20 of file ast.cpp.
Referenced by consume_with_commas_until(), parse_fn_decl(), parse_fn_name(), parse_operator(), parse_primary(), parse_receiver(), parse_struct_decl(), parse_type(), parse_unary(), parse_var_decl(), and try_parse_type().
Word
constexpr auto yume::ast::Word = Token::Type::Word static constexpr
Definition at line 21 of file ast.cpp.
Referenced by consume_word(), parse_fn_decl(), parse_fn_name(), parse_if_stmt(), parse_primary(), parse_return_stmt(), parse_struct_decl(), parse_type(), parse_type_name(), parse_var_decl(), parse_while_stmt(), try_parse_type(), and try_peek_uword().