Yume: yume::ast::TokenIterator Struct Reference
yume::ast::TokenIterator Struct Reference
An iterator-like holding Tokens, used when parsing.
#include <ast.hpp>
Public Member Functions
constexpr TokenIterator (const VectorTokenIterator &iterator, const VectorTokenIterator &end)
constexpr auto at_end () const noexcept -> bool
Check if the iterator is at the end and no more Tokens could possibly be read.
auto constexpr operator-> () const noexcept -> Token *
constexpr auto operator* () const noexcept -> Token
constexpr auto operator+ (int i) const noexcept -> TokenIterator
constexpr auto operator++ () -> TokenIterator &
auto operator++ (int) -> TokenIterator
auto begin () const -> VectorTokenIterator
Returns the underlying iterator. This shouldn't really be needed but I'm too lazy to properly model an iterator.
Public Attributes
VectorTokenIterator m_iterator
VectorTokenIterator m_end
Detailed Description
An iterator-like holding Tokens, used when parsing.
Every parse method usually takes this as the first parameter. This is its own struct as it actually holds two iterators, where one is the end. This is to provide safe indexing (avoiding going past the end) without having to pass the end iterator around as a separate parameter.
Definition at line 104 of file ast.hpp.
Constructor & Destructor Documentation
TokenIterator()
constexpr yume::ast::TokenIterator::TokenIterator (const VectorTokenIterator & iterator, const VectorTokenIterator & end) inline constexpr
Definition at line 108 of file ast.hpp.
Member Function Documentation
at_end()
constexpr auto yume::ast::TokenIterator::at_end () const -> bool inline constexpr noexcept
Check if the iterator is at the end and no more Tokens could possibly be read.
Definition at line 112 of file ast.hpp.
References m_end, and m_iterator.
Referenced by operator++(), and yume::ast::Program::parse().
begin()
auto yume::ast::TokenIterator::begin () const -> VectorTokenIterator inline
Returns the underlying iterator. This shouldn't really be needed but I'm too lazy to properly model an iterator.
Definition at line 132 of file ast.hpp.
References m_iterator.
Referenced by yume::ast::Program::parse().
operator*()
constexpr auto yume::ast::TokenIterator::operator* () const -> Token inline constexpr noexcept
Definition at line 114 of file ast.hpp.
References m_iterator.
operator+()
constexpr auto yume::ast::TokenIterator::operator+ (int i) const -> TokenIterator inline constexpr noexcept
Definition at line 115 of file ast.hpp.
References m_end, and m_iterator.
operator++() [1/2]
constexpr auto yume::ast::TokenIterator::operator++ () -> TokenIterator& inline constexpr
Definition at line 118 of file ast.hpp.
References at_end(), and m_iterator.
operator++() [2/2]
auto yume::ast::TokenIterator::operator++ (int) -> TokenIterator inline
Definition at line 125 of file ast.hpp.
References at_end(), m_end, and m_iterator.
operator->()
auto constexpr yume::ast::TokenIterator::operator-> () const -> Token* inline constexpr noexcept
Definition at line 113 of file ast.hpp.
References m_iterator.
Member Data Documentation
m_end
VectorTokenIterator yume::ast::TokenIterator::m_end
Definition at line 106 of file ast.hpp.
Referenced by at_end(), operator+(), and operator++().
m_iterator
VectorTokenIterator yume::ast::TokenIterator::m_iterator
Definition at line 105 of file ast.hpp.
Referenced by at_end(), begin(), operator*(), operator+(), operator++(), and operator->().
The documentation for this struct was generated from the following file:
src/ast/ast.hpp