Yume: yume::visitable_variant< Ts > Struct Template Reference
yume::visitable_variant< Ts > Struct Template Reference
#include <util.hpp>
Public Member Functions
template<typename... Us>
auto visit (Us... us) -> decltype(auto)
template<typename... Us>
auto visit (Us... us) const -> decltype(auto)
Detailed Description
template<typename... Ts>
struct yume::visitable_variant< Ts >
Definition at line 45 of file util.hpp.
Member Function Documentation
visit() [1/2]
template<typename... Ts> template<typename... Us> auto yume::visitable_variant< Ts >::visit (Us... us) -> decltype(auto) inline
Definition at line 55 of file util.hpp.
Referenced by yume::Fn::abstract(), yume::Fn::arg_count(), yume::Fn::arg_nodes(), yume::Fn::ast(), yume::Fn::extern_decl(), yume::Fn::extern_linkage(), yume::Fn::fn_body(), yume::Fn::local(), yume::Fn::make_extern_linkage(), yume::Fn::name(), yume::Fn::primitive(), yume::Fn::ret(), yume::Fn::varargs(), and yume::ast::FnDecl::visit().
visit() [2/2]
template<typename... Ts> template<typename... Us> auto yume::visitable_variant< Ts >::visit (Us... us) const -> decltype(auto) inline
Definition at line 56 of file util.hpp.
The documentation for this struct was generated from the following file:
src/yume/util.hpp