Yume: yume::TokenState Struct Reference
yume::TokenState Struct Reference
Public Member Functions
auto validate (bool val=true) -> bool
auto accept (bool ok) -> bool
auto accept (char chr) -> bool
auto accept (char_raw_fn fn) -> bool
auto accept (char_pos_fn fn) -> bool
auto accept_validate (auto x) -> bool
Public Attributes
bool valid
char c
size_t index
stringstream & stream
Detailed Description
Definition at line 39 of file token.cpp.
Member Function Documentation
accept() [1/4]
auto yume::TokenState::accept (bool ok) -> bool inline
Definition at line 50 of file token.cpp.
References c, and stream.
Referenced by accept_validate().
accept() [2/4]
auto yume::TokenState::accept (char chr) -> bool inline
Definition at line 56 of file token.cpp.
References accept(), and c.
Referenced by accept().
accept() [3/4]
auto yume::TokenState::accept (char_pos_fn fn) -> bool inline
Definition at line 58 of file token.cpp.
References accept(), c, and index.
Referenced by accept().
accept() [4/4]
auto yume::TokenState::accept (char_raw_fn fn) -> bool inline
Definition at line 57 of file token.cpp.
References accept(), and c.
Referenced by accept().
accept_validate()
auto yume::TokenState::accept_validate (auto x) -> bool inline
Definition at line 60 of file token.cpp.
References accept(), and validate().
validate()
auto yume::TokenState::validate (bool val = true) -> bool inline
Definition at line 45 of file token.cpp.
References valid.
Referenced by accept_validate().
Member Data Documentation
c
char yume::TokenState::c
Definition at line 41 of file token.cpp.
Referenced by accept().
index
size_t yume::TokenState::index
Definition at line 42 of file token.cpp.
Referenced by accept().
stream
stringstream& yume::TokenState::stream
Definition at line 43 of file token.cpp.
Referenced by accept().
valid
bool yume::TokenState::valid
Definition at line 40 of file token.cpp.
Referenced by validate().
The documentation for this struct was generated from the following file:
src/yume/token.cpp