Yume: yume::semantic::OverloadSet Struct Reference
yume::semantic::OverloadSet Struct Reference
#include <overload.hpp>
Public Member Functions
auto empty () const -> bool
void dump (llvm::raw_ostream &stream, bool hide_invalid=false) const
void determine_valid_overloads ()
auto is_valid_overload (Overload &overload) -> bool
auto try_best_viable_overload () const -> const Overload *
auto best_viable_overload () const -> Overload
Public Attributes
ast::AST * call
vector< Overload > overloads
vector< ast::AST * > args
unique_ptr< diagnostic::StringNotesHolder > notes = std::make_unique<diagnostic::StringNotesHolder>()
Detailed Description
Definition at line 37 of file overload.hpp.
Member Function Documentation
best_viable_overload()
auto yume::semantic::OverloadSet::best_viable_overload () const -> Overload
Definition at line 300 of file overload.cpp.
References args, call, yume::semantic::get_val_ty, yume::semantic::join_args(), notes, yume::semantic::overload_name(), overloads, and try_best_viable_overload().
determine_valid_overloads()
void yume::semantic::OverloadSet::determine_valid_overloads ()
Definition at line 241 of file overload.cpp.
References is_valid_overload(), and overloads.
dump()
void yume::semantic::OverloadSet::dump (llvm::raw_ostream & stream, bool hide_invalid = false) const
Definition at line 66 of file overload.cpp.
References args, call, yume::semantic::get_val_ty, yume::semantic::join_args(), yume::semantic::overload_name(), and overloads.
empty()
auto yume::semantic::OverloadSet::empty () const -> bool inline
Definition at line 43 of file overload.hpp.
References overloads.
is_valid_overload()
auto yume::semantic::OverloadSet::is_valid_overload (Overload & overload) -> bool
Definition at line 116 of file overload.cpp.
References yume::ty::Type::apply_generic_substitution(), yume::ty::Type::determine_generic_subs(), yume::ast::AST::ensure_ty(), yume::semantic::generic_base(), yume::ty::Type::is_generic(), yume::semantic::literal_cast(), yume::ty::Type::name(), yume::semantic::overload_receiver(), yume::semantic::parameter_count_matches(), and YUME_ASSERT.
Referenced by determine_valid_overloads().
try_best_viable_overload()
auto yume::semantic::OverloadSet::try_best_viable_overload () const -> const Overload*
Definition at line 287 of file overload.cpp.
References yume::semantic::Overload::better_candidate_than(), and overloads.
Referenced by best_viable_overload().
Member Data Documentation
args
vector<ast::AST*> yume::semantic::OverloadSet::args
Definition at line 40 of file overload.hpp.
Referenced by best_viable_overload(), and dump().
call
ast::AST* yume::semantic::OverloadSet::call
Definition at line 38 of file overload.hpp.
Referenced by best_viable_overload(), and dump().
notes
unique_ptr<diagnostic::StringNotesHolder> yume::semantic::OverloadSet::notes = std::make_unique<diagnostic::StringNotesHolder>()
Definition at line 41 of file overload.hpp.
Referenced by best_viable_overload().
overloads
vector<Overload> yume::semantic::OverloadSet::overloads
Definition at line 39 of file overload.hpp.
Referenced by best_viable_overload(), determine_valid_overloads(), dump(), empty(), and try_best_viable_overload().
The documentation for this struct was generated from the following files:
src/yume/semantic/overload.hpp
src/yume/semantic/overload.cpp