Yume: yume::diagnostic::NotesHolder Struct Reference
yume::diagnostic::NotesHolder Struct Reference
#include <notes.hpp>
Public Member Functions
auto emit (Loc location, Severity severity=Severity::Note) -> Note
Public Attributes
vector< SourceFile * > context_files
llvm::raw_ostream * stream {&llvm::errs()}
Loc prev_loc {}
Detailed Description
Definition at line 49 of file notes.hpp.
Member Function Documentation
emit()
auto yume::diagnostic::NotesHolder::emit (Loc location, Severity severity = Severity::Note) -> Note inline
Definition at line 55 of file notes.hpp.
Referenced by yume::ast::parser::Parser::emit_fatal_and_terminate(), and yume::ast::parser::Parser::emit_note().
Member Data Documentation
context_files
vector<SourceFile*> yume::diagnostic::NotesHolder::context_files
Definition at line 51 of file notes.hpp.
Referenced by yume::diagnostic::Note::emit().
prev_loc
Loc yume::diagnostic::NotesHolder::prev_loc {}
Definition at line 53 of file notes.hpp.
Referenced by yume::diagnostic::Note::emit().
stream
llvm::raw_ostream* yume::diagnostic::NotesHolder::stream {&llvm::errs()}
Definition at line 52 of file notes.hpp.
Referenced by yume::diagnostic::Note::emit().
The documentation for this struct was generated from the following file:
src/yume/diagnostic/notes.hpp