Yume: yume::DeclLike Struct Reference
yume::DeclLike Struct Reference
A common base between declarations in the compiler: Fn and Struct. Its value may also be absent (std::monostate).
#include <vals.hpp>
Public Member Functions
template<typename R = void, typename... Ts>
auto visit_decl (Ts... ts)
template<typename R = void, typename... Ts>
auto visit_decl (Ts... ts) const
auto subs () const noexcept -> const Substitution *
auto subs () noexcept -> Substitution *
auto ast () const noexcept -> const ast::AST *
auto ast () noexcept -> ast::AST *
auto self_ty () const noexcept -> optional< ty::Type >
Detailed Description
A common base between declarations in the compiler: Fn and Struct. Its value may also be absent (std::monostate).
Definition at line 194 of file vals.hpp.
Member Function Documentation
ast() [1/2]
auto yume::DeclLike::ast () const -> const ast::AST* inline noexcept
Definition at line 237 of file vals.hpp.
Referenced by yume::semantic::TypeWalker::statement().
ast() [2/2]
auto yume::DeclLike::ast () -> ast::AST* inline noexcept
Definition at line 241 of file vals.hpp.
self_ty()
auto yume::DeclLike::self_ty () const -> optional<ty::Type> inline noexcept
Definition at line 245 of file vals.hpp.
Referenced by yume::semantic::TypeWalker::expression(), and yume::semantic::TypeWalker::statement().
subs() [1/2]
auto yume::DeclLike::subs () const -> const Substitution* inline noexcept
Definition at line 212 of file vals.hpp.
References yume::Struct::subs.
Referenced by yume::semantic::TypeWalker::statement().
subs() [2/2]
auto yume::DeclLike::subs () -> Substitution* inline noexcept
Definition at line 227 of file vals.hpp.
visit_decl() [1/2]
template<typename R = void, typename... Ts> auto yume::DeclLike::visit_decl (Ts... ts) inline
Definition at line 205 of file vals.hpp.
visit_decl() [2/2]
template<typename R = void, typename... Ts> auto yume::DeclLike::visit_decl (Ts... ts) const inline
Definition at line 208 of file vals.hpp.
The documentation for this struct was generated from the following file:
src/yume/compiler/vals.hpp