Yume: yume::Def Struct Reference
yume::Def Struct Reference
#include <vals.hpp>
Public Member Functions
template<typename R = void, typename... Ts>
auto visit_def (Ts... ts) -> decltype(auto)
template<typename R = void, typename... Ts>
auto visit_def (Ts... ts) const -> decltype(auto)
Detailed Description
Definition at line 39 of file vals.hpp.
Member Function Documentation
visit_def() [1/2]
template<typename R = void, typename... Ts> auto yume::Def::visit_def (Ts... ts) -> decltype(auto) inline
Definition at line 49 of file vals.hpp.
Referenced by yume::Fn::arg_count(), yume::Fn::arg_nodes(), yume::Fn::ast(), yume::Fn::extern_decl(), yume::Fn::extern_linkage(), yume::Fn::local(), yume::Fn::make_extern_linkage(), yume::Fn::name(), yume::Fn::primitive(), yume::Fn::ret(), and yume::Fn::varargs().
visit_def() [2/2]
template<typename R = void, typename... Ts> auto yume::Def::visit_def (Ts... ts) const -> decltype(auto) inline
Definition at line 52 of file vals.hpp.
The documentation for this struct was generated from the following file:
src/yume/compiler/vals.hpp