Yume: yume::Ctor Struct Reference
yume::Ctor Struct Reference
A constructor declaration in the compiler.
#include <vals.hpp>
Public Types
using decl_t = ast::CtorDecl
using call_t = ast::CtorExpr
Public Member Functions
Ctor (ast::CtorDecl &ast_decl, optional< ty::Type > type=std::nullopt, ast::Program *member=nullptr)
auto ast () const -> const auto &
auto ast () -> auto &
auto get_self_ty () const -> optional< ty::Type >
auto get_subs () const -> const Substitution &
auto get_subs () -> Substitution &
auto name () const -> string
Static Public Member Functions
static auto overload_name (const call_t &ast) -> string
static auto arg_type (const decl_t::arg_t &ast) -> optional< ty::Type >
static auto arg_name (const decl_t::arg_t &ast) -> string
static auto common_ast (const decl_t::arg_t &ast) -> const ast::AST &
Public Attributes
FnBase base
Detailed Description
A constructor declaration in the compiler.
Very similar to Fn, the primary use of this structure is to bind together the AST declaration of a struct (ast::CtorDecl) and the bytecode body of a function (llvm::Function).
Definition at line 121 of file vals.hpp.
Member Typedef Documentation
call_t
using yume::Ctor::call_t = ast::CtorExpr
Definition at line 123 of file vals.hpp.
decl_t
using yume::Ctor::decl_t = ast::CtorDecl
Definition at line 122 of file vals.hpp.
Constructor & Destructor Documentation
Ctor()
yume::Ctor::Ctor (ast::CtorDecl & ast_decl, optional< ty::Type > type = std::nullopt, ast::Program * member = nullptr) inline
Definition at line 127 of file vals.hpp.
Member Function Documentation
arg_name()
auto yume::Ctor::arg_name (const decl_t::arg_t & ast) -> string static
Definition at line 60 of file vals.cpp.
Referenced by yume::Compiler::declare().
arg_type()
auto yume::Ctor::arg_type (const decl_t::arg_t & ast) -> optional<ty::Type> static
Definition at line 50 of file vals.cpp.
Referenced by yume::Compiler::declare(), yume::semantic::TypeWalker::expression(), and yume::Compiler::mangle_name().
ast() [1/2]
auto yume::Ctor::ast () -> auto& inline
Definition at line 131 of file vals.hpp.
References yume::FnBase::ast, and yume::Fn::base.
ast() [2/2]
auto yume::Ctor::ast () const -> const auto& inline
Definition at line 130 of file vals.hpp.
References yume::FnBase::ast, and yume::Fn::base.
Referenced by yume::Compiler::define().
common_ast()
auto yume::Ctor::common_ast (const decl_t::arg_t & ast) -> const ast::AST& static
Definition at line 55 of file vals.cpp.
get_self_ty()
auto yume::Ctor::get_self_ty () const -> optional<ty::Type> inline
Definition at line 132 of file vals.hpp.
References yume::Fn::base, and yume::FnBase::self_ty.
Referenced by name().
get_subs() [1/2]
auto yume::Ctor::get_subs () -> Substitution& inline
Definition at line 134 of file vals.hpp.
References yume::Fn::base, and yume::FnBase::subs.
get_subs() [2/2]
auto yume::Ctor::get_subs () const -> const Substitution& inline
Definition at line 133 of file vals.hpp.
References yume::Fn::base, and yume::FnBase::subs.
name()
auto yume::Ctor::name () const -> string
Definition at line 43 of file vals.cpp.
References get_self_ty().
overload_name()
auto yume::Ctor::overload_name (const call_t & ast) -> string static
Definition at line 47 of file vals.cpp.
Member Data Documentation
base
FnBase yume::Ctor::base
Definition at line 125 of file vals.hpp.
Referenced by yume::Compiler::define().
The documentation for this struct was generated from the following files:
src/yume/compiler/vals.hpp
src/yume/compiler/vals.cpp