Yume: yume::ast::parser::Parser Struct Reference
yume::ast::parser::Parser Struct Reference
#include <parser.hpp>
Classes
struct FnArg
Public Member Functions
auto ts (const VectorTokenIterator &entry) const -> span< Token >
template<typename T , typename... Args>
auto ast_ptr (const VectorTokenIterator &entry, Args &&... args)
template<typename T , typename... Args>
auto ast_ptr (TokenRange &&range, Args &&... args)
template<typename T , typename... Args>
auto make_ast (const VectorTokenIterator &entry, Args &&... args)
auto make_guard (const string &message) const -> ParserStackTrace
auto ignore_separator (source_location location=source_location::current()) -> bool
Ignore any Separator tokens if any are present.
void expect (Token::Type token_type, source_location location=source_location::current()) const
If the next token doesn't have the type, token_type, throw a runtime exception.
void require_separator (source_location location=source_location::current())
Consume all subsequent Separator tokens. Throws if none were found.
void consume (TokenAtom token_atom, source_location location=source_location::current())
Consume a token of the given type and payload. Throws if it wasn't encountered.
auto try_consume (TokenAtom token_atom, source_location location=source_location::current()) -> bool
Attempt to consume a token of the given type and payload. Returns false if it wasn't encountered.
auto try_peek (int ahead, TokenAtom token_atom, source_location location=source_location::current()) const -> bool
Check if the token ahead by ahead is of the given type and payload.
auto try_peek (int ahead, Token::Type token_type, source_location location=source_location::current()) const -> bool
Check if the token ahead by ahead is of type token_type.
void consume_with_commas_until (TokenAtom token_atom, std::invocable auto action, const source_location location=source_location::current())
Consume tokens until a token of the given type and payload is encountered. action (a no-arg function) is called every time. Between each call, a comma is expected.
template<typename T , std::convertible_to< T > U>
void collect_with_commas_until (TokenAtom token_atom, U(Parser::*action)(), vector< T > &vec, const source_location location=source_location::current())
Consume tokens until a token of the given type and payload is encountered. action (a no-arg member function) is called every time and its result is appended to vec. Between each call, a comma is expected.
template<typename T , std::convertible_to< T > U>
auto collect_with_commas_until (TokenAtom token_atom, U(Parser::*action)(), const source_location location=source_location::current()) -> vector< T >
Consume tokens until a token of the given type and payload is encountered. action (a no-arg member function) is called every time. Between each call, a comma is expected. Returns a vector of all the results of calling action.
auto next (source_location location=source_location::current()) -> Token
Return the next token and increment the iterator.
auto assert_payload_next (source_location location=source_location::current()) -> Atom
Returns the payload of the next token and increment the iterator.
auto consume_word (source_location location=source_location::current()) -> string
Return the payload of the next token. Throws if the next token isn't a Word.
auto try_peek_uword (int ahead, source_location location=source_location::current()) const -> bool
Check if the ahead by ahead is a capitalized word.
auto parse_stmt (bool require_sep=true) -> unique_ptr< Stmt >
auto parse_expr () -> unique_ptr< Expr >
auto parse_fn_arg () -> FnArg
auto try_parse_function_type () -> optional< unique_ptr< FunctionType > >
auto try_parse_type () -> optional< unique_ptr< Type > >
auto parse_type (bool implicit_self=false) -> unique_ptr< Type >
auto parse_type_name () -> unique_ptr< TypeName >
auto parse_fn_name () -> string
auto parse_struct_decl () -> unique_ptr< StructDecl >
auto parse_fn_or_ctor_decl () -> unique_ptr< Stmt >
auto parse_fn_decl () -> unique_ptr< FnDecl >
auto parse_ctor_decl () -> unique_ptr< CtorDecl >
auto parse_var_decl () -> unique_ptr< VarDecl >
auto parse_const_decl () -> unique_ptr< ConstDecl >
auto parse_while_stmt () -> unique_ptr< WhileStmt >
auto parse_return_stmt () -> unique_ptr< ReturnStmt >
auto parse_if_stmt () -> unique_ptr< IfStmt >
auto parse_number_expr () -> unique_ptr< NumberExpr >
auto parse_string_expr () -> unique_ptr< StringExpr >
auto parse_char_expr () -> unique_ptr< CharExpr >
auto parse_primary () -> unique_ptr< Expr >
auto parse_receiver (unique_ptr< Expr > receiver, VectorTokenIterator receiver_entry) -> unique_ptr< Expr >
auto parse_receiver () -> unique_ptr< Expr >
auto parse_unary () -> unique_ptr< Expr >
auto parse_lambda () -> unique_ptr< LambdaExpr >
auto parse_logical_or () -> unique_ptr< Expr >
auto parse_logical_and () -> unique_ptr< Expr >
template<size_t N = 0>
auto parse_operator () -> unique_ptr< Expr >
Static Public Member Functions
template<typename T , typename U >
static auto ts (T &&begin, U &&end) -> span< Token >
static auto operators ()
static auto unary_operators ()
static auto to_string (Token token) -> string
static auto is_uword (string_view word) -> bool
Check if the string begins with a capital letter. Used for types, as all types must be capitalized.
Public Attributes
TokenIterator & tokens
Static Public Attributes
static constexpr auto Symbol = Token::Type::Symbol
static constexpr auto Word = Token::Type::Word
static constexpr auto Separator = Token::Type::Separator
static constexpr auto Number = Token::Type::Number
Detailed Description
Definition at line 140 of file parser.hpp.
Member Function Documentation
assert_payload_next()
auto yume::ast::parser::Parser::assert_payload_next (source_location location = source_location::current()) -> Atom
Returns the payload of the next token and increment the iterator.
Exceptions
if the next token has no payload
Definition at line 114 of file parser.cpp.
References yume::at().
ast_ptr() [1/2]
template<typename T , typename... Args> auto yume::ast::parser::Parser::ast_ptr (const VectorTokenIterator & entry, Args &&... args) inline
Definition at line 151 of file parser.hpp.
References yume::ast::TokenIterator::begin(), and tokens.
ast_ptr() [2/2]
template<typename T , typename... Args> auto yume::ast::parser::Parser::ast_ptr (TokenRange && range, Args &&... args) inline
Definition at line 155 of file parser.hpp.
collect_with_commas_until() [1/2]
template<typename T , std::convertible_to< T > U> auto yume::ast::parser::Parser::collect_with_commas_until (TokenAtom token_atom, U(Parser::*)() action, const source_location location = source_location::current()) -> vector<T> inline
Consume tokens until a token of the given type and payload is encountered. action (a no-arg member function) is called every time. Between each call, a comma is expected. Returns a vector of all the results of calling action.
Definition at line 250 of file parser.hpp.
References consume(), yume::ast::parser::SYM_COMMA, and try_consume().
collect_with_commas_until() [2/2]
template<typename T , std::convertible_to< T > U> void yume::ast::parser::Parser::collect_with_commas_until (TokenAtom token_atom, U(Parser::*)() action, vector< T > & vec, const source_location location = source_location::current()) inline
Consume tokens until a token of the given type and payload is encountered. action (a no-arg member function) is called every time and its result is appended to vec. Between each call, a comma is expected.
Definition at line 236 of file parser.hpp.
References consume(), yume::ast::parser::SYM_COMMA, and try_consume().
consume()
void yume::ast::parser::Parser::consume (TokenAtom token_atom, source_location location = source_location::current())
Consume a token of the given type and payload. Throws if it wasn't encountered.
Definition at line 42 of file parser.cpp.
References yume::at(), expect(), ignore_separator(), to_string(), and tokens.
Referenced by collect_with_commas_until(), and consume_with_commas_until().
consume_with_commas_until()
void yume::ast::parser::Parser::consume_with_commas_until (TokenAtom token_atom, std::invocable auto action, const source_location location = source_location::current()) inline
Consume tokens until a token of the given type and payload is encountered. action (a no-arg function) is called every time. Between each call, a comma is expected.
Definition at line 222 of file parser.hpp.
References consume(), yume::ast::parser::SYM_COMMA, and try_consume().
consume_word()
auto yume::ast::parser::Parser::consume_word (source_location location = source_location::current()) -> string
Return the payload of the next token. Throws if the next token isn't a Word.
Definition at line 123 of file parser.cpp.
References yume::at(), and yume::ast::parser::Word.
expect()
void yume::ast::parser::Parser::expect (Token::Type token_type, source_location location = source_location::current()) const
If the next token doesn't have the type, token_type, throw a runtime exception.
Definition at line 21 of file parser.cpp.
References yume::at(), yume::ast::TokenIterator::at_end(), to_string(), tokens, and yume::Token::type_name().
Referenced by consume(), and require_separator().
ignore_separator()
auto yume::ast::parser::Parser::ignore_separator (source_location location = source_location::current()) -> bool
Ignore any Separator tokens if any are present.
Returns
true if a separator was encountered (and consumed)
Definition at line 9 of file parser.cpp.
References yume::at().
Referenced by consume(), yume::ast::Program::parse(), and require_separator().
is_uword()
static auto yume::ast::parser::Parser::is_uword (string_view word) -> bool inline static
Check if the string begins with a capital letter. Used for types, as all types must be capitalized.
Definition at line 274 of file parser.hpp.
make_ast()
template<typename T , typename... Args> auto yume::ast::parser::Parser::make_ast (const VectorTokenIterator & entry, Args &&... args) inline
Definition at line 159 of file parser.hpp.
References yume::ast::TokenIterator::begin(), and tokens.
make_guard()
auto yume::ast::parser::Parser::make_guard (const string & message) const -> ParserStackTrace inline
Definition at line 173 of file parser.hpp.
References tokens.
next()
auto yume::ast::parser::Parser::next (source_location location = source_location::current()) -> Token
Return the next token and increment the iterator.
Definition at line 106 of file parser.cpp.
References yume::at().
operators()
static auto yume::ast::parser::Parser::operators () inline static
Definition at line 175 of file parser.hpp.
References yume::ast::parser::SYM_AND, yume::ast::parser::SYM_EQ_EQ, yume::ast::parser::SYM_GT, yume::ast::parser::SYM_LT, yume::ast::parser::SYM_MINUS, yume::ast::parser::SYM_NEQ, yume::ast::parser::SYM_PERCENT, yume::ast::parser::SYM_PLUS, yume::ast::parser::SYM_SLASH_SLASH, and yume::ast::parser::SYM_STAR.
Referenced by parse_operator().
parse_char_expr()
auto yume::ast::parser::Parser::parse_char_expr () -> unique_ptr<CharExpr>
Definition at line 654 of file parser.cpp.
References yume::Token::Char.
parse_const_decl()
auto yume::ast::parser::Parser::parse_const_decl () -> unique_ptr<ConstDecl>
Definition at line 532 of file parser.cpp.
References yume::ast::parser::KWD_CONST, and yume::ast::parser::SYM_EQ.
parse_ctor_decl()
auto yume::ast::parser::Parser::parse_ctor_decl () -> unique_ptr<CtorDecl>
Definition at line 488 of file parser.cpp.
References yume::ast::parser::KWD_DEF, yume::ast::parser::KWD_END, yume::ast::parser::KWD_NEW, yume::ast::parser::SYM_COLON, yume::ast::parser::SYM_LPAREN, and yume::ast::parser::SYM_RPAREN.
parse_expr()
auto yume::ast::parser::Parser::parse_expr () -> unique_ptr<Expr>
Definition at line 312 of file parser.cpp.
Referenced by parse_primary(), and parse_receiver().
parse_fn_arg()
auto yume::ast::parser::Parser::parse_fn_arg () -> FnArg
Definition at line 385 of file parser.cpp.
References yume::ast::parser::SYM_COLON_COLON.
parse_fn_decl()
auto yume::ast::parser::Parser::parse_fn_decl () -> unique_ptr<FnDecl>
Definition at line 408 of file parser.cpp.
References yume::ast::parser::KWD_ABSTRACT, yume::ast::parser::KWD_DEF, yume::ast::parser::KWD_END, yume::ast::parser::KWD_EXTERN, yume::ast::parser::KWD_PRIMITIVE, yume::ast::parser::KWD_VARARGS, yume::ast::parser::SYM_AT, yume::ast::parser::SYM_EQ, yume::ast::parser::SYM_LBRACE, yume::ast::parser::SYM_LPAREN, yume::ast::parser::SYM_RBRACE, and yume::ast::parser::SYM_RPAREN.
parse_fn_name()
auto yume::ast::parser::Parser::parse_fn_name () -> string
Definition at line 314 of file parser.cpp.
References yume::ast::parser::SYM_BANG, yume::ast::parser::SYM_EQ, yume::ast::parser::SYM_LBRACKET, yume::ast::parser::SYM_RBRACKET, yume::ast::parser::Symbol, and yume::ast::parser::Word.
parse_fn_or_ctor_decl()
auto yume::ast::parser::Parser::parse_fn_or_ctor_decl () -> unique_ptr<Stmt>
Definition at line 402 of file parser.cpp.
References yume::ast::parser::SYM_COLON.
parse_if_stmt()
auto yume::ast::parser::Parser::parse_if_stmt () -> unique_ptr<IfStmt>
Definition at line 578 of file parser.cpp.
References yume::ast::parser::KWD_ELSE, yume::ast::parser::KWD_END, yume::ast::parser::KWD_IF, and yume::ast::parser::KWD_THEN.
parse_lambda()
auto yume::ast::parser::Parser::parse_lambda () -> unique_ptr<LambdaExpr>
Definition at line 785 of file parser.cpp.
References yume::ast::parser::KWD_DEF, yume::ast::parser::KWD_END, yume::ast::parser::SYM_AT, yume::ast::parser::SYM_EQ, yume::ast::parser::SYM_LPAREN, and yume::ast::parser::SYM_RPAREN.
parse_logical_and()
auto yume::ast::parser::Parser::parse_logical_and () -> unique_ptr<Expr>
Definition at line 302 of file parser.cpp.
References yume::ast::parser::SYM_AND_AND.
parse_logical_or()
auto yume::ast::parser::Parser::parse_logical_or () -> unique_ptr<Expr>
Definition at line 292 of file parser.cpp.
References yume::ast::parser::SYM_OR_OR.
parse_number_expr()
auto yume::ast::parser::Parser::parse_number_expr () -> unique_ptr<NumberExpr>
Definition at line 633 of file parser.cpp.
parse_operator()
template<size_t N = 0> auto yume::ast::parser::Parser::parse_operator () -> unique_ptr<Expr> inline
Definition at line 327 of file parser.hpp.
References yume::ast::TokenIterator::begin(), operators(), parse_unary(), tokens, and try_consume().
parse_primary()
auto yume::ast::parser::Parser::parse_primary () -> unique_ptr<Expr>
Definition at line 663 of file parser.cpp.
References yume::Token::Char, yume::ast::parser::KWD_FALSE, yume::ast::parser::KWD_TRUE, yume::Token::Literal, parse_expr(), yume::ast::parser::SYM_COLON, yume::ast::parser::SYM_COLON_COLON, yume::ast::parser::SYM_DOLLAR, yume::ast::parser::SYM_DOT, yume::ast::parser::SYM_LBRACKET, yume::ast::parser::SYM_LPAREN, yume::ast::parser::SYM_RBRACKET, yume::ast::parser::SYM_RPAREN, and yume::ast::parser::Word.
parse_receiver() [1/2]
auto yume::ast::parser::Parser::parse_receiver () -> unique_ptr<Expr>
Definition at line 825 of file parser.cpp.
References yume::ast::parser::KWD_DEF.
parse_receiver() [2/2]
auto yume::ast::parser::Parser::parse_receiver (unique_ptr< Expr > receiver, VectorTokenIterator receiver_entry) -> unique_ptr<Expr>
Definition at line 730 of file parser.cpp.
References parse_expr(), yume::ast::parser::SYM_ARROW, yume::ast::parser::SYM_COLON_COLON, yume::ast::parser::SYM_DOT, yume::ast::parser::SYM_EQ, yume::ast::parser::SYM_LBRACKET, yume::ast::parser::SYM_LPAREN, yume::ast::parser::SYM_RBRACKET, and yume::ast::parser::SYM_RPAREN.
parse_return_stmt()
auto yume::ast::parser::Parser::parse_return_stmt () -> unique_ptr<ReturnStmt>
Definition at line 566 of file parser.cpp.
References yume::ast::parser::KWD_RETURN.
parse_stmt()
auto yume::ast::parser::Parser::parse_stmt (bool require_sep = true) -> unique_ptr<Stmt>
Definition at line 144 of file parser.cpp.
References yume::ast::parser::KWD_CONST, yume::ast::parser::KWD_DEF, yume::ast::parser::KWD_IF, yume::ast::parser::KWD_INTERFACE, yume::ast::parser::KWD_LET, yume::ast::parser::KWD_RETURN, yume::ast::parser::KWD_STRUCT, and yume::ast::parser::KWD_WHILE.
parse_string_expr()
auto yume::ast::parser::Parser::parse_string_expr () -> unique_ptr<StringExpr>
Definition at line 645 of file parser.cpp.
References yume::Token::Literal.
parse_struct_decl()
auto yume::ast::parser::Parser::parse_struct_decl () -> unique_ptr<StructDecl>
Definition at line 349 of file parser.cpp.
References yume::ast::parser::KWD_END, yume::ast::parser::KWD_IS, yume::ast::parser::KWD_STRUCT, yume::ast::parser::SYM_LBRACE, yume::ast::parser::SYM_LPAREN, yume::ast::parser::SYM_RBRACE, and yume::ast::parser::SYM_RPAREN.
parse_type()
auto yume::ast::parser::Parser::parse_type (bool implicit_self = false) -> unique_ptr<Type>
Definition at line 182 of file parser.cpp.
References yume::ast::parser::KWD_MUT, yume::ast::parser::KWD_PTR, yume::ast::parser::KWD_REF, yume::ast::parser::KWD_SELF_TYPE, yume::ast::parser::KWD_TYPE, yume::Mut, yume::Ptr, yume::Ref, yume::ast::parser::SYM_LBRACE, yume::ast::parser::SYM_LBRACKET, yume::ast::parser::SYM_RBRACE, yume::ast::parser::SYM_RBRACKET, and yume::Type.
parse_type_name()
auto yume::ast::parser::Parser::parse_type_name () -> unique_ptr<TypeName>
Definition at line 281 of file parser.cpp.
References yume::ast::parser::KWD_SELF_ITEM.
parse_unary()
auto yume::ast::parser::Parser::parse_unary () -> unique_ptr<Expr>
Definition at line 833 of file parser.cpp.
Referenced by parse_operator().
parse_var_decl()
auto yume::ast::parser::Parser::parse_var_decl () -> unique_ptr<VarDecl>
Definition at line 518 of file parser.cpp.
References yume::ast::parser::KWD_LET, and yume::ast::parser::SYM_EQ.
parse_while_stmt()
auto yume::ast::parser::Parser::parse_while_stmt () -> unique_ptr<WhileStmt>
Definition at line 546 of file parser.cpp.
References yume::ast::parser::KWD_END, and yume::ast::parser::KWD_WHILE.
require_separator()
void yume::ast::parser::Parser::require_separator (source_location location = source_location::current())
Consume all subsequent Separator tokens. Throws if none were found.
Definition at line 30 of file parser.cpp.
References yume::ast::TokenIterator::at_end(), expect(), ignore_separator(), Separator, and tokens.
to_string()
auto yume::ast::parser::Parser::to_string (Token token) -> string static
Definition at line 36 of file parser.cpp.
Referenced by consume(), and expect().
try_consume()
auto yume::ast::parser::Parser::try_consume (TokenAtom token_atom, source_location location = source_location::current()) -> bool
Attempt to consume a token of the given type and payload. Returns false if it wasn't encountered.
Definition at line 58 of file parser.cpp.
References yume::at().
Referenced by collect_with_commas_until(), consume_with_commas_until(), and parse_operator().
try_parse_function_type()
auto yume::ast::parser::Parser::try_parse_function_type () -> optional<unique_ptr<FunctionType>>
Definition at line 169 of file parser.cpp.
References yume::ast::parser::KWD_PTR, yume::ast::parser::SYM_ARROW, yume::ast::parser::SYM_LPAREN, and yume::ast::parser::SYM_RPAREN.
try_parse_type()
auto yume::ast::parser::Parser::try_parse_type () -> optional<unique_ptr<Type>>
Definition at line 229 of file parser.cpp.
References yume::ast::parser::KWD_MUT, yume::ast::parser::KWD_PTR, yume::ast::parser::KWD_REF, yume::ast::parser::KWD_SELF_TYPE, yume::ast::parser::KWD_TYPE, yume::make_atom(), yume::Mut, yume::Ptr, yume::Ref, yume::ast::parser::SYM_LBRACE, yume::ast::parser::SYM_LBRACKET, yume::ast::parser::SYM_RBRACE, yume::ast::parser::SYM_RBRACKET, yume::Type, and yume::ast::parser::Word.
try_peek() [1/2]
auto yume::ast::parser::Parser::try_peek (int ahead, Token::Type token_type, source_location location = source_location::current()) const -> bool
Check if the token ahead by ahead is of type token_type.
Definition at line 89 of file parser.cpp.
References yume::at(), and yume::Token::type_name().
try_peek() [2/2]
auto yume::ast::parser::Parser::try_peek (int ahead, TokenAtom token_atom, source_location location = source_location::current()) const -> bool
Check if the token ahead by ahead is of the given type and payload.
Definition at line 72 of file parser.cpp.
References yume::at(), and yume::Token::type_name().
try_peek_uword()
auto yume::ast::parser::Parser::try_peek_uword (int ahead, source_location location = source_location::current()) const -> bool
Check if the ahead by ahead is a capitalized word.
Definition at line 133 of file parser.cpp.
References yume::at(), and yume::ast::parser::Word.
ts() [1/2]
auto yume::ast::parser::Parser::ts (const VectorTokenIterator & entry) const -> span<Token> inline
Definition at line 147 of file parser.hpp.
References yume::ast::TokenIterator::begin(), and tokens.
ts() [2/2]
template<typename T , typename U > static auto yume::ast::parser::Parser::ts (T && begin, U && end) -> span<Token> inline static
Definition at line 143 of file parser.hpp.
References end.
unary_operators()
static auto yume::ast::parser::Parser::unary_operators () inline static
Definition at line 185 of file parser.hpp.
References yume::ast::parser::SYM_BANG, yume::ast::parser::SYM_MINUS, and yume::ast::parser::SYM_PLUS.
Member Data Documentation
Number
constexpr auto yume::ast::parser::Parser::Number = Token::Type::Number static constexpr
Definition at line 171 of file parser.hpp.
Separator
constexpr auto yume::ast::parser::Parser::Separator = Token::Type::Separator static constexpr
Definition at line 170 of file parser.hpp.
Referenced by require_separator().
Symbol
constexpr auto yume::ast::parser::Parser::Symbol = Token::Type::Symbol static constexpr
Definition at line 168 of file parser.hpp.
tokens
TokenIterator& yume::ast::parser::Parser::tokens
Definition at line 141 of file parser.hpp.
Referenced by ast_ptr(), consume(), expect(), make_ast(), make_guard(), parse_operator(), require_separator(), and ts().
Word
constexpr auto yume::ast::parser::Parser::Word = Token::Type::Word static constexpr
Definition at line 169 of file parser.hpp.
The documentation for this struct was generated from the following files:
src/yume/ast/parser.hpp
src/yume/ast/parser.cpp