Yume: yume::diagnostic::Note Struct Reference
yume::diagnostic::Note Struct Reference
#include <notes.hpp>
Public Member Functions
Note (NotesHolder *holder, string message, Loc location, Severity severity=Severity::Note)
Note (const Note &)=delete
Note (Note &&)=default
auto operator= (const Note &) -> Note &=delete
auto operator= (Note &&) -> Note &=default
~Note () noexcept(false)
void emit () const
auto operator<< (auto &&other) -> Note &
Public Attributes
NotesHolder * holder
string message
Loc location
Severity severity
Detailed Description
Definition at line 19 of file notes.hpp.
Constructor & Destructor Documentation
Note() [1/3]
yume::diagnostic::Note::Note (NotesHolder * holder, string message, Loc location, Severity severity = Severity::Note) inline
Definition at line 26 of file notes.hpp.
Note() [2/3]
yume::diagnostic::Note::Note (const Note &) delete
Note() [3/3]
yume::diagnostic::Note::Note (Note &&) default
~Note()
yume::diagnostic::Note::~Note () inline noexcept
Definition at line 34 of file notes.hpp.
References emit(), yume::diagnostic::Fatal, and message.
Member Function Documentation
emit()
void yume::diagnostic::Note::emit () const
Definition at line 11 of file notes.cpp.
References yume::Loc::begin_col, yume::Loc::begin_line, yume::diagnostic::NotesHolder::context_files, yume::diagnostic::Error, yume::diagnostic::Fatal, holder, location, message, yume::diagnostic::Note, yume::diagnostic::NotesHolder::prev_loc, severity, yume::Loc::single(), yume::diagnostic::NotesHolder::stream, yume::Loc::valid(), and yume::diagnostic::Warn.
Referenced by ~Note().
operator<<()
auto yume::diagnostic::Note::operator<< (auto && other) -> Note& inline
Definition at line 43 of file notes.hpp.
operator=() [1/2]
auto yume::diagnostic::Note::operator= (const Note &) -> Note &=delete delete
operator=() [2/2]
auto yume::diagnostic::Note::operator= (Note &&) -> Note &=default default
Member Data Documentation
holder
NotesHolder* yume::diagnostic::Note::holder
Definition at line 21 of file notes.hpp.
Referenced by emit().
location
Loc yume::diagnostic::Note::location
Definition at line 23 of file notes.hpp.
Referenced by emit().
message
string yume::diagnostic::Note::message
Definition at line 22 of file notes.hpp.
Referenced by emit(), and ~Note().
severity
Severity yume::diagnostic::Note::severity
Definition at line 24 of file notes.hpp.
Referenced by emit().
The documentation for this struct was generated from the following files:
src/yume/diagnostic/notes.hpp
src/yume/diagnostic/notes.cpp