Yume: yume::semantic::TypeWalker Struct Reference
yume::semantic::TypeWalker Struct Reference
Determine the type information of AST nodes. This makes up most of the "semantic" phase of the compiler.
#include <type_walker.hpp>
Classes
struct ASTWithName
Public Types
using scope_t = ScopeContainer< nonnull< ast::AST * > >
Public Member Functions
TypeWalker (Compiler &compiler)
void body_statement (ast::Stmt &)
void body_expression (ast::Expr &)
void resolve_queue ()
auto make_dup (ast::AnyExpr &expr) -> Fn *
template<>
void expression (ast::NumberExpr &expr)
template<>
void expression (ast::StringExpr &expr)
template<>
void expression (ast::CharExpr &expr)
template<>
void expression (ast::BoolExpr &expr)
template<>
void expression (ast::Type &expr)
template<>
void expression (ast::TypeName &expr)
template<>
void expression (ast::ImplicitCastExpr &expr)
template<>
void expression (ast::CtorExpr &expr)
template<>
void expression (ast::SliceExpr &expr)
template<>
void expression (ast::LambdaExpr &expr)
template<>
void expression (ast::AssignExpr &expr)
template<>
void expression (ast::VarExpr &expr)
template<>
void expression (ast::ConstExpr &expr)
template<>
void expression (ast::FieldAccessExpr &expr)
template<>
void expression (ast::CallExpr &expr)
template<>
void expression (ast::BinaryLogicExpr &expr)
template<>
void statement (ast::Compound &stat)
template<>
void statement (ast::StructDecl &stat)
template<>
void statement (ast::FnDecl &stat)
template<>
void statement (ast::CtorDecl &stat)
template<>
void statement (ast::ReturnStmt &stat)
template<>
void statement (ast::VarDecl &stat)
template<>
void statement (ast::ConstDecl &stat)
template<>
void statement (ast::IfStmt &stat)
template<>
void statement (ast::WhileStmt &stat)
Public Member Functions inherited from yume::CRTPWalker< TypeWalker >
auto body_statement (ast::Stmt &stat, auto &&... args)
auto body_expression (ast::Expr &expr, auto &&... args)
Public Attributes
friend CRTPWalker
Compiler & compiler
DeclLike current_decl {}
scope_t scope {}
vector< scope_t > enclosing_scopes {}
vector< ASTWithName > closured {}
std::queue< DeclLike > decl_queue {}
bool in_depth = false
Whether or not to compile the bodies of methods. Initially, on the parameter types of methods are traversed and converted, then everything else in a second pass.
Detailed Description
Determine the type information of AST nodes. This makes up most of the "semantic" phase of the compiler.
Definition at line 32 of file type_walker.hpp.
Member Typedef Documentation
scope_t
using yume::semantic::TypeWalker::scope_t = ScopeContainer<nonnull<ast::AST*> >
Definition at line 43 of file type_walker.hpp.
Constructor & Destructor Documentation
TypeWalker()
yume::semantic::TypeWalker::TypeWalker (Compiler & compiler) inline explicit
Definition at line 54 of file type_walker.hpp.
Member Function Documentation
body_expression()
void yume::semantic::TypeWalker::body_expression (ast::Expr & expr)
Definition at line 662 of file type_walker.cpp.
References yume::CRTPWalker< Derived >::body_expression(), and yume::ast::AST::kind_name().
Referenced by expression(), and statement().
body_statement()
void yume::semantic::TypeWalker::body_statement (ast::Stmt & stat)
Definition at line 658 of file type_walker.cpp.
References yume::CRTPWalker< Derived >::body_statement(), and yume::ast::AST::kind_name().
Referenced by expression(), and statement().
expression() [1/16]
template<> void yume::semantic::TypeWalker::expression (ast::AssignExpr & expr)
Definition at line 297 of file type_walker.cpp.
References yume::ast::AST::attach_to(), body_expression(), yume::semantic::make_implicit_conversion(), yume::ast::AnyBase< T >::raw_ptr(), yume::ast::AssignExpr::target, and yume::ast::AssignExpr::value.
expression() [2/16]
template<> void yume::semantic::TypeWalker::expression (ast::BinaryLogicExpr & expr)
Definition at line 515 of file type_walker.cpp.
References body_expression(), yume::TypeHolder::bool_type, compiler, yume::ast::BinaryLogicExpr::lhs, yume::ast::BinaryLogicExpr::rhs, yume::ast::AST::val_ty(), and yume::yume_assert().
expression() [3/16]
template<> void yume::semantic::TypeWalker::expression (ast::BoolExpr & expr)
Definition at line 77 of file type_walker.cpp.
References yume::TypeHolder::bool_type, compiler, and yume::ast::AST::val_ty().
expression() [4/16]
template<> void yume::semantic::TypeWalker::expression (ast::CallExpr & expr)
Definition at line 408 of file type_walker.cpp.
References yume::ast::CallExpr::args, yume::ast::AST::attach_to(), body_expression(), body_statement(), yume::semantic::Overload::compatibilities, current_decl, decl_queue, yume::semantic::Overload::dump(), yume::semantic::Overload::fn, yume::Fn::get_or_create_instantiation(), yume::ast::OptionalAnyBase< T >::has_value(), in_depth, yume::ast::CallExpr::name, yume::ast::CallExpr::receiver, resolve_queue(), yume::ast::CallExpr::selected_overload, yume::semantic::Overload::subs, yume::semantic::wrap_in_implicit_cast(), and yume::yume_assert().
expression() [5/16]
template<> void yume::semantic::TypeWalker::expression (ast::CharExpr & expr)
Definition at line 75 of file type_walker.cpp.
References compiler, yume::TypeHolder::int8(), and yume::ast::AST::val_ty().
expression() [6/16]
template<> void yume::semantic::TypeWalker::expression (ast::ConstExpr & expr)
Definition at line 325 of file type_walker.cpp.
References compiler, yume::ast::ConstExpr::name, and yume::ast::AST::val_ty().
expression() [7/16]
template<> void yume::semantic::TypeWalker::expression (ast::CtorExpr & expr)
Definition at line 101 of file type_walker.cpp.
References yume::ast::CtorExpr::args, body_expression(), compiler, yume::semantic::for_all_instantiations(), resolve_queue(), yume::ast::CtorExpr::selected_overload, yume::ast::CtorExpr::type, yume::ast::AST::val_ty(), yume::semantic::wrap_in_implicit_cast(), and yume::yume_assert().
expression() [8/16]
template<> void yume::semantic::TypeWalker::expression (ast::FieldAccessExpr & expr)
Definition at line 359 of file type_walker.cpp.
References yume::ast::FieldAccessExpr::base, body_expression(), current_decl, yume::ast::FieldAccessExpr::field, yume::semantic::find_field(), yume::ast::OptionalAnyBase< T >::has_value(), yume::ast::FieldAccessExpr::offset, yume::DeclLike::self_ty(), and yume::ast::AST::val_ty().
expression() [9/16]
template<> void yume::semantic::TypeWalker::expression (ast::ImplicitCastExpr & expr)
Definition at line 91 of file type_walker.cpp.
References yume::ast::ImplicitCastExpr::base, and body_expression().
expression() [10/16]
template<> void yume::semantic::TypeWalker::expression (ast::LambdaExpr & expr)
Definition at line 241 of file type_walker.cpp.
References yume::ast::LambdaExpr::args, yume::ast::LambdaExpr::body, body_statement(), yume::ScopeContainer< T >::clear(), closured, yume::ast::LambdaExpr::closured_names, yume::ast::LambdaExpr::closured_nodes, compiler, enclosing_scopes, yume::TypeHolder::find_or_create_fn_type(), yume::ast::OptionalAnyBase< T >::has_value(), yume::ScopeContainer< T >::push_scope_guarded(), yume::ast::LambdaExpr::ret, scope, and yume::ast::AST::val_ty().
expression() [11/16]
template<> void yume::semantic::TypeWalker::expression (ast::NumberExpr & expr)
Definition at line 62 of file type_walker.cpp.
References compiler, yume::TypeHolder::int32(), yume::TypeHolder::int64(), yume::ast::NumberExpr::val, and yume::ast::AST::val_ty().
expression() [12/16]
template<> void yume::semantic::TypeWalker::expression (ast::SliceExpr & expr)
Definition at line 228 of file type_walker.cpp.
References yume::ast::SliceExpr::args, body_expression(), yume::ast::SliceExpr::type, and yume::ast::AST::val_ty().
expression() [13/16]
template<> void yume::semantic::TypeWalker::expression (ast::StringExpr & expr)
Definition at line 70 of file type_walker.cpp.
References compiler, yume::TypeHolder::int8(), and yume::ast::AST::val_ty().
expression() [14/16]
template<> void yume::semantic::TypeWalker::expression (ast::Type & expr)
Definition at line 79 of file type_walker.cpp.
References yume::ast::AST::val_ty().
expression() [15/16]
template<> void yume::semantic::TypeWalker::expression (ast::TypeName & expr)
Definition at line 85 of file type_walker.cpp.
References yume::ast::AST::attach_to(), and yume::ast::TypeName::type.
expression() [16/16]
template<> void yume::semantic::TypeWalker::expression (ast::VarExpr & expr)
Definition at line 307 of file type_walker.cpp.
References yume::ScopeContainer< T >::add_to_front(), yume::ast::AST::attach_to(), closured, enclosing_scopes, yume::ScopeContainer< T >::find(), yume::ast::VarExpr::name, and scope.
make_dup()
auto yume::semantic::TypeWalker::make_dup (ast::AnyExpr & expr) -> Fn*
Definition at line 166 of file type_walker.cpp.
References yume::semantic::for_all_instantiations(), yume::Struct::name(), yume::semantic::wrap_in_implicit_cast(), and yume::yume_assert().
resolve_queue()
void yume::semantic::TypeWalker::resolve_queue ()
Definition at line 756 of file type_walker.cpp.
References compiler, decl_queue, yume::Compiler::decl_statement(), yume::Compiler::declare(), and in_depth.
Referenced by expression().
statement() [1/9]
template<> void yume::semantic::TypeWalker::statement (ast::Compound & stat)
Definition at line 525 of file type_walker.cpp.
References body_statement(), yume::ScopeContainer< T >::push_scope_guarded(), and scope.
statement() [2/9]
template<> void yume::semantic::TypeWalker::statement (ast::ConstDecl & stat)
Definition at line 632 of file type_walker.cpp.
References body_expression(), in_depth, yume::ast::ConstDecl::init, yume::semantic::make_implicit_conversion(), yume::ast::AnyBase< T >::raw_ptr(), yume::ast::ConstDecl::type, and yume::ast::AST::val_ty().
statement() [3/9]
template<> void yume::semantic::TypeWalker::statement (ast::CtorDecl & stat)
Definition at line 574 of file type_walker.cpp.
References yume::ScopeContainer< T >::add(), yume::ast::CtorDecl::args, yume::ast::CtorDecl::body, yume::ScopeContainer< T >::clear(), compiler, current_decl, yume::TypeHolder::find_or_create_fn_ptr_type(), in_depth, yume::ScopeContainer< T >::push_scope_guarded(), scope, yume::DeclLike::self_ty(), yume::ScopeContainer< T >::size(), yume::ast::AST::val_ty(), and yume::yume_assert().
statement() [4/9]
template<> void yume::semantic::TypeWalker::statement (ast::FnDecl & stat)
Definition at line 543 of file type_walker.cpp.
References yume::ScopeContainer< T >::add(), yume::any_of, yume::ast::FnDecl::args, yume::ast::AST::attach_to(), yume::ast::FnDecl::body, yume::ScopeContainer< T >::clear(), compiler, current_decl, yume::TypeHolder::find_or_create_fn_ptr_type(), yume::ast::OptionalAnyBase< T >::has_value(), in_depth, yume::ScopeContainer< T >::push_scope_guarded(), yume::ast::OptionalAnyBase< T >::raw_ptr(), yume::ast::FnDecl::ret, scope, yume::ScopeContainer< T >::size(), yume::DeclLike::subs(), yume::ast::FnDecl::varargs, and yume::yume_assert().
statement() [5/9]
template<> void yume::semantic::TypeWalker::statement (ast::IfStmt & stat)
Definition at line 643 of file type_walker.cpp.
References body_expression(), yume::ast::IfStmt::clauses, and yume::ast::IfStmt::else_clause.
statement() [6/9]
template<> void yume::semantic::TypeWalker::statement (ast::ReturnStmt & stat)
Definition at line 604 of file type_walker.cpp.
References yume::DeclLike::ast(), body_expression(), current_decl, yume::ast::ReturnStmt::expr, yume::ast::ReturnStmt::extends_lifetime, yume::ScopeContainer< T >::find(), yume::ast::OptionalAnyBase< T >::has_value(), yume::semantic::make_implicit_conversion(), yume::ast::OptionalAnyBase< T >::raw_ptr(), and scope.
statement() [7/9]
template<> void yume::semantic::TypeWalker::statement (ast::StructDecl & stat)
Definition at line 531 of file type_walker.cpp.
References yume::any_of, current_decl, yume::ast::StructDecl::fields, yume::ast::StructDecl::implements, and yume::DeclLike::subs().
statement() [8/9]
template<> void yume::semantic::TypeWalker::statement (ast::VarDecl & stat)
Definition at line 620 of file type_walker.cpp.
References yume::ScopeContainer< T >::add(), body_expression(), yume::ast::OptionalAnyBase< T >::has_value(), yume::ast::VarDecl::init, yume::semantic::make_implicit_conversion(), yume::ast::VarDecl::name, yume::ast::OptionalAnyBase< T >::raw_ptr(), scope, yume::ast::VarDecl::type, and yume::ast::AST::val_ty().
statement() [9/9]
template<> void yume::semantic::TypeWalker::statement (ast::WhileStmt & stat)
Definition at line 653 of file type_walker.cpp.
References yume::ast::WhileStmt::body, body_expression(), and yume::ast::WhileStmt::cond.
Member Data Documentation
closured
vector<ASTWithName> yume::semantic::TypeWalker::closured {}
Definition at line 46 of file type_walker.hpp.
Referenced by expression().
compiler
Compiler& yume::semantic::TypeWalker::compiler
Definition at line 41 of file type_walker.hpp.
Referenced by expression(), resolve_queue(), and statement().
CRTPWalker
friend yume::semantic::TypeWalker::CRTPWalker
Definition at line 33 of file type_walker.hpp.
current_decl
DeclLike yume::semantic::TypeWalker::current_decl {}
Definition at line 42 of file type_walker.hpp.
Referenced by expression(), and statement().
decl_queue
std::queue<DeclLike> yume::semantic::TypeWalker::decl_queue {}
Definition at line 48 of file type_walker.hpp.
Referenced by expression(), and resolve_queue().
enclosing_scopes
vector<scope_t> yume::semantic::TypeWalker::enclosing_scopes {}
Definition at line 45 of file type_walker.hpp.
Referenced by expression().
in_depth
bool yume::semantic::TypeWalker::in_depth = false
Whether or not to compile the bodies of methods. Initially, on the parameter types of methods are traversed and converted, then everything else in a second pass.
Definition at line 52 of file type_walker.hpp.
Referenced by expression(), resolve_queue(), and statement().
scope
scope_t yume::semantic::TypeWalker::scope {}
Definition at line 44 of file type_walker.hpp.
Referenced by expression(), and statement().
The documentation for this struct was generated from the following files:
src/yume/semantic/type_walker.hpp
src/yume/semantic/type_walker.cpp