Yume: yume::ast::TemplatedType Struct Reference
yume::ast::TemplatedType Struct Reference final
A type with explicit type parameters i.e. Foo<Bar,Baz>.
#include <ast.hpp>
Public Member Functions
TemplatedType (span< Token > tok, AnyType base, vector< AnyType > type_args)
void visit (Visitor &visitor) const override
Recursively visit this ast node and all its constituents.
auto describe () const -> string override
A short, string representation for debugging.
auto clone () const -> TemplatedType *override
Deep copy, except for the type and attachments.
auto clone () const -> Type *override=0
Deep copy, except for the type and attachments.
Public Member Functions inherited from yume::ast::AST
AST (const AST &)=delete
AST (AST &&)=default
auto operator= (const AST &) -> AST &=delete
auto operator= (AST &&) -> AST &=delete
virtual ~AST ()=default
virtual void visit (Visitor &visitor) const =0
Recursively visit this ast node and all its constituents.
auto val_ty () const noexcept -> optional< ty::Type >
auto ensure_ty () const -> ty::Type
void val_ty (optional< ty::Type > type)
void attach_to (nonnull< AST * > other)
Make the type of this node depend on the type of other.
auto kind () const -> Kind
auto kind_name () const -> string
Human-readable string representation of the Kind of this node.
auto token_range () const -> const span< Token > &
auto location () const -> Loc
The union of the locations of the Tokens making up this node.
virtual auto describe () const -> string
A short, string representation for debugging.
virtual auto clone () const -> AST *=0
Deep copy, except for the type and attachments.
Public Attributes
AnyType base
vector< AnyType > type_args
Additional Inherited Members
Protected Member Functions inherited from yume::ast::Type
AST (Kind kind, span< Token > tok)
AST (const AST &)=delete
AST (AST &&)=default
Protected Member Functions inherited from yume::ast::AST
void unify_val_ty ()
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
auto tok () const noexcept -> span< Token >
AST (Kind kind, span< Token > tok)
Detailed Description
A type with explicit type parameters i.e. Foo<Bar,Baz>.
Definition at line 352 of file ast.hpp.
Constructor & Destructor Documentation
TemplatedType()
yume::ast::TemplatedType::TemplatedType (span< Token > tok, AnyType base, vector< AnyType > type_args) inline
Definition at line 357 of file ast.hpp.
Referenced by clone().
Member Function Documentation
clone()
auto yume::ast::TemplatedType::clone () const -> TemplatedType *override override virtual
Deep copy, except for the type and attachments.
Implements yume::ast::Type.
Definition at line 102 of file ast.cpp.
References base, TemplatedType(), yume::ast::AST::tok(), and type_args.
describe()
auto yume::ast::TemplatedType::describe () const -> string override virtual
A short, string representation for debugging.
Reimplemented from yume::ast::AST.
Definition at line 20 of file describe.cpp.
References type_args.
visit()
void yume::ast::TemplatedType::visit (Visitor & visitor) const override virtual
Recursively visit this ast node and all its constituents.
See also
Visitor
Implements yume::ast::AST.
Definition at line 106 of file visit.cpp.
References base, type_args, and visitor.
Member Data Documentation
base
AnyType yume::ast::TemplatedType::base
Definition at line 354 of file ast.hpp.
Referenced by clone(), and visit().
type_args
vector<AnyType> yume::ast::TemplatedType::type_args
Definition at line 355 of file ast.hpp.
Referenced by clone(), describe(), and visit().
The documentation for this struct was generated from the following files:
src/yume/ast/ast.hpp
src/yume/ast/ast.cpp
src/yume/ast/describe.cpp
src/yume/ast/visit.cpp