Yume: yume::ast::ProxyType Struct Reference
yume::ast::ProxyType Struct Reference final
A type which refers to a different type, specifically that of a struct field.
#include <ast.hpp>
Public Member Functions
ProxyType (span< Token > tok, string field)
void visit (Visitor &visitor) const override
Recursively visit this ast node and all its constituents.
auto describe () const -> string override
A short, string representation for debugging.
auto clone () const -> ProxyType *override
Deep copy, except for the type and attachments.
auto clone () const -> Type *override=0
Deep copy, except for the type and attachments.
Public Member Functions inherited from yume::ast::AST
AST (const AST &)=delete
AST (AST &&)=default
auto operator= (const AST &) -> AST &=delete
auto operator= (AST &&) -> AST &=delete
virtual ~AST ()=default
virtual void visit (Visitor &visitor) const =0
Recursively visit this ast node and all its constituents.
auto val_ty () const noexcept -> optional< ty::Type >
auto ensure_ty () const -> ty::Type
void val_ty (optional< ty::Type > type)
void attach_to (nonnull< AST * > other)
Make the type of this node depend on the type of other.
auto kind () const -> Kind
auto kind_name () const -> string
Human-readable string representation of the Kind of this node.
auto token_range () const -> const span< Token > &
auto location () const -> Loc
The union of the locations of the Tokens making up this node.
virtual auto describe () const -> string
A short, string representation for debugging.
virtual auto clone () const -> AST *=0
Deep copy, except for the type and attachments.
Public Attributes
string field
Additional Inherited Members
Protected Member Functions inherited from yume::ast::Type
AST (Kind kind, span< Token > tok)
AST (const AST &)=delete
AST (AST &&)=default
Protected Member Functions inherited from yume::ast::AST
void unify_val_ty ()
Verify the type compatibility of the depends of this node, and merge the types if possible. This is called every time the node's type is updated.
auto tok () const noexcept -> span< Token >
AST (Kind kind, span< Token > tok)
Detailed Description
A type which refers to a different type, specifically that of a struct field.
Definition at line 364 of file ast.hpp.
Constructor & Destructor Documentation
ProxyType()
yume::ast::ProxyType::ProxyType (span< Token > tok, string field) inline explicit
Definition at line 368 of file ast.hpp.
Referenced by clone().
Member Function Documentation
clone()
auto yume::ast::ProxyType::clone () const -> ProxyType *override override virtual
Deep copy, except for the type and attachments.
Implements yume::ast::Type.
Definition at line 99 of file ast.cpp.
References field, ProxyType(), and yume::ast::AST::tok().
describe()
auto yume::ast::ProxyType::describe () const -> string inline override virtual
A short, string representation for debugging.
Reimplemented from yume::ast::AST.
Definition at line 370 of file ast.hpp.
visit()
void yume::ast::ProxyType::visit (Visitor & visitor) const override virtual
Recursively visit this ast node and all its constituents.
See also
Visitor
Implements yume::ast::AST.
Definition at line 112 of file visit.cpp.
References field, and visitor.
Member Data Documentation
field
string yume::ast::ProxyType::field
Definition at line 366 of file ast.hpp.
Referenced by clone(), and visit().
The documentation for this struct was generated from the following files:
src/yume/ast/ast.hpp
src/yume/ast/ast.cpp
src/yume/ast/visit.cpp