Yume: yume::ty::Conversion Struct Reference
yume::ty::Conversion Struct Reference
#include <compatibility.hpp>
Public Member Functions
constexpr auto empty () const -> bool
auto to_string () const -> string
Public Attributes
bool dereference = false
bool generic = false
ConversionKind kind {}
Detailed Description
Definition at line 13 of file compatibility.hpp.
Member Function Documentation
empty()
constexpr auto yume::ty::Conversion::empty () const -> bool inline constexpr
Definition at line 18 of file compatibility.hpp.
References dereference, kind, and yume::ty::None.
Referenced by to_string().
to_string()
auto yume::ty::Conversion::to_string () const -> string inline
Definition at line 22 of file compatibility.hpp.
References dereference, empty(), generic, yume::ty::Int, and kind.
Referenced by yume::ast::ImplicitCastExpr::visit().
Member Data Documentation
dereference
bool yume::ty::Conversion::dereference = false
Definition at line 14 of file compatibility.hpp.
Referenced by empty(), and to_string().
generic
bool yume::ty::Conversion::generic = false
Definition at line 15 of file compatibility.hpp.
Referenced by to_string().
kind
ConversionKind yume::ty::Conversion::kind {}
Definition at line 16 of file compatibility.hpp.
Referenced by empty(), and to_string().
The documentation for this struct was generated from the following file:
src/compatibility.hpp