Yume: yume::ty::Conv Struct Reference
yume::ty::Conv Struct Reference
#include <compatibility.hpp>
Public Types
enum struct Kind : uint8_t { None , Int }
Public Member Functions
constexpr auto empty () const -> bool
auto to_string () const -> string
Public Attributes
bool dereference = false
Kind kind {}
Detailed Description
Definition at line 11 of file compatibility.hpp.
Member Enumeration Documentation
Kind
enum struct yume::ty::Conv::Kind : uint8_t strong
Enumerator
None
Int
Definition at line 12 of file compatibility.hpp.
Member Function Documentation
empty()
constexpr auto yume::ty::Conv::empty () const -> bool inline constexpr
Definition at line 20 of file compatibility.hpp.
References dereference, and kind.
Referenced by to_string().
to_string()
auto yume::ty::Conv::to_string () const -> string inline
Definition at line 22 of file compatibility.hpp.
References dereference, empty(), and kind.
Referenced by yume::ast::ImplicitCastExpr::visit().
Member Data Documentation
dereference
bool yume::ty::Conv::dereference = false
Definition at line 17 of file compatibility.hpp.
Referenced by empty(), and to_string().
kind
Kind yume::ty::Conv::kind {}
Definition at line 18 of file compatibility.hpp.
Referenced by empty(), and to_string().
The documentation for this struct was generated from the following file:
src/yume/ty/compatibility.hpp