Yume: yume::semantic::Overload Struct Reference
yume::semantic::Overload Struct Reference
#include <overload.hpp>
Public Member Functions
Overload ()=delete
Overload (Fn *fn) noexcept
auto better_candidate_than (Overload other) const -> bool
void dump (llvm::raw_ostream &stream) const
auto location () const -> Loc
Public Attributes
Fn * fn {}
vector< ty::Compat > compatibilities {}
Substitutions subs
bool viable = false
Detailed Description
Definition at line 22 of file overload.hpp.
Constructor & Destructor Documentation
Overload() [1/2]
yume::semantic::Overload::Overload () delete
Overload() [2/2]
yume::semantic::Overload::Overload (Fn * fn) inline explicit noexcept
Definition at line 29 of file overload.hpp.
References fn.
Member Function Documentation
better_candidate_than()
auto yume::semantic::Overload::better_candidate_than (Overload other) const -> bool
Definition at line 264 of file overload.cpp.
References yume::semantic::compare_implicit_conversions().
Referenced by yume::semantic::OverloadSet::try_best_viable_overload().
dump()
void yume::semantic::Overload::dump (llvm::raw_ostream & stream) const
Definition at line 47 of file overload.cpp.
References yume::Fn::arg_types(), yume::Fn::ast(), yume::Substitutions::empty(), fn, yume::semantic::indirect, yume::semantic::join_args(), yume::Substitutions::mapping(), yume::Fn::name(), yume::Fn::self_ty, and subs.
Referenced by yume::semantic::TypeWalker::expression().
location()
auto yume::semantic::Overload::location () const -> Loc inline
Definition at line 34 of file overload.hpp.
References yume::Fn::ast(), and fn.
Member Data Documentation
compatibilities
vector<ty::Compat> yume::semantic::Overload::compatibilities {}
Definition at line 24 of file overload.hpp.
Referenced by yume::semantic::TypeWalker::expression().
fn
Fn* yume::semantic::Overload::fn {}
Definition at line 23 of file overload.hpp.
Referenced by dump(), yume::semantic::TypeWalker::expression(), location(), and Overload().
subs
Substitutions yume::semantic::Overload::subs
Definition at line 25 of file overload.hpp.
Referenced by dump(), and yume::semantic::TypeWalker::expression().
viable
bool yume::semantic::Overload::viable = false
Definition at line 26 of file overload.hpp.
The documentation for this struct was generated from the following files:
src/yume/semantic/overload.hpp
src/yume/semantic/overload.cpp