Yume: yume::TypeWalker Struct Reference
yume::TypeWalker Struct Reference
Determine the type information of AST nodes. This makes up most of the "semantic" phase of the compiler.
#include <type_walker.hpp>
Public Member Functions
TypeWalker (Compiler &compiler)
auto visit (ast::AST &expr, const char *label) -> TypeWalker &override
auto visit (std::nullptr_t null, const char *label) -> TypeWalker &override
auto visit (const string &str, const char *label) -> TypeWalker &override
void body_statement (ast::Stmt &)
void body_expression (ast::Expr &)
template<>
void expression (ast::NumberExpr &expr)
template<>
void expression (ast::StringExpr &expr)
template<>
void expression (ast::CharExpr &expr)
template<>
void expression (ast::BoolExpr &expr)
template<>
void expression (ast::Type &expr)
template<>
void expression (ast::TypeName &expr)
template<>
void expression (ast::CtorExpr &expr)
template<>
void expression (ast::SliceExpr &expr)
template<>
void expression (ast::AssignExpr &expr)
template<>
void expression (ast::VarExpr &expr)
template<>
void expression (ast::FieldAccessExpr &expr)
template<>
void expression (ast::CallExpr &expr)
template<>
void statement (ast::Compound &stat)
template<>
void statement (ast::FnDecl &stat)
template<>
void statement (ast::ReturnStmt &stat)
template<>
void statement (ast::VarDecl &stat)
Public Member Functions inherited from yume::CRTPWalker< TypeWalker, false >
auto body_statement (maybe_const_t< Const, ast::Stmt > &stat, auto &&... args)
auto body_expression (maybe_const_t< Const, ast::Expr > &expr, auto &&... args)
Public Member Functions inherited from yume::Visitor
Visitor ()=default
virtual ~Visitor ()=default
Visitor (Visitor &)=delete
Visitor (Visitor &&)=default
auto operator= (Visitor &) -> Visitor &=delete
auto operator= (Visitor &&) -> Visitor &=default
virtual auto visit (ast::AST &, const char *) -> Visitor &=0
virtual auto visit (std::nullptr_t, const char *) -> Visitor &=0
virtual auto visit (const string &, const char *) -> Visitor &=0
virtual auto visit (ast::AST &expr) -> Visitor &
virtual auto visit (std::nullptr_t) -> Visitor &
virtual auto visit (const string &str) -> Visitor &
template<typename T >
auto visit (vector< T > &vector, const char *label=nullptr) -> Visitor &
template<typename T >
auto visit (unique_ptr< T > &ptr, const char *label=nullptr) -> Visitor &
template<typename T >
auto visit (optional< T > &opt, const char *label=nullptr) -> Visitor &
template<typename T >
auto visit (std::pair< T, const char * > &pair) -> Visitor &
void visit ()
Public Attributes
friend CRTPWalker
Compiler & m_compiler
Fn * m_current_fn {}
std::map< string, ast::AST * > m_scope {}
bool m_in_depth = false
Whether or not to compile the bodies of methods. Initially, on the parameter types of methods are traversed and converted, then everything else in a second pass.
Detailed Description
Determine the type information of AST nodes. This makes up most of the "semantic" phase of the compiler.
Definition at line 18 of file type_walker.hpp.
Constructor & Destructor Documentation
TypeWalker()
yume::TypeWalker::TypeWalker (Compiler & compiler) inline explicit
Definition at line 34 of file type_walker.hpp.
Member Function Documentation
body_expression()
void yume::TypeWalker::body_expression (ast::Expr & expr)
Definition at line 341 of file type_walker.cpp.
References yume::CRTPWalker< Derived, Const >::body_expression(), and yume::ast::AST::kind_name().
Referenced by expression(), and statement().
body_statement()
void yume::TypeWalker::body_statement (ast::Stmt & stat)
Definition at line 337 of file type_walker.cpp.
References yume::CRTPWalker< Derived, Const >::body_statement(), and yume::ast::AST::kind_name().
Referenced by expression(), and statement().
expression() [1/12]
template<> void yume::TypeWalker::expression (ast::AssignExpr & expr)
Definition at line 63 of file type_walker.cpp.
References body_expression(), yume::ast::AssignExpr::target(), and yume::ast::AssignExpr::value().
expression() [2/12]
template<> void yume::TypeWalker::expression (ast::BoolExpr & expr)
Definition at line 29 of file type_walker.cpp.
References yume::TypeHolder::bool_type, m_compiler, and yume::ast::AST::val_ty().
expression() [3/12]
template<> void yume::TypeWalker::expression (ast::CallExpr & expr)
Definition at line 112 of file type_walker.cpp.
References yume::ast::CallExpr::args(), body_expression(), body_statement(), yume::Compiler::declare(), yume::ast::Program::direct_body(), yume::ty::Type::Compatiblity::INVALID, yume::join_args(), m_compiler, m_current_fn, m_in_depth, yume::Fn::m_instantiations, yume::Fn::m_member, m_scope, yume::Instantiation::m_sub, yume::ast::CallExpr::name(), yume::ast::CallExpr::selected_overload(), and yume::ast::AST::val_ty().
expression() [4/12]
template<> void yume::TypeWalker::expression (ast::CharExpr & expr)
Definition at line 27 of file type_walker.cpp.
References yume::TypeHolder::int8(), m_compiler, and yume::ast::AST::val_ty().
expression() [5/12]
template<> void yume::TypeWalker::expression (ast::CtorExpr & expr)
Definition at line 45 of file type_walker.cpp.
References yume::ast::CtorExpr::args(), body_expression(), yume::Compiler::convert_type(), m_compiler, m_current_fn, yume::Fn::parent(), yume::ast::CtorExpr::type(), and yume::ast::AST::val_ty().
expression() [6/12]
template<> void yume::TypeWalker::expression (ast::FieldAccessExpr & expr)
Definition at line 76 of file type_walker.cpp.
References yume::ast::FieldAccessExpr::base(), body_expression(), yume::Compiler::convert_type(), yume::ast::FieldAccessExpr::field(), m_compiler, yume::ast::FieldAccessExpr::offset(), and yume::ast::AST::val_ty().
expression() [7/12]
template<> void yume::TypeWalker::expression (ast::NumberExpr & expr)
Definition at line 13 of file type_walker.cpp.
References yume::TypeHolder::int32(), yume::TypeHolder::int64(), m_compiler, yume::ast::NumberExpr::val(), and yume::ast::AST::val_ty().
expression() [8/12]
template<> void yume::TypeWalker::expression (ast::SliceExpr & expr)
Definition at line 54 of file type_walker.cpp.
References yume::ast::SliceExpr::args(), body_expression(), yume::Compiler::convert_type(), m_compiler, m_current_fn, yume::Fn::parent(), yume::ast::SliceExpr::type(), and yume::ast::AST::val_ty().
expression() [9/12]
template<> void yume::TypeWalker::expression (ast::StringExpr & expr)
Definition at line 22 of file type_walker.cpp.
References yume::TypeHolder::int8(), m_compiler, and yume::ast::AST::val_ty().
expression() [10/12]
template<> void yume::TypeWalker::expression (ast::Type & expr)
Definition at line 31 of file type_walker.cpp.
References yume::Compiler::convert_type(), m_compiler, m_current_fn, yume::Fn::parent(), and yume::ast::AST::val_ty().
expression() [11/12]
template<> void yume::TypeWalker::expression (ast::TypeName & expr)
Definition at line 39 of file type_walker.cpp.
References yume::ast::AST::attach_to(), and yume::ast::TypeName::type().
expression() [12/12]
template<> void yume::TypeWalker::expression (ast::VarExpr & expr)
Definition at line 69 of file type_walker.cpp.
References yume::ast::AST::attach_to(), m_scope, and yume::ast::VarExpr::name().
statement() [1/4]
template<> void yume::TypeWalker::statement (ast::Compound & stat)
Definition at line 279 of file type_walker.cpp.
References yume::ast::Compound::body(), and body_statement().
statement() [2/4]
template<> void yume::TypeWalker::statement (ast::FnDecl & stat)
Definition at line 285 of file type_walker.cpp.
References yume::ast::FnDecl::args(), yume::ast::AST::attach_to(), yume::ast::FnDecl::body(), m_current_fn, m_in_depth, m_scope, yume::Fn::m_subs, and yume::ast::FnDecl::ret().
statement() [3/4]
template<> void yume::TypeWalker::statement (ast::ReturnStmt & stat)
Definition at line 308 of file type_walker.cpp.
References yume::ast::AST::attach_to(), body_expression(), yume::ast::ReturnStmt::expr(), yume::Fn::m_ast_decl, and m_current_fn.
statement() [4/4]
template<> void yume::TypeWalker::statement (ast::VarDecl & stat)
Definition at line 315 of file type_walker.cpp.
References body_expression(), yume::ast::VarDecl::init(), m_scope, yume::ast::VarDecl::name(), yume::ast::VarDecl::type(), and yume::ast::AST::val_ty().
visit() [1/3]
auto yume::TypeWalker::visit (ast::AST & expr, const char * label) -> TypeWalker& override virtual
Implements yume::Visitor.
Definition at line 327 of file type_walker.cpp.
visit() [2/3]
auto yume::TypeWalker::visit (const string & str, const char * label) -> TypeWalker& inline override virtual
Implements yume::Visitor.
Definition at line 43 of file type_walker.hpp.
visit() [3/3]
auto yume::TypeWalker::visit (std::nullptr_t null, const char * label) -> TypeWalker& inline override virtual
Implements yume::Visitor.
Definition at line 39 of file type_walker.hpp.
Member Data Documentation
CRTPWalker
friend yume::TypeWalker::CRTPWalker
Definition at line 23 of file type_walker.hpp.
m_compiler
Compiler& yume::TypeWalker::m_compiler
Definition at line 26 of file type_walker.hpp.
Referenced by expression().
m_current_fn
Fn* yume::TypeWalker::m_current_fn {}
Definition at line 27 of file type_walker.hpp.
Referenced by expression(), and statement().
m_in_depth
bool yume::TypeWalker::m_in_depth = false
Whether or not to compile the bodies of methods. Initially, on the parameter types of methods are traversed and converted, then everything else in a second pass.
Definition at line 32 of file type_walker.hpp.
Referenced by expression(), and statement().
m_scope
std::map<string, ast::AST*> yume::TypeWalker::m_scope {}
Definition at line 28 of file type_walker.hpp.
Referenced by expression(), and statement().
The documentation for this struct was generated from the following files:
src/compiler/type_walker.hpp
src/compiler/type_walker.cpp